// Auto-generated from "Herbal Medicine: From the Heart of the Earth" by Sharol Tilgner
// Tincture/liquid extract drop dose ranges; drops used as stated
// herb_id → { min: drops, max: drops }
export const HOTE_MATERIA_MEDICA: Record<number, { min: number; max: number }> = {
  9: { min: 20, max: 60 },   // Siberian Ginseng (Eleutherococcus senticosus)
  14: { min: 20, max: 60 },  // Ginseng (Panax ginseng)
  15: { min: 20, max: 60 },  // American Ginseng (Panax quinquefolius)
  16: { min: 30, max: 120 }, // Rhodiola (Rhodiola rosea)
  17: { min: 10, max: 50 },  // Schizandra (Schisandra chinensis)
  20: { min: 10, max: 60 },  // Ashwagandha (Withania somnifera)
  21: { min: 30, max: 60 },  // Garlic (Allium sativum)
  22: { min: 20, max: 60 },  // Burdock (Arctium lappa)
  23: { min: 2, max: 10 },   // Wild Indigo (Baptisia tinctoria)
  24: { min: 10, max: 30 },  // Fringetree (Chionanthus virginicus)
  25: { min: 10, max: 60 },  // Black Cohosh (Actaea racemosa)
  26: { min: 10, max: 120 }, // Echinacea (Echinacea spp.)
  28: { min: 30, max: 75 },  // Cleavers (Galium aparine)
  30: { min: 10, max: 60 },  // Goldenseal (Hydrastis canadensis)
  31: { min: 1, max: 5 },    // Blue Flag (Iris versicolor)
  32: { min: 10, max: 60 },  // Chaparral (Larrea tridentata)
  33: { min: 10, max: 60 },  // Oregon Grape (Mahonia aquifolium)
  35: { min: 1, max: 10 },   // Poke Root (Phytolacca americana)
  36: { min: 1, max: 5 },    // Pasqueflower (Pulsatilla vulgaris)
  37: { min: 10, max: 40 },  // Yellow Dock (Rumex crispus)
  38: { min: 1, max: 2 },    // Bloodroot (Sanguinaria canadensis)
  39: { min: 10, max: 30 },  // Figwort (Scrophularia nodosa)
  40: { min: 10, max: 40 },  // Sarsaparilla (Smilax spp.)
  41: { min: 10, max: 30 },  // Queen's Delight (Stillingia sylvatica)
  42: { min: 10, max: 60 },  // Red Clover (Trifolium pratense)
  43: { min: 10, max: 60 },  // Nettle (Urtica dioica) leaf
  44: { min: 5, max: 30 },   // Yarrow (Achillea millefolium)
  45: { min: 30, max: 60 },  // Marshmallow (Althaea officinalis)
  46: { min: 10, max: 90 },  // Bearberry / Uva Ursi (Arctostaphylos uva-ursi)
  47: { min: 1, max: 5 },    // Cayenne (Capsicum annuum)
  50: { min: 10, max: 40 },  // Boneset (Eupatorium perfoliatum)
  51: { min: 10, max: 60 },  // Eyebright (Euphrasia spp.)
  52: { min: 10, max: 60 },  // Cranesbill (Geranium maculatum)
  53: { min: 10, max: 60 },  // Hyssop (Hyssopus officinalis)
  54: { min: 10, max: 60 },  // Elecampane (Inula helenium)
  55: { min: 10, max: 30 },  // Peppermint (Mentha piperita)
  56: { min: 10, max: 40 },  // Sage (Salvia officinalis)
  57: { min: 10, max: 60 },  // Elder (Sambucus nigra) flower
  58: { min: 10, max: 50 },  // Goldenrod (Solidago virgaurea)
  59: { min: 10, max: 30 },  // Thyme (Thymus vulgaris) leaf
  61: { min: 10, max: 40 },  // Mullein (Verbascum thapsus) leaf
  62: { min: 1, max: 5 },    // Horse Chestnut (Aesculus hippocastanum)
  67: { min: 10, max: 30 },  // Pleurisy Root (Asclepias tuberosa)
  70: { min: 20, max: 60 },  // Calendula (Calendula officinalis)
  71: { min: 20, max: 60 },  // Shepherd's Purse (Capsella bursa-pastoris)
  72: { min: 10, max: 30 },  // Blue Cohosh (Caulophyllum thalictroides)
  73: { min: 60, max: 120 }, // Hawthorn (Crataegus spp.) berry
  74: { min: 20, max: 60 },  // Wild Yam (Dioscorea villosa)
  75: { min: 10, max: 60 },  // Meadowsweet (Filipendula ulmaria)
  76: { min: 10, max: 60 },  // Fennel (Foeniculum vulgare)
  78: { min: 20, max: 60 },  // Licorice (Glycyrrhiza glabra)
  79: { min: 10, max: 60 },  // Witch Hazel (Hamamelis virginiana)
  80: { min: 10, max: 60 },  // Devil's Claw (Harpagophytum procumbens)
  81: { min: 10, max: 60 },  // St. John's Wort (Hypericum perforatum)
  82: { min: 10, max: 30 },  // Lavender (Lavandula spp.)
  84: { min: 20, max: 75 },  // Chamomile (Matricaria recutita)
  85: { min: 15, max: 40 },  // Plantain (Plantago major)
  87: { min: 10, max: 60 },  // Willow (Salix spp.)
  88: { min: 20, max: 75 },  // Chickweed (Stellaria media)
  90: { min: 20, max: 40 },  // Linden (Tilia platyphyllos)
  91: { min: 10, max: 50 },  // Fenugreek (Trigonella foenum-graecum)
  93: { min: 20, max: 75 },  // Cramp Bark (Viburnum opulus)
  95: { min: 10, max: 75 },  // Corn Silk (Zea mays)
  98: { min: 20, max: 30 },  // Caraway (Carum carvi)
  99: { min: 10, max: 40 },  // Myrrh (Commiphora molmol)
  102: { min: 1, max: 20 },  // Gentian (Gentiana lutea)
  103: { min: 10, max: 30 }, // Juniper (Juniperus communis)
  104: { min: 20, max: 60 }, // Osha (Ligusticum porteri)
  109: { min: 10, max: 30 }, // Rosemary (Rosmarinus officinalis)
  110: { min: 1, max: 4 },   // Rue (Ruta graveolens)
  112: { min: 20, max: 60 }, // Usnea (Usnea spp.)
  114: { min: 1, max: 10 },  // Arnica (Arnica montana)
  115: { min: 1, max: 20 },  // Mugwort (Artemisia vulgaris)
  117: { min: 10, max: 40 }, // Gravel Root (Eupatorium purpureum)
  120: { min: 10, max: 50 }, // Parsley (Petroselinum crispum)
  121: { min: 10, max: 40 }, // Feverfew (Tanacetum parthenium)
  122: { min: 1, max: 60 },  // Dandelion (Taraxacum officinale) root
  123: { min: 5, max: 15 },  // Prickly Ash (Zanthoxylum americanum)
  124: { min: 10, max: 60 }, // Ginger (Zingiber officinale)
  127: { min: 20, max: 30 }, // Cardamom (Elettaria cardamomum)
  128: { min: 20, max: 60 }, // California Poppy (Eschscholzia californica)
  129: { min: 10, max: 60 }, // Hops (Humulus lupulus)
  131: { min: 20, max: 40 }, // Motherwort (Leonurus cardiaca)
  132: { min: 1, max: 10 },  // Lobelia (Lobelia inflata)
  133: { min: 10, max: 60 }, // Bugleweed (Lycopus spp.)
  134: { min: 10, max: 60 }, // Lemon Balm (Melissa officinalis)
  135: { min: 10, max: 30 }, // Pennyroyal (Mentha pulegium)
  136: { min: 10, max: 60 }, // Catnip (Nepeta cataria)
  137: { min: 10, max: 60 }, // Passionflower (Passiflora incarnata)
  138: { min: 60, max: 120 }, // Kava (Piper methysticum)
  140: { min: 10, max: 40 }, // Wild Cherry Bark (Prunus serotina)
  142: { min: 20, max: 60 }, // Skullcap (Scutellaria lateriflora)
  143: { min: 1, max: 10 },  // Skunk Cabbage (Symplocarpus foetidus)
  144: { min: 10, max: 30 }, // Damiana (Turnera diffusa)
  145: { min: 10, max: 60 }, // Valerian (Valeriana officinalis)
  146: { min: 5, max: 15 },  // Vervain (Verbena officinalis)
  154: { min: 20, max: 60 }, // Rhubarb (Rheum palmatum)
  155: { min: 10, max: 60 }, // Raspberry (Rubus idaeus) leaf
  158: { min: 10, max: 60 }, // Barberry (Berberis vulgaris)
  160: { min: 1, max: 30 },  // Horehound (Marrubium vulgare)
  163: { min: 1, max: 10 },  // Lily Of The Valley (Convallaria majalis)
  167: { min: 10, max: 60 }, // Cinnamon (Cinnamomum spp.)
  172: { min: 10, max: 60 }, // Artichoke (Cynara scolymus)
  174: { min: 1, max: 10 },  // Butternut (Juglans cinerea)
  175: { min: 1, max: 20 },  // Black Root / Culver's Root (Leptandra virginica)
  178: { min: 20, max: 60 }, // Oat (Avena sativa) milky oats
  179: { min: 30, max: 60 }, // Couch Grass (Elymus repens)
  182: { min: 20, max: 60 }, // Stoneroot (Collinsonia canadensis)
  186: { min: 10, max: 60 }, // Saw Palmetto (Serenoa repens)
  188: { min: 10, max: 40 }, // Partridgeberry (Mitchella repens)
  190: { min: 20, max: 75 }, // Chasteberry (Vitex agnus-castus)
  199: { min: 10, max: 40 }, // Gumweed (Grindelia camporum)
  200: { min: 10, max: 40 }, // Lungwort (Pulmonaria officinalis)
  203: { min: 10, max: 90 }, // Turmeric (Curcuma longa)
  205: { min: 20, max: 70 }, // Cascara Sagrada (Rhamnus purshiana)
  206: { min: 20, max: 60 }, // Milk Thistle (Silybum marianum)
  207: { min: 10, max: 30 }, // Wood Betony (Stachys officinalis)
  211: { min: 1, max: 15 },  // Mistletoe (Viscum album)
  216: { min: 20, max: 60 }, // Senna (Senna alexandrina)
  218: { min: 10, max: 30 }, // Guarana (Paullinia cupana)
  225: { min: 1, max: 50 },  // Astragalus (Astragalus membranaceus)
  274: { min: 10, max: 40 }, // Privet / Ligustrum (Ligustrum lucidum)
  288: { min: 1, max: 10 },  // Black Walnut (Juglans nigra)
  291: { min: 10, max: 50 }, // Pau D'arco (Tabebuia impetiginosa)
  309: { min: 10, max: 40 }, // Yerba Mansa (Anemopsis californica)
  406: { min: 10, max: 30 }, // Oregano (Origanum vulgare)
  448: { min: 10, max: 60 }, // Ma Huang (Ephedra sinica)
  450: { min: 20, max: 60 }, // Khella (Ammi visnaga)
  590: { min: 10, max: 50 }, // Yerba Santa (Eriodictyon californicum)
  591: { min: 10, max: 60 }, // Devil's Club (Oplopanax horridus)
  877: { min: 10, max: 40 }, // Guggul (Commiphora mukul)
  885: { min: 30, max: 60 }, // Alfalfa (Medicago sativa)
  956: { min: 10, max: 60 }, // Dan Shen (Salvia miltiorrhiza)
  980: { min: 10, max: 30 }, // Lomatium (Lomatium dissectum)
  981: { min: 20, max: 40 }, // Red Root (Ceanothus americanus)
  1009: { min: 10, max: 60 }, // Dong Quai (Angelica sinensis)
  1014: { min: 10, max: 40 }, // Lady's Mantle (Alchemilla vulgaris)
  1122: { min: 10, max: 60 }, // Goat's Rue (Galega officinalis)
  1124: { min: 20, max: 40 }, // Blessed Thistle (Cnicus benedictus)
  1160: { min: 20, max: 40 }, // Bilberry (Vaccinium myrtillus)
  1648: { min: 1, max: 60 },  // Dandelion (Taraxacum officinale) leaf
  1649: { min: 20, max: 60 }, // Nettle (Urtica dioica) root
  2229: { min: 20, max: 60 }, // Gotu Kola (Centella asiatica)
  2232: { min: 30, max: 120 }, // Gymnema (Gymnema sylvestre)
  2239: { min: 10, max: 60 }, // Pipsissewa (Chimaphila umbellata)
  2241: { min: 10, max: 60 }, // White Oak (Quercus alba)
  2244: { min: 10, max: 50 }, // Yucca (Yucca spp.)
  2363: { min: 10, max: 60 }, // Spilanthes / Paracress (Acmella oleracea)
};
