// Auto-generated by parse-mm-materia-medica.py
// Michael Moore Herbal Materia Medica 5.0 — herb_id → entry text
export const MM_MATERIA_MEDICA: Record<number, string> = {
  // Siberian Ginseng (Eleutherococcus senticosus)
  9: `ELEUTHEROCOCCUS (Acanthopanax,  Siberian Ginseng)
  ROOT.  Tincture [1:5, 60% alcohol] 20-60 drops. Cold Infusion, 2-4 ounces,
  both to 3X a day.
  STATUS : W/LA/C`,

  // Ginseng (Panax ginseng)
  14: `*PANAX GINSENG (Asian Ginseng)
  ROOT.  Tincture [1:5, 70% alcohol].
  KIRIN (dark red Chinese cured root) 5-20 drops.
  SHIU-CHIU (light red Chinese cured) 10-30 drops.
  KOREAN RED, 5-15 drops.
  WHITE (Chinese or Korean uncured) 20-40 drops, all to 3X a day.
  Capsules, "Red Ginseng" (Kirin or Korean Red) to 4X  a day. "White", to 6 a
  day. Chewing root pieces is more reliable than the unidentifiable substances
  found in capsules.  With the cost of Ginseng, tinctures are the most
  bioavailable form.
  STATUS : C`,

  // Garlic (Allium sativum)
  21: `ALLIUM SATIVUM  (Garlic)
  BULB. Fresh Juice, 1/4 to 1 teaspoon.  Fresh Tincture [1:2] 15-40 drops.
  STATUS : C`,

  // Burdock (Arctium lappa)
  22: `ARCTIUM  (Burdock)
  ROOT. Cold Infusion, 2-4 ounces. Fluidextract [1:1, 60% alcohol] 15-30 drops.
  Tincture [Fresh Root, 1:2, Dry Root, 1:5, 60% alcohol] 30-90 drops, all 3X a
  day.
  SEED. Tincture [1:5, 60% alcohol] 10-25 drops.
  STATUS : W/C`,

  // Wild Indigo (Baptisia tinctoria)
  23: `BAPTISIA  (Wild Indigo Root)
  ROOT. Tincture [1:5, 65% alcohol],
  WHOLE PLANT. Fresh Tincture [1:2], both taken 10-25 drops, to 3X a day.
  USE WITH CARE; better long term in formulas
  STATUS : W/A`,

  // Fringetree (Chionanthus virginicus)
  24: `CHIONANTHUS  (Fringetree)
  BARK. Cold Infusion, 2-4 ounces.  Tincture [Fresh Bark, 1:2, Dry Bark, 1:5,
  65% alcohol] 30-60 drops.
  LEAF. Cold Infusion, 2-4 ounces.
  STATUS : W/LA`,

  // Echinacea (Echinacea spp.)
  26: `ECHINACEA ANGUSTIFOLIA ,E.PALLIDA  (Ks. Snakeroot, Purple Coneflower)
  ROOT and FLOWERS.  Tincture [Fresh Plant 1:2, Dry Plant, 1:5, 70% alcohol],
  30-100 drops as needed.  Cold Infusion 2-6 ounces, all to 5X a day.
  Fluidextract  [1:1, 65% alcohol] 10-30 drops.
  STATUS : W/LA/C`,

  // Fumitory (Fumaria officinalis)
  27: `FUMARIA (Fumitory)
  DRIED HERB. Standard Infusion, 2-4 ounces. Tincture [1:5,50% alcohol], 45-90
  drops.
  STATUS : W/A`,

  // Cleavers (Galium aparine)
  28: `GALIUM APARINE  (Cleavers, Bedstraw)
  WHOLE PLANT.  Cold or Standard Infusion, as needed.  Fresh Plant Tincture
  [1:2] 1-2 teaspoons. Fresh plant juice, 1/2 to 1 teaspoon, all to 4X a day.
  STATUS : W/A`,

  // Guaiacum (Guaiacum officinale)
  29: `GUAIACUM OFFICINALE (Lignum Vitae, Guaiac Wood)
  BARK  OR WOOD. Tincture [1:5, 95% alcohol] 5-15 drops in water, frequently.
  As a gargle, the same as above.
  STATUS : W/LA`,

  // Goldenseal (Hydrastis canadensis)
  30: `*HYDRASTIS  (Golden Seal)
  ROOT/LEAF. Fresh Plant Tincture [1:2], 15-30 drops. Dry Root Tincture, [1:5,
  70% alcohol] 20-50 drops.  Dry Herb Tincture [1:5, 60% alcohol] 30-75 drops
  all the above to 4X a day.  Dry Root capsules #00, 2-4, to 3X a day.
  Standard Infusion of leaf 1-3 ounces, to 4X a day.
  The root is only partially soluble in water and should not be wasted in tea.
  STATUS: W/Rare (cultivation has largely failed in recent years, due to plant
  blight and flooding; most of the world's Hydrastis is obtained by poaching
  from isolated old-growth remnants in NE North America.  Most remnant stands
  will have disappeared forever by the time re-cultivation takes up the slack.
  PLEASE use substitutes whenever possible.)`,

  // Chaparral (Larrea tridentata)
  32: `LARREA  (Chaparral, Gobernadora, Creosote Bush)
  LEAFING BRANCHES. Tincture [1:5, 75% alcohol], 20-60 drops.
  Capsules,#00, 2-4 a day.
  Strong Decoction for topical use.
  STATUS : W/A`,

  // Oregon Grape (Mahonia aquifolium)
  33: `MAHONIA (Oregon Grape, Algerita)
  SAME as Berberis.
  STATUS : W/A`,

  // Bogbean (Menyanthes trifoliata)
  34: `MENYANTHES  (Buckbean, Bogbean)
  WHOLE PLANT.  Tincture [Fresh Plant, 1:2, Dry Plant, 1:5, 50% alcohol],
  10-30 drops, to 3X a day.  Cold Infusion, 1-2 ounces, also to 3X a day.
  STATUS : W/LA`,

  // Poke Root (Phytolacca americana)
  35: `*PHYTOLACCA (Poke)
  ROOT and BERRIES. Fresh Tincture, (Root or Berries), [1:2], 2-10 drops.
  Dry Root Tincture [1:5, 50% alcohol] 5-15 drops.
  USE WITH CARE.
  STATUS : W/A`,

  // Pasqueflower (Pulsatilla vulgaris)
  36: `*ANEMONE HIRSUTISSIMA  (Pulsatilla ludoviciana, Pasque Flower)
  FRESH PLANT. Tincture [1:2] 3-10 drops, to 4X a day.
  Use with care.
  STATUS : W/LA`,

  // Yellow Dock (Rumex crispus)
  37: `RUMEX CRISPUS  (Yellow Dock)
  ROOT.  Tincture [Fresh Root, 1:2, Dry Root, 1:5, 50% alcohol], 30-75 drops,
  to 3X a day.  Capsules, #00, 1-2 to 2X a day.  Use with moderation in
  pregnancy.  In all cases it works best in sub-laxative doses.
  STATUS : W/C`,

  // Bloodroot (Sanguinaria canadensis)
  38: `*SANGUINARIA  (Bloodroot)
  ROOT. Tincture [1:5, 60% alcohol] 10-15 drops.  Dilute with 2X water for
  tinea application.
  STATUS : W/LA`,

  // Figwort (Scrophularia nodosa)
  39: `SCROPHULARIA  (Figwort)
  HERB.  Standard Infusion, 2-4 ounces, to 3X a day.
  STATUS : W/A`,

  // Sarsaparilla (Smilax spp.)
  40: `SMILAX  (Sarsaparilla)
  ROOT/RHIZOME. Cold Infusion or Strong Decoction, 1-4 ounces, to 3X a day.
  Tincture [Fresh Root,1:2, Dry Root,1:5, 60% alcohol] 30-90 drops to 3X a day
  STATUS : W/A`,

  // Queen’s Delight (Stillingia sylvatica)
  41: `STILLINGIA SYLVATICA  (Queen's Root)
  ROOT.  Tincture [Fresh root,1:2, Recent Dry Root, 1:5, 50% alcohol] 10-30
  drops, preferably in small frequent doses.
  STATUS : W/LA`,

  // Red Clover (Trifolium pratense)
  42: `TRIFOLIUM PRATENSE (Red Clover)
  FLOWERING TOP. Standard Infusion or Strong Decoction, 4-6 ounces to 3X a day
  STATUS : W/C`,

  // Nettle (Urtica dioica)
  43: `URTICA  (Nettles)
  WHOLE HERB.  Cold or Standard infusion, as needed.
  STATUS : W/C`,

  // Yarrow (Achillea millefolium)
  44: `ACHILLEA  (Yarrow, Milfoil, Plumajillo)
  WHOLE FLOWERING PLANT. Tincture [FRESH 1:2, DRY 1:5, 50% alcohol] 10 to 40
  drops.  Standard Infusion, 2-4 ounces.
  ROOT.  Fresh Root Tincture, topical to gums as needed.
  STATUS : W/A`,

  // Marshmallow (Althaea officinalis)
  45: `ALTHEA  (Marshmallow or Hollyhock)
  ROOT. Cold Infusion or Fresh Tincture [1:2] as needed
  HERB. Cold Infusion as needed, or moistened for poultice.
  STATUS : W/C`,

  // Bearberry (Arctostaphylos uva-ursi)
  46: `ARCTOSTAPHYLOS  (Uva Ursi, Manzanita, Bearberry)
  LEAVES.  Tincture [1:5, 50% alcohol] 30-60 drops in 8 oz. of water, to 3X a
  day. Standard Infusion 3-4 ounces to 3X a day.   For sitz bath, 8-12 ounces
  Standard Infusion in warm water; sit in it morning and evening.
  STATUS : W/LA`,

  // Cayenne (Capsicum annuum)
  47: `CAPSICUM  (Cayenne, African Bird Peppers)
  FRUIT. Tincture [1:5, 95% alcohol] 5-15 drops.  Capsules, #0, 1-2.
  STATUS : W/C`,

  // Iceland Moss (Cetraria islandica)
  48: `CETRARIA  (Iceland Moss)
  DRY SEAWEED. 2-4 grams boiled in 8 oz. of fruit juice, drunk WARM.
  STATUS : W/semiC`,

  // Boneset (Eupatorium perfoliatum)
  50: `EUPATORIUM PERFOLIATUM  (Boneset)
  FLOWERING HERB. Fresh Plant Tincture [1:2], 20-40 drops in hot water. Dry
  herb, Cold Infusion (tonic), Standard Infusion (diaphoretic), 2-6 ounces,
  to 3X a day.
  STATUS : W/C`,

  // Eyebright (Euphrasia spp.)
  51: `EUPHRASIA  (Eyebright)
  HERB. Strong Decoction, 2-4 ounces. Tincture [1:5, 50% alcohol] 30-90 drops,
  both to 4X a day.
  STATUS : U`,

  // Cranesbill (Geranium maculatum)
  52: `GERANIUM  (Cranesbill, Alum Root)
  ROOT. Tincture [1:5, 50% alcohol, 10% glycerin] in 1/2 to 1 teaspoon doses.
  Strong Decoction, 1-4 ounces, both to 4X a day.
  STATUS : W/A`,

  // Hyssop (Hyssopus officinalis)
  53: `HYSSOPUS  (Hyssop)
  FLOWERING HERB.  Cold Infusion, 2-3 ounces, or topically for bruises.
  STATUS : W/C`,

  // Elecampane (Inula helenium)
  54: `INULA  (Elecampane)
  ROOT. Tincture [Fresh root, 1:2, Dry Root, 1:5, 60% alcohol], 10-30 drops to
  4X a day. Strong Decoction 2-6 ounces, to 3X a day.
  STATUS : W/C`,

  // Peppermint (Mentha piperita)
  55: `MENTHA PIPERITA  (Peppermint)
  HERB.  Corld or Standard Infusion as needed.
  ESSENTIAL OIL. 10-20 drops in capsules (in a binder), to 3X a day.
  STATUS : W/C`,

  // Sage (Salvia officinalis)
  56: `SALVIA  (Sage)
  FLOWERING HERB. Tincture [Fresh, 1:2, Dry, 1:5, 50% alcohol] 30-60 drops, in
  hot water (diaphoretic) or cold water (tonic).Cold Infusion or Strong
  Decoction 2-4 ounces.
  STATUS : W/C`,

  // Elder (Sambucus nigra)
  57: `SAMBUCUS  (Elder)
  FLOWERS, LEAVES.   Flowers, Standard Infusion 2-4 ounces.  Leaves, Cold
  Infusion 1-2 ounces, both to 3X a day.
  STATUS : W/C`,

  // Goldenrod (Solidago virgaurea)
  58: `SOLIDAGO (Goldenrod)
  HERB.  Standard Infusion, 1-3 ounces everey four hours.
  STATUS : W/A`,

  // Thyme (Thymus vulgaris)
  59: `THYMUS  (Thyme)
  HERB. Standard Infusion, 2-4 ounces, to 4X a day, or topically as needed.
  ESSENTIAL OIL. Diluted w/2 parts vegetable oil as a topical antimicrobial.
  STATUS : W/C`,

  // Coltsfoot (Tussilago farfara)
  60: `TUSSILAGO (Coltsfoot)
  HERB. Standard Infusion, 2-6 ounces, sipped slowly. Unlike its antispasmodic
  relative Petasites, which can irritate the liver when used excessively, this
  is  simple and safe cough therapy.
  STATUS : W/A`,

  // Mullein (Verbascum thapsus)
  61: `VERBASCUM  (Mullein)
  LEAVES. Standard Infusion, 2-4 ounces.
  FLOWERS.Tincture [Fresh Flowers,1:2,Dry Flowers,1:5,60% alcohol] 30-90 drops
  ROOT. Strong Decoction, 2-3 ounces.  All forms to 4X a day.
  STATUS : W/A`,

  // Horse Chestnut (Aesculus hippocastanum)
  62: `*AESCULUS HIPPOCASTANUM (Horse Chestnut)
  BARK and FRUIT. Tincture [1:5, 50% alcohol] 3-10 drops.
  USE WITH CARE.
  STATUS : W/A`,

  // Angelica (Angelica archangelica)
  65: `ANGELICA
  ROOT. Tincture [Fresh Root, 1:2, Dry Root, 1:5, 65% alcohol) 30-60 drops, to
  4X  a day.  Strong Decoction, 1-2 ounces  similarly.
  SEED: Tincture (as previous), 10-30 drops, or several seeds chewed.
  STATUS : W/C`,

  // Celery Seed (Apium graveolens)
  66: `APIUM  (Celery)
  SEED. Simple Infusion, 1/2 to 1 teaspoon of seeds in cup of hot water.
  STATUS : C`,

  // Pleurisy Root (Asclepias tuberosa)
  67: `*ASCLEPIAS TUBEROSA  (Pleurisy Root)
  ROOT. Cold Infusion, 2-4 ounces. Tincture [Fresh, 1:2, Dry, 1:5, 50% alcohol]
  30-90 drops. Capsules, #00, 1-3, all to 3X  a day.
  STATUS : W/C`,

  // Birch (Betula spp.)
  68: `BETULA   (Birch)
  BARK. Strong Decoction, 1-2 ounces, to 4X a day; external wash.
  LEAVES. Standard Infusion as bath or wash, as needed.
  STATUS : W/A`,

  // Calendula (Calendula officinalis)
  70: `CALENDULA OFFICINALIS   (European Marigold)
  FLOWERS.  Tincture [Fresh Flowers, 1:2, Dry Flowers, 1:5, 70% alcohol] 5-30
  drops, to 4X a day.  Dilute with several parts of water for topical use.
  STATUS : W/C`,

  // Shepherd’s Purse (Capsella bursa-pastoris)
  71: `*CAPSELLA BURSA-PASTORIS  (Shepherd's Purse)
  WHOLE PLANT. Tincture (Fresh Plant, 1:2, recent Dry Plant, 1:5, 50% alcohol]
  20-60 drops.
  STATUS : W/A`,

  // Blue Cohosh (Caulophyllum thalictroides)
  72: `*CAULOPHYLLUM  (Blue Cohosh)
  RHIZOME / ROOT. Tincture [1:5, 60% alcohol] 5-20 drops, usually in formula
  context.
  STATUS : W/LA`,

  // Hawthorn (Crataegus spp.)
  73: `CRATAEGUS  (Hawthorn)
  BERRIES, FLOWERING BRANCHES. Tincture [Fresh Plant, 1:2, Dry Berries, 1:5,
  60% alcohol] 10-30 drops, to 3X a day.
  Cold Infusion (berries) 1-2 ounces, to 2X a day.
  STATUS : W/C`,

  // Wild Yam (Dioscorea villosa)
  74: `DIOSCOREA VILLOSA  (Wild Yam)
  ROOT. Tincture [Fresh ROOT, 1:2, Dry Root, 1:5, 60% alcohol] 30-100 drops,
  to 4X a day. Fluidextract [1:1, 55% alcohol] 10-25 drops.
  Cold Infusion, 2-4 ounces to 4X a day.
  STATUS : W/LA`,

  // Meadowsweet (Filipendula ulmaria)
  75: `FILIPENDULA  (Spiraea, Meadowsweet)
  FLOWERING HERB.  Fresh Tincture [1:2], 60-90 drops, Dry Tincture [1:5, 50%
  alcohol], 90-120 drops, Standard Infusion, 3-6 ounces all to 4X a day.
  STATUS : W/A`,

  // Fennel (Foeniculum vulgare)
  76: `FOENICULUM  (Fennel Seed)
  SEED.  Tincture [1:5, 60% alcohol] 30-60 drops in warm water as needed.
  Standard Infusion as needed.
  STATUS : C`,

  // Wintergreen (Gaultheria procumbens)
  77: `GAULTHERIA  (Wintergreen)
  ESSENTIAL OIL, INTERNALLY: 2-5 drops in capsule.
  EXTERNALLY, diluted with four parts vegetable oil for liniment.
  RECENT HERB. Standard Infusion in frequent 2-4 ounce doses.
  STATUS : U`,

  // Licorice (Glycyrrhiza glabra)
  78: `*GLYCYRRHIZA GLABRA  (Licorice)
  ROOT. Tincture [1:5, 50% alcohol] 3-60 drops. Strong Decoction, 1-3 ounces,
  either to 3X a day.  Can occasion sodium retention.
  STATUS : C`,

  // Witch Hazel (Hamamelis virginiana)
  79: `HAMAMELIS  (Witch Hazel)
  TWIGS AND LEAVES.  Tincture [Fresh Herb, 1:2] 10-60 drops as needed, and
  diluted for topical use.
  BARK. Servicable as Standard Decoction topically.
  STATUS : W/C`,

  // Devil’s Claw (Harpagophytum procumbens)
  80: `HARPAGOPHYTUM PROCUMBENS  (Devil's Claw)
  TUBERS. Capsules, #0, 2-4 in evenings.  Cold Infusion 4-6 ounces similarly.
  Strong Tincture [1:2, 60% alcohol], 1/2 to 1 teaspoons. Some recommend that
  two weeks on and two weeks off is the best approach to Devil's Claw. I have
  found a month of continuous use is the best way to begin.
  STATUS : W/Rare/Cult.(w/little success)`,

  // St. John’s Wort (Hypericum perforatum)
  81: `HYPERICUM  (St. Johns Wort)
  FLOWERING TOPS. Tincture [Fresh Plant, 1:2] 20-30 drops to 3X a day. The dry
  plant is far less active, but a Standard Infusion can be taken, 3-6 ounces.
  STATUS : W/C`,

  // Lavender (Lavandula spp.)
  82: `LAVANDULA  (Lavender)
  FLOWERS.  Standard Infusion, 2-3 ounces to 4X a day.
  ESSENTIAL OIL. 5-10  drops in capsule, with food.
  STATUS : W/C`,

  // Chamomile (Matricaria recutita)
  84: `MATRICARIA  (Chamomile, Manzanilla)
  FLOWERS. Standard or Cold Infusion, 2-6 ounces as needed.
  STATUS : W/C`,

  // Plantain (Plantago major)
  85: `PLANTAGO MAJOR  (Plantain)
  FRESH LEAF.  Fresh or frozen juice, 1-2 tablespoons to 4X a day.
  STATUS : W/A`,

  // Willow (Salix spp.)
  87: `SALIX  (Willow)
  BARK.  Strong Decoction, 2-4 ounces to 4X a day.
  STATUS : W/A`,

  // Chickweed (Stellaria media)
  88: `STELLARIA MEDIA (Chickweed)
  HERB.  Fresh plant juice or bruised whole plant as a poultice.  Tincture
  [Fresh Herb, 1:2, Recent Dry Herb 1:5, 50% alcohol] as needed.
  STATUS : W/A`,

  // Comfrey (Symphytum officinale)
  89: `SYMPHYTUM  (Comfrey)
  LEAF and ROOT. Leaf, Standard Infusion 2-6 ounces. Root, Cold Infusion, 1-4
  ounces, both to 3X a day,for short term use. Constant use of some cultivated
  strains can irritate or damage the liver.
  STATUS : C`,

  // Cramp Bark (Viburnum opulus)
  93: `VIBURNUM (V. opulus, V. prunifolium, Cramp Bark, Black Haw)
  ROOTBARK and BARK. Cold Infusion or Strong Decoction, 3-4 ounces to 4X a day.
  Tincture [1:5, 50% alcohol] 30-90 drops to 4X a day.
  STATUS : W/LA`,

  // Black Haw (Viburnum prunifolium)
  94: `VIBURNUM (V. opulus, V. prunifolium, Cramp Bark, Black Haw)
  ROOTBARK and BARK. Cold Infusion or Strong Decoction, 3-4 ounces to 4X a day.
  Tincture [1:5, 50% alcohol] 30-90 drops to 4X a day.
  STATUS : W/LA`,

  // Corn Silk (Zea mays)
  95: `ZEA MAYS  (Corn Silk)
  STIGMAS.  Standard Infusion, 4-6 ounces to 3X a day.  Fresh Silk Tincture,
  [1:2], 1/2 to 1 1/2 teaspoons in 8 ounces water.
  STATUS : C`,

  // Caraway (Carum carvi)
  98: `CARUM  (Caraway Seed)
  SEED. Spirit of Caraway (1 part essential oil, 10 parts ethanol) 10-20 drops
  in water, or some chewed seeds or simple tea for indigestion.
  STATUS : W/C`,

  // Myrrh (Commiphora molmol)
  99: `COMMIPHORA  (Myrrh Gum)
  RESIN. Tincture [ 1:5, 95% alcohol] 5-20 drops. Capsules, #0, 1-2, both to
  3X a day.  Topically, dilute tincture with water as needed.
  STATUS : U`,

  // Coriander (Coriandrum sativum)
  100: `CORIANDRUM  (Coriander, Cilantro)
  SEED.  Tincture [1:5, 65% alcohol] 10-20 drops.  Seeds chewed as needed.
  STATUS : C`,

  // Eucalyptus (Eucalyptus spp.)
  101: `EUCALYPTUS
  LEAVES.Standard Infusion, 2-4 ounces, to 4X a day.
  ESSENTIAL OIL,1-5 drops in capsule.
  STATUS : W/C`,

  // Gentian (Gentiana lutea)
  102: `GENTIANA  (Gentian)
  ROOT. Tincture [Fresh Root 1:2,Dry Root,1:5, 50% alcohol] 5-20 drops before
  each meal.
  STATUS : W/A/C`,

  // Juniper (Juniperus communis)
  103: `JUNIPERUS  (Juniper)
  BERRIES. Tincture [1:5, 75% alcohol], 20-40 drops. Standard Infusion, 2-3
  oz., to 3X a day.
  LEAVES: Standard Infusion, 2-4 ounces, or boiled for inhalation. For short
  term use; may irritate the kidneys in time.
  STATUS : W/semi-C`,

  // Osha (Ligusticum porteri)
  104: `LIGUSTICUM PORTERI  (Osha, Chuchupate, Mountain Lovage)
  ROOT. Tincture [Fresh Root, 1:2, Dry Root, 1:5, 70% alcohol], 20-60 drops up
  to 5X a day.  Cold Infusion, 2-6 ounces, as needed.
  STATUS : W/LA`,

  // Balsam Of Peru (Myroxylon balsamum var. pereirae)
  105: `BALSAM OF PERU (Myroxylum  pereirae, Peruvian Balsam)
  RESIN (Dark Brown, syrupy).
  EXTERNAL: Mix one part balsam with two parts of lanolin or lard.
  INTERNAL: 5-10 drops in capsule, taken with a little food.
  STATUS : U`,

  // Olive (Olea europaea)
  106: `OLEA EUROPAEA (Olive)
  LEAVES.  Standard Infusion, 1-3 ounces, to 3X a day.
  STATUS : W/C`,

  // Aniseed (Pimpinella anisum)
  108: `ANISUM  (Anise Seed)
  SEED. Standard Infusion, 2-4 ounces.  Spirit of Anise, 1/4 to 1/2 teaspoon,
  Oil  of Anise, 1-5 drops, all as needed
  STATUS : C`,

  // Rosemary (Rosmarinus officinalis)
  109: `ROSMARINUS  (Rosemary)
  LEAVES.  Standard Infusion 2-4 ounces, to 14X a day or for a topical wash.
  ESSENTIAL OIL.  Capsule, 3-6 drops in a binder, with water.
  STATUS : W/C`,

  // Rue (Ruta graveolens)
  110: `*RUTA GRAVEOLENS  (Rue, Ruda)
  HERB.  Tincture [1:5, 65% alcohol] 5-20 drops. A poultice with the powdered
  leaves for a counterirritant poultice.
  STATUS : W/C`,

  // Clove (Syzygium aromaticum)
  111: `CARYOPHYLLUS  (Cloves)
  UNRIPE BUDS. Essential Oil: 1:4 drops in capsule, taken with food. A piece
  of oil-moistened cotton on or in a tooth, avoiding gums if possible.
  STATUS : C`,

  // Usnea (Usnea spp.)
  112: `USNEA  (Hair Moss, Old Man's Beard)
  HERB. Tincture [1:5, 50% alcohol] 30-60 drops to 4X a day. Moisten the herb
  with a little alcohol and make a Strong Decoction, 2-6 ounces, to 3X a day,
  or use the tea for topical application.
  STATUS : W/A`,

  // Horseradish (Armoracia rusticana)
  113: `ARMORACIA (Cochlearia, Horseradish)
  FRESH ROOT.  Grated root, 1/2 to 1-1/2 tspn. (w/some honey if needed)   STATUS : W/C`,

  // Arnica (Arnica montana)
  114: `*ARNICA  (A. montana, A. cordifolia, A. latiflora, etc.)
  WHOLE PLANT. Fresh plant, flower or root tincture [1:2], dry flowers or herb
  tincture, [1:5, 50% alcohol] and dry root tincture [1:5, 60% alcohol].
  EXTERNAL is diluted with one or two parts of water, applied as needed.
  INTERNAL use  3-10 drops.
  TAKE INTERNALLY WITH CARE
  STATUS : W/C`,

  // Mugwort (Artemisia vulgaris)
  115: `*ARTEMISIA VULGARIS  (Mugwort, California Mugwort)
  HERB. Tincture [1:5, 50% alc.] 10-25 drops;
  Acetum Tincture [1:5, in vinegar] as needed externally.
  Standard Infusion (drunk hot) for diaphoretic, Cold Infusion as tonic.
  STATUS : W/C`,

  // Mustard (Brassica spp.)
  116: `SINAPIS  (Mustard)
  SEED. PLASTER: mix 1 part powdered seed and one part flour, add enough water
  to form a spreadable paste, place between two layers of gauze and apply to
  desired area until skin turns pink...NOT RED (by then it will blister).
  Remove plaster and wash skin.
  STATUS : C`,

  // Gravel Root (Eupatorium purpureum)
  117: `EUPATORIUM PURPUREUM  (Gravel Root, Queen of the Meadow)
  ROOT. Strong Decoction, 2-4 ounces, to 4X a day. Tincture [Fresh Root, 1:2,
  Dry Root, 1:5, 60% alcohol] 30-90 drops in cup of warm water.
  STATUS : W/A`,

  // Kelp (Fucus vesiculosus)
  118: `FUCUS  (Bladderwrack, seawrack)
  WHOLE PLANT. Cold Infusion, 2-4 ounces. Capsules, #00, 1-2, both to 2X a day.
  STATUS : W/C`,

  // Bayberry (Myrica cerifera)
  119: `MYRICA  (Bayberry)
  BARK and ROOTBARK. Tincture [Fresh Bark, 1:2, Dry Bark, 1:5, 60% alcohol]
  20-60 drops.  Cold Infusion, 2-4 ounces, both to 3X a day.  The diluted
  tincture or the infusion for topical use or as a gargle.
  STATUS : W/A`,

  // Parsley (Petroselinum crispum)
  120: `*PETROSELINUM  (Parsley)
  ROOT. Tincture [1:5, 60% alcohol, 30-60 drops in warm water, to 3X a day.
  STATUS : C`,

  // Feverfew (Tanacetum parthenium)
  121: `CHRYSANTHEMUM PARTHENIUM (Tanacetum , Pyrethrum,  Feverfew)
  HERB.  Cold Infusion 2-4 ounces.  Tincture [Fresh plant, 1:2, Dry herb, 1:5,
  50% alcohol] 30-60 drops, to 4X a day.
  STATUS : W/C`,

  // Dandelion (Taraxacum officinale)
  122: `TARAXACUM  (Dandelion)
  ROOT or LEAF.  Root Fluidextract [1:1, 45% alcohol] 30-60 drops up to 4X a
  day.  Tincture [Fresh Root, 1:2] 1/2 to 1 teaspoon.  Strong Decoction, 2-4
  ounces, to 4X a day.  Leaf as Standard Infusion, 3-6 ounces as needed.
  STATUS : W/C`,

  // Ginger (Zingiber officinale)
  124: `ZINGIBER  (Ginger Root)
  ROOT. Fresh Root Tincture [1:2] 10-20 drops in warm water. Strong Decoction
  1-2 ounces, both as needed.
  STATUS : C`,

  // Wild Carrot (Daucus carota)
  125: `*DAUCUS CAROTA  (Carrot, Wild Carrot)
  SEED.  Standard Infusion, 2-6 ounces.  Tincture [1:5, 60% alcohol] 20-60
  drops,  both to 2X a day.
  STATUS : W/A`,

  // Sundew (Drosera rotundifolia)
  126: `DROSERA  (Sundew)
  HERB.  Tincture [Fresh Plant, 1:2], 5-15 drops to 4X a day.
  STATUS : W/LA`,

  // Cardamom (Elettaria cardamomum)
  127: `CARDAMOMUM  (Cardamom Seeds)
  SEEDS.  Tincture [1:5, 50% alcohol] 5-10 drops...or chew a couple seeds,
  already.
  STATUS : W/LA/C`,

  // Hops (Humulus lupulus)
  129: `HUMULUS  (Hops)
  STROBILE.  Tincture [Fresh strobiles, 1:2, Dry strobiles 1:5, 65% alcohol]
  30-90 drops.  Cold Infusion 2-4 ounces, Standard Infusion 3-6 ounces, to 3X
  a day.
  HERB.  Cold or Standard Infusion for topical use, powder for poultice.
  STATUS : W/C`,

  // Wild Lettuce (Lactuca virosa)
  130: `LACTUCA  (Wild Lettuce)
  HERB. Standard Infusion as needed. LATEX (Lactucarium), Tincture [1:2, 95%
  alcohol], 1/2 to 1 teaspoon.
  STATUS : W/A`,

  // Motherwort (Leonurus cardiaca)
  131: `*LEONURUS CARDIACA  (Motherwort)
  FLOWERING HERB. Tincture [Fresh Plant 1:2, Recent Dry Plant, 1:5, 60% alc.]
  30-60 drops, to 4X a day.  Standard Infusion, 2-4 ounces.
  STATUS : W/C`,

  // Lobelia (Lobelia inflata)
  132: `LOBELIA INFLATA  (Lobelia, Indian Tobacco)
  FLOWERING PLANT. Fresh Plant Tincture [1:4] 5-20 drops up to 4X a day.
  Dry Plant Tincture (inferior) is best as an Acetum Tincture [Dry Herb 1:5 in
  vinegar] 10-20 drops, or used for local application.
  SEED. Tincture [1:5, 65% alcohol), 3-10 drops.
  Herb tea is especially nauseating, fresh herb or seed preps only slightly.
  STATUS : W/LA/C`,

  // Bugleweed (Lycopus spp.)
  133: `LYCOPUS  (Bugleweed, Water Horehound)
  HERB. Fresh Plant Tincture [1:2] 15-40 drops, to 3X a day. Standard Infusion
  of recent plant, 2-3 ounces, also to 3X a day.
  STATUS : W/A`,

  // Lemon Balm (Melissa officinalis)
  134: `MELISSA OFFICINALIS  (Lemon Balm)
  FLOWERING HERB.  Standard Infusion as needed.
  STATUS : W/C`,

  // Pennyroyal (Mentha pulegium)
  135: `*MENTHA PULEGIUM  (European Pennyroyal)
  BASAL LEAVES and FLOWERING STALKS.  Same as Hedeoma.
  STATUS : W/C`,

  // Catnip (Nepeta cataria)
  136: `NEPETA CATARIA  (Catnip)
  FLOWERING HERB. Tincture [Fresh Herb 1:2, Recent Dry Herb 1:5, 50% alc.],
  1/4 to 1 teaspoon  Standard Infusion, 2-6 ounces, all to 4X a day.
  STATUS : W/C`,

  // Passionflower (Passiflora incarnata)
  137: `PASSIFLORA  (Passion Flower)
  WHOLE HERB. Tincture [Fresh Plant 1:2, Dry Herb, 1:5, 50% alcohol] .5 to
  1.5 teapoon.  Fluidextract [1:1, 45% alcohol], 30-60 drops. Standard Infusion
  of recent herb, 2-6 ounces, all forms to 4X a day.
  STATUS : W/C`,

  // Kava (Piper methysticum)
  138: `PIPER METHYSTICUM  (Kava Kava, Ava)
  ROOT.  Tincture [Fresh Root 1:2, Recent Dry Root 1:5, 60% alcohol] 30-90
  drops to 4X a day.   Fluidextract [1:1, 55% alcohol] 10-30 drops.  Cold
  Infusion, 2-6 oz.  all to 4X a day.
  STATUS : W/LA/C`,

  // Jamaica Dogwood (Piscidia erythrina)
  139: `PISCIDIA  (Jamaica Dogwood, Jabin)
  TREE and ROOT BARK. Tincture [1:5, 60% alcohol] 10-90 drops.
  USE WITH CARE.  Response is highly individual, so start with a low dose.
  STATUS : W/LA`,

  // Wild Cherry Bark (Prunus serotina)
  140: `PRUNUS  (Wild Cherry, Choke Cherry)
  SUMMER or FALL BARK.  Cold Infusion 2-6 ounces, to 3X a day. Tincture [1:5,
  60% alcohol, 10% glycerin] 30-90 drops, to 4X a day.
  STATUS : W/A`,

  // Skullcap (Scutellaria lateriflora)
  142: `SCUTELLARIA  (Skullcap)
  HERB. Tincture  [Fresh Plant, 1:2, Recent Dry Plant, 1:5, 50% alcohol] 20-60
  drops.  Standard Infusion of recent herb, 2-6 ounces, all to 3X a day.
  STATUS : W/C`,

  // Damiana (Turnera diffusa)
  144: `*TURNERA DIFFUSA  (Damiana)
  FLOWERING HERB.  Fresh Plant Tincture [1:2] 20-30 drops.  Standard Infusion
  2-4 ounces. Dry Plant Tincture (inferior) [1:5, 60% alcohol] 30-60 drops,
  all to 3X a day.
  STATUS : W/LA`,

  // Valerian (Valeriana officinalis)
  145: `VALERIANA  (Valerian)
  PLANT. Tincture [Fresh Whole Plant 1:2, Dry Root, 1:5, 70% alcohol], 30-90
  drops, to 3X a day.  Capsules (root), #00, 2-3. Constant use of the dry root
  can induce mental agitation.
  STATUS : W/C`,

  // Vervain (Verbena officinalis)
  146: `VERBENA (Blue Vervain)
  FLOWERING HERB.  Standard Infusion, 2-5 ounces, to 3X a day. Tincture [1:5,
  60% alcohol] 30-90 drops, to 4X a day.
  STATUS : W/A`,

  // Agrimony (Agrimonia eupatoria)
  148: `AGRIMONIA (Agrimony)
  HERB.  Standard Infusion, 2-4 ounces.  Tincture [1:5, 50% alcohol, or Fresh
  Plant, 1:2], 1/4 to 1 teaspoon as needed.
  STATUS : W/A`,

  // Kola (Cola acuminata)
  150: `COLA NITIDA  (Kola Nut)
  SEED.  Strong Decoction, 2-6 ounces, to 4X a day.
  STATUS : W/C`,

  // Bistort (Polygonum bistorta)
  152: `POLYGONUM BISTORTA (Bistort Root)
  ROOT. Strong Decoction 1-4 ounces. Tincture [1:5, 50% alcohol, 10% glycerin]
  30-90 drops, both to 3X a day. The decoction and the diluted tincture as
  needed for topical use, mouthwash or gargle.
  STATUS : W/A`,

  // Oak (Quercus spp.)
  153: `QUERCUS  (Oak)
  Same as Geranium
  STATUS : W/A`,

  // Rhubarb (Rheum palmatum)
  154: `RHEUM  (Rhubarb, Chinese or Turkey Rhubarb)
  ROOT. Tincture [1:5, 50% alcohol, 10% glycerin] 15-30 drops, to 4X a day.
  Too much too frequently can induce rebound constipation.
  STATUS : W/C`,

  // Raspberry (Rubus idaeus)
  155: `RUBUS IDAEUS  (Raspberry)
  LEAVES.  Infusion as needed.
  STATUS : W/C`,

  // Blackberry (Rubus villosus)
  156: `RUBUS VILLOSUS  (Blackberry)
  ROOT BARK.  Strong Decoction, 2-4 ounces, to 4X a day.
  STATUS : W/C`,

  // Barberry (Berberis vulgaris)
  158: `BERBERIS VULGARIS  (Common Barberry)
  ROOT. Tincture [1:5, 50% alcohol] 10-60 drops. Cold Infusion, 1-3  ounces.
  Capsules, #00, 1-3.  All to 3X a day.  See MAHONIA (Oregon Grape) as well.
  STATUS : W/A`,

  // Centaury (Centaurium erythraea)
  159: `CENTAURIUM  (Erythraea,  Centaury)
  WHOLE PLANT.  Fresh Plant Tincture [1:2] 10-20 drops before meals.
  Cold Infusion 1-2 ounces, also before meals.
  STATUS : W/LA`,

  // Horehound (Marrubium vulgare)
  160: `MARRUBIUM  (Horehound)
  FLOWERING HERB. Cold Infusion, 2-4 ounces. Tincture [Fresh Plant, 1:2, Dry
  Plant, 1:5, 50% alcohol], 30-90 drops, both to 4X a day.
  STATUS : W/A`,

  // Tansy (Tanacetum vulgare)
  161: `*TANACETUM  (Tansy)
  FLOWERING HERB.  Standard Infusion 1-4 ounce.
  For short term use only; some of the chemical races can be moderately toxic.
  STATUS : W/C`,

  // Lily Of The Valley (Convallaria majalis)
  163: `*CONVALLARIA  (Lily of the Valley)
  ROOT. Tincture [Fresh Root,1:2, recent Dry Root,1:5,65% alcohol] 5-20 drops.
  USE WITH CARE.
  STATUS : W/LA`,

  // Scotch Broom (Cytisus scoparius)
  164: `*SCOPARIUS  (Cytisus scoparius, Broom Tops)
  FLOWERING BRANCHES.  Standard Infusion 1-2 ounces to 3X a day. Tincture [1:5,
  50% alcohol] 20-40 drops to 4X a day.
  USE WITH CARE, and NOT with prescription medications.
  STATUS : W/A`,

  // Ginkgo (Ginkgo biloba)
  165: `GINKGO BILOBA  (Maidenhair Tree)
  LEAVES.  Standard Infusion, 2-4 ounces. Tincture [1:5, 60% alcohol] 30-60
  drops to 3X a day.
  STATUS : W/C`,

  // Cinnamon (Cinnamomum spp.)
  167: `CINNAMOMUM  (Cinnamon, Canela)
  BARK. Standard Infusion 2-4 ounces. Tincture [1:5, 60% alcohol, 5% glycerin]
  20-50 drops, both to 4X a day.
  ESSENTIAL OIL. 2-5 drops in capsule.
  STATUS : W/LA/C`,

  // Celandine (Chelidonium majus)
  170: `CHELIDONIUM  (Greater Celandine)
  WHOLE PLANT.  Fresh Plant Tincture, [1:2] 10-25 drops. Alone, for short term
  use; safe for extended use as a low dose formula constituent.
  STATUS : W/A`,

  // Balmony (Chelone glabra)
  171: `CHELONE  (Balmony, Turtlehead)
  HERB. Tincture [fresh plant, 1:2], 10-20 drops to 3X a day.
  Cold Infusion, 1-3 ounces, to 3X a day.
  Dry Plant Tincture [1:5, 50% alcohol], 30-60 drops, to 4X a day.
  STATUS : W/LA`,

  // Artichoke (Cynara scolymus)
  172: `CYNARA  (Artichoke)
  HERB IN FLOWER. Standard Infusion, 2-4 ounces. Tincture [1:5, 50% alcohol]
  30-90 drops, either to 3X a day.
  STATUS : C`,

  // Wahoo (Euonymus atropurpureus)
  173: `*EUONYMUS (Wahoo, Burning Bush)
  BARK. Tincture [1:5, 60% alcohol] 10-30 drops. Cold Infusion, 1-2 ounces,
  both to 2X a day.
  Avoid prolonged use; Euonymus  can irritate the liver.
  STATUS : W/LA`,

  // Black Root (Leptandra virginica)
  175: `*LEPTANDRA  (Veronicastrum, Culver's Root)
  ROOT. Tincture [1:5, 65% alcohol], 10-30 drops,to 3X a day. An herb better
  used in formulas than by itself.
  USE WITH CARE.
  STATUS : W/Rare`,

  // Oat (Avena sativa)
  178: `AVENA  (A. sativa,  A. fatua, Oats, Wild Oats.)
  UNRIPE FRESH SEED, w/"Milky" center.  Fresh Tincture [1:2], 10-20 drops, to
  4X a day.
  STRAW (dry but green stems). Standard Infusion, 4-8 ounces.
  STATUS : W/C`,

  // Couch Grass (Elymus repens)
  179: `AGROPYRON REPENS (Triticum repens, Couchgrass)
  RHIZOME/STEMS. Cold Infusion, 2-4 fl. oz. Tincture [ 1:5, 50% alcohol] 30-60
  drops to 5X a day. Fluidextract [1:1, 50%  alcohol] 10-30 drops to 5X a day
  STATUS : W/A`,

  // Flax (Linum usitatissimum)
  180: `LINUM  (Flaxseed)
  SEEDS. Whole seeds, 1-2 teaspoons in cup of warm water, Ground seeds for a
  poultice. Only use freshly ground whole seeds internally; even several days
  is long enough to allow oxidative degradation, creating irritating lipids.
  STATUS : C`,

  // Buchu (Agathosma betulina)
  181: `BAROSMA (Agothasma, Buchu)
  LEAVES.  Cold Infusion (rewarmed) 1-3 ounces. Tincture  [1:5, 80% alcohol],
  30-60 drops in water. Both forms to 4X a day.
  STATUS : U`,

  // Stoneroot (Collinsonia canadensis)
  182: `COLLINSONIA  (Stone Root, Horse Balm)
  ROOT and HERB.  Tincture [Fresh Plant, 1:2] 20-40 drops to 3X a day.
  Tincture  [Dry Root, 1:5, 60% alcohol] 45-60 dropsto 4X a day (inferior).
  STATUS : W/LA`,

  // Pellitory of the Wall (Parietaria judaica)
  185: `PARIETARIA  (Pellitory-of-the-Wall)
  FLOWERING HERB.  Standard Infusion, 2-4 ounces. Tincture [1:5, 50% alcohol]
  60-90 drops, both to 5X a day.
  STATUS : W/A`,

  // Saw Palmetto (Serenoa repens)
  186: `SERENOA  (Saw Palmetto, Sabal)
  BERRIES.  Tincture [Fresh Berry, 1:2, Dry Berry, 1:5, 80% alcohol] 30-90
  drops.  Standard Infusion, 2-4 ounces, all forms to 3X a day.
  STATUS : W/LA`,

  // Partridgeberry (Mitchella repens)
  188: `MITCHELLA REPENS  (Squaw Vine)
  HERB. Tincture [Fresh Plant, 1:2, Dry Plant, 1:5, 50% alcohol],1/2 to 1
  teaspoon to 3X a day.  Standard Infusion, 2-8 ounces to 4X a day.
  STATUS : W/LA`,

  // Chasteberry (Vitex agnus-castus)
  190: `*VITEX AGNUS-CASTUS  (Chaste Tree Berries, Monk Peppers)
  SEEDS.  Tincture [1:5, 65% alcohol] 30-60 drops.  Ground Berries, 1/2 to 1
  tspn. in tea, both once in the morning. As it strengthens the progesterone
  phase of the estrus cycle, it usually works best the two weeks before menses
  STATUS : W/LA/C`,

  // Tolu Balsam (Myroxylon balsamum var. balsamum)
  194: `BALSAM OF TOLU. (Myroxylum toluiferum)
  RESIN. (Light Brown, syrupy, aromatic). TINCTURE:  One part resin in five of
  ethanol; take in 15-30 drop doses or add to some boiling water for steam
  inhalation.
  STATUS : U`,

  // Cowslip (Primula veris)
  197: `PRIMULA (Primrose, Cowslip)
  ROOT. Strong Decoction (more energetic but can gag in excess), Cold Infusion
  (less active but better for more frequent expectorant use), either format
  1-2 ounces to 5X a day.
  STATUS : W/LA`,

  // Violet (Viola odorata)
  198: `VIOLA ODORATA  (Violet)
  HERB. Standard Infusion 2-5 ounces to 3X a day. Tincture [Fresh Plant, 1:2]
  1-2 teaspoons to 2X a day.
  STATUS : W/C`,

  // Gumweed (Grindelia camporum)
  199: `GRINDELIA  (Gumweed, Yerba del Buey)
  FLOWERING TOPS. Tincture (Fresh Herb, [1:2], Dry Herb, [1:5, 70% alcohol]),
  15-40 drops to 5X a day.
  STATUS : W/A`,

  // Lungwort (Pulmonaria officinalis)
  200: `PULMONARIA  (Lungwort)
  FLOWERING HERB.  Standard Infusion as needed.
  STATUS : W/A`,

  // Thuja (Thuja occidentalis)
  201: `*THUJA  (Arbor Vitae, Flat, Red or Yellow Cedar)
  HERB. Fresh Plant Tincture [1:2] for topical use; 5-15 drops in water, to 4X
  a  day.  Cold Infusion, 2-3 ounces, to 3X a day.
  STATUS : W/A`,

  // Aloe (Aloe vera)
  202: `*ALOE  (Aloes Socrotine, etc.)
  DRIED JUICE. Capsules, a single #0 or #00. Tincture [ 1:10, 50% alcohol]
  15-60 drops.  Use with antispasmodic such as Acorus or Angelica.
  STATUS : W/C`,

  // Turmeric (Curcuma longa)
  203: `CURCUMA  (Turmeric)
  ROOT.  Tincture [1:5, 50% alcohol], 10-30 drops. 1 teaspoon of powder
  suspended in water.  Colors mouth a disturbing yellow.
  STATUS : C`,

  // Buckthorn (Rhamnus cathartica)
  204: `*RHAMNUS CATHARTICA  (Buckthorn)
  BERRIES.  Fresh Tincture [1:2], 3-20 drops.  DRY crushed berries, 1-2
  teaspoons steeped in a cup of water.  This Rhamnus has no advantages over
  the others, and is the least predictable in effect, ranging from ineffective
  to painful catharsis.
  STATUS : W/LA`,

  // Cascara Sagrada (Rhamnus purshiana)
  205: `RHAMNUS PURSHIANA (Cascara Sagrada)
  AGED BARK.  Same as Rhamnus californica
  STATUS : W/C`,

  // Milk Thistle (Silybum marianum)
  206: `SILYBUM MARIANUM  (Milk Thistle)
  SEEDS.  Capsules, #00, 2 at a time, to 3X a day.  Fluidextract [1:1, 60%
  alcohol],  20-40 drops to 5X a day. Strong Tincture [1:3, 70% alcohol], 1/2
  to 1 teaspoon, to 4X a day.
  STATUS : W/C`,

  // Wood Betony (Stachys officinalis)
  207: `STACHYS  (Hedge Nettle, Woundwort)
  FLOWERING HERB.  Tincture [Fresh Plant, 1:2, Dry Plant, 1:5, 50% alcohol],
  1/2 to 1 teaspoon, to 4X a day.  Standard Infusion, as needed, and topically
  as a poultice.
  STATUS : W/A`,

  // Mistletoe (Viscum album)
  211: `*VISCUM ALBUM (European Mistletoe)
  HERB. Tincture [1:5, 50% alcohol] 15-30 drops. Standard infusion, 2-3 ounces
  both to 3X a day.  Use in moderation.
  STATUS : U`,

  // Roman Chamomile (Chamaemelum nobile)
  213: `ANTHEMIS NOBILIS  (Roman Chamomile)
  FLOWERING HERB. Cold Infusion (bitter tonic),Standard Infusion (diaphoretic),
  both 2-4 ounces.
  STATUS : C`,

  // Senna (Senna alexandrina)
  216: `*SENNA (Cassia angustifolia, Egyptian Senna, etc. )
  LEAVES.  Strong Decoction, 2-4 ounces.
  PODS. 10-20, steeped for an hour in a cup of water. Take both in evening.
  See also Cassia marilandica.
  STATUS : W/C`,

  // Coffee (Coffea arabica)
  217: `CAFFEA ARABICA  (Coffee)
  ROASTED BEANS.  Black, freshly brewed or cold infusion, 4-12 ounces.
  STATUS : (gimme a break!!)`,

  // Guarana (Paullinia cupana)
  218: `PAULLINIA  (Guarana)
  SEED. Capsule, #00,  2-4. Fluidextract [1:1,50% alcohol,10% glycerin], 20-60
  drops. Tincture [1:5, 65% alcohol], 1/4 to 1 teaspoon.
  STATUS : W/C`,

  // Rhatany (Krameria triandra)
  220: `KRAMERIA  (Rhatany)
  WHOLE PLANT.  Tincture [Fresh Plant, 1:2, Dry Root, 1:5, 50% alcohol, 10%
  glycerin], 20-50 drops.  Strong Decoction, 1-3 ounces, or used topically.
  STATUS : W/A`,

  // Astragalus (Astragalus membranaceus)
  225: `ASTRAGALUS MEMBRANACEUS  (Huang-Chi)
  SLICED ROOT.  Cold Infusion, 2-3 ounces to 3X a day. Fluidextract [1:1, 55%
  alcohol] 10-15 drops to 3X a day.  Tincture [1:5, 60% alcohol]  30-60 drops,
  4X a day.
  STATUS : W/C`,

  // Privet (Ligustrum lucidum)
  274: `LIGUSTRUM  (Privet)
  BARK AND LEAVES.  Strong Decoction, as needed.
  STATUS : W/A`,

  // Pau D'arco (Tabebuia impetiginosa)
  291: `TABEBUIA  (Lapacho, Pau D'Arco, Ipe Roxo, Amapa)
  TREE BARK.  Cold Infusion, 2-4 ounce to 3X a day.  Fluidextract [1:1, 50%
  alc.]  15-30 drops to 5X a day.Tincture [1:5, 50% alcohol] 1/2 to 1 teaspoon
  to 4X a day
  STATUS : U`,

  // Yerba Mansa (Anemopsis californica)
  309: `ANEMOPSIS  (Yerba Mansa, Lizard Tail)
  ROOT.  Tincture [Fresh Root, 1:2, Dry Root, 1:5, 60% alcohol] 20-60 drops to
  5X  a day.  Cold Infusion, 2-4 ounces similarly.
  HERB.  Standard or Cold Infusion as needed.
  STATUS : W/LA`,

  // Sassafras (Sassafras albidum)
  313: `SASSAFRAS
  BARK OF ROOT.  Strong Decoction, as needed.
  LEAVES.  Standard Infusion,  as needed.
  ESSENTIAL OIL. Diluted with alcohol and applied to fresh Poison Ivy contact.
  STATUS : W/C`,

  // Peach (Prunus persica)
  320: `*AMYGDALIS PERSICA  (Peach Tree)
  FRESH TWIGS. Cold Infusion, 1-2 oz. Tincture [1:2], 30-90 drops, both ad lib.
  STATUS : C`,

  // Asian Mint (Mentha arvensis var. piperascens)
  410: `*MENTHA ARVENSIS  (Brook Mint, Poleo)
  HERB IN FLOWER.  Standard Infusion as needed. Although less than found in
  Hedeoma or Mentha pulegium, the pulegone content in this plant makes it
  inappropriate in pregnancy.
  STATUS : W/C`,

  // Dwarf Pine (Pinus pumilio)
  412: `PINUS  (Pine)
  NEEDLES.  Standard Infusion, 2-4 ounces, to 3X a day.
  PITCH. Pea-sized piece hewed and swallowed as expectorant.
  STATUS : W/A`,

  // Sandalwood (Santalum album)
  413: `SANTALUM (Santal, White Sandalwood)
  WOOD, OIL. Wood Tincture [1:5, 80% alcohol] 25-50 drops. The oil in capsule
  5-10 drops, with food, to 2X a day.
  STATUS : U`,

  // Khella (Ammi visnaga)
  450: `AMMI VISNAGA (Khella, Bishops's Weed)
  SEEDS.  Tincture [1:5, 60% alcohol], 60-120 drops to 4X a day.
  Not advisable for extended use.  Whole seed CVS uses are rather inferior to
  the refined  constituents, but quite adequate for smooth-muscle relaxation.
  STATUS : W/C`,

  // Scots Pine (Pinus sylvestris)
  469: `PINUS  (Pine)
  NEEDLES.  Standard Infusion, 2-4 ounces, to 3X a day.
  PITCH. Pea-sized piece hewed and swallowed as expectorant.
  STATUS : W/A`,

  // Cypress (Cupressus sempervirens)
  570: `CUPRESSUS (Cypress)
  GREEN FOLIAGE. EXTERNAL: Tincture [Fresh Herb, 1:2] straight, or diluted
  with two parts water.
  INTERNAL: Standard Infusion [lightly roasted twigs], 2-4 ounces.
  STATUS : W/A`,

  // California Spikenard (Aralia californica)
  579: `ARALIA RACEMOSA  [including A. californica]  (Spikenard, California Spikenard)
  ROOT.Tincture [Fresh Root,1:2, Recent Dry Root,1:5, 50% alcohol] 10-30 drops.
  Strong Decoction or Cold Infusion, 2-4 ounces.
  STATUS : W/LA`,

  // Western Coltsfoot (Petasites palmatus)
  586: `PETASITES  (Western Coltsfoot)
  HERB.  Standard Infusion, 2-4 ounces, to 4X a day.  Fresh Tincture [1:2],
  30-60 drops.
  ROOT. Strong Decoction, 2-3 ounces to 3X a day.
  STATUS : W/LA`,

  // Yerba Santa (Eriodictyon californicum)
  590: `ERIODICTYON  (Yerba Santa)
  LEAVES (from current year's growth). Tincture [Fresh Herb,1:2, Dry Herb,1:5,
  75% alcohol] 20-30 drops, to 5X a day.
  Standard Infusion, 2-4 ounces as needed.
  STATUS : W/LA`,

  // False Solomon's Seal (Smilacina racemosa)
  593: `SMILACINA RACEMOSA  (False Solomon's Seal)
  ROOT. Steep a teaspoon of ground root in cup of hot water. Mix with some hot
  water for a poultice.  The fresh root can be used as a poultice.
  STATUS : W/A`,

  // Kola Nut (Cola vera)
  615: `COLA NITIDA  (Kola Nut)
  SEED.  Strong Decoction, 2-6 ounces, to 4X a day.
  STATUS : W/C`,

  // Yellow Jasmine (Gelsemium sempervirens)
  645: `*GELSEMIUM  (Yellow Jasmine)
  ROOT.  Tincture [Fresh Root 1:2, Dry Root, 1:10, 65% alcohol] 2-10 drops.
  DANGEROUS IN LARGER DOSES
  STATUS : W/LA`,

  // Clary Sage (Salvia sclarea)
  743: `SALVIA  (Sage)
  FLOWERING HERB. Tincture [Fresh, 1:2, Dry, 1:5, 50% alcohol] 30-60 drops, in
  hot water (diaphoretic) or cold water (tonic).Cold Infusion or Strong
  Decoction 2-4 ounces.
  STATUS : W/C`,

  // Rose (Rosa spp.)
  849: `ROSA (Rose Buds, Rose Petals)
  FLOWERS. Standard Infusion, 2-4 ounces.  Make w/isotonic water for eyes.
  STATUS : W/C`,

  // Rose (Rosa spp.)
  850: `ROSA (Rose Buds, Rose Petals)
  FLOWERS. Standard Infusion, 2-4 ounces.  Make w/isotonic water for eyes.
  STATUS : W/C`,

  // Silk Tassel (Garrya fremontii)
  853: `*GARRYA (Silk Tassel, Cuauchichic, Quinine Bush)
  LEAF.  Tincture [Fresh leaf, 1:2, Dry Leaf, 1:5, 50% alcohol] 45-60 drops to
  5X a day.  Leaf, Cold Infusion, 2-3 ounces, to 4X a day.
  ROOT BARK [Tincture, 1:5, 50% alcohol] 10-20 drops to 5X a day,
  Use moderately, and NOT with other anti-cholinergics.
  STATUS : W/LA`,

  // Alfalfa (Medicago sativa)
  885: `MEDICAGO SATIVA  (Alfalfa)
  FLOWERING PLANT.  Standard Infusion as needed.
  STATUS : W/C`,

  // Lomatium (Lomatium dissectum)
  980: `LOMATIUM DISSECTUM  (Leptotaenia,  Biscuit Root)
  ROOT. Tincture [Fresh Root, 1:2, Dry Root, 1:5, 70% alcohol], 10-30 drops up
  to 4X a day.  Cold Infusion, 2-3 ounces also to 4X a day.
  STATUS : W/LA`,

  // Red Root (Ceanothus americanus)
  981: `CEANOTHUS  (Red Root, New Jersey Tea)
  ROOT.  Cold Infusion, 2-4 ounces. Tincture [Fresh Root, 1:2, Dry Root, 1:5,
  50% alcohol] 30-90 drops, to 4X a day.
  STATUS : W/A`,

  // Blue Vervain (Verbena hastata)
  983: `VERBENA (Blue Vervain)
  FLOWERING HERB.  Standard Infusion, 2-5 ounces, to 3X a day. Tincture [1:5,
  60% alcohol] 30-90 drops, to 4X a day.
  STATUS : W/A`,

  // Dong Quai (Angelica sinensis)
  1009: `*ANGELICA SINENSIS  (Dong Quai, Tang Kwei)
  CURED CHINESE OR KOREAN ROOT.  Large slices, 1/16 to 1/8 a day,chewed and
  swallowed.
  Tincture [1:5, 70%  alcohol] 5-20 drops
  Capsules, #0, 1 to 3 a day.
  STATUS : W/C`,

  // Lady's Mantle (Alchemilla vulgaris)
  1014: `ALCHEMILLA (Ladies Mantle)
  WHOLE PLANT. Standard Infusion, as needed
  STATUS : W/LA`,

  // Life Root (Senecio aureus)
  1058: `*SENECIO AUREUS  (Life Root, Squaw Weed)
   HERB. Standard Infusion, 1-4 ounces. Tincture [1:5, 50% alc.], 30-90 drops.
  STATUS : W/LA`,

  // Cinnamon Bark (Cinnamomum aromaticum)
  1083: `CINNAMOMUM  (Cinnamon, Canela)
  BARK. Standard Infusion 2-4 ounces. Tincture [1:5, 60% alcohol, 5% glycerin]
  20-50 drops, both to 4X a day.
  ESSENTIAL OIL. 2-5 drops in capsule.
  STATUS : W/LA/C`,

  // Goat's Rue (Galega officinalis)
  1122: `*GALEGA  (Goat's Rue)
  DRIED HERB.  Standard Infusion, 2-4 ounces.
  STATUS : W/A`,

  // Blessed Thistle (Cnicus benedictus)
  1124: `CNICUS BENEDICTUS  (Blessed or Holy Thistle)
  FLOWERING HERB. Cold Infusion, 4-6 ounces. Tincture [Fresh Herb, 1:2, Dry
  Herb, 1:5, 60% alcohol] 20-40 drops in hot water, both to 3X a day.
  STATUS : W/C`,

  // Evening Primrose (Oenothera biennis)
  1139: `OENOTHERA  (Evening Primrose)
  FLOWERING HERB. Standard Infusion, 2-4 ounces. The seeds contain high levels
  of GLA and tryptophane.
  STATUS : W/C`,

  // Bilberry (Vaccinium myrtillus)
  1160: `VACCINIUM  (Blueberry, Huckleberry, Bilberry, Whortleberry, etc.)
  LEAVES.  Standard Infusion of recent herb, 3-4 ounces, to 3X a day.
  STATUS : W/C`,

  // Cranberry (Vaccinium macrocarpon)
  1212: `VACCINIUM  (Blueberry, Huckleberry, Bilberry, Whortleberry, etc.)
  LEAVES.  Standard Infusion of recent herb, 3-4 ounces, to 3X a day.
  STATUS : W/C`,

  // Ocotillo (Fouquieria splendens)
  1248: `*FOUQUIERIA SPLENDENS (Ocotillo)
  FRESH BARK.  Tincture, [1:2] 10-30 drops, to 4X a day.
  STATUS : W/LA`,

  // Solomon's Seal (Polygonatum biflorum)
  1252: `POLYGONATUM (Solomon's Seal)
  ROOT.  Strong Decoction 1-4 ounces to 3X a day.
  STATUS : W/LA`,

  // Manzanita (Arctostaphylos manzanita)
  1253: `ARCTOSTAPHYLOS  (Uva Ursi, Manzanita, Bearberry)
  LEAVES.  Tincture [1:5, 50% alcohol] 30-60 drops in 8 oz. of water, to 3X a
  day. Standard Infusion 3-4 ounces to 3X a day.   For sitz bath, 8-12 ounces
  Standard Infusion in warm water; sit in it morning and evening.
  STATUS : W/LA`,

  // Cocklebur Fruit / Xanthium Fruit (Fructus Xanthii)
  1517: `XANTHIUM  (Cocklebur)
  PODS. 2-3 pods as infusion.
  HERB. Strong Infusion 2-3 ounces, to 2X a day.
  STATUS : W/A`,

  // Galangal Rhizome (Rhizoma Alpiniae Officinari)
  1546: `ALPINIA (Galangal)
  DRIED ROOT.  Tincture [1:5, 65% alcohol] 30-90 drops as needed.  1-2 #00
  capsules to 3X a day.
  STATUS : C`,

  // Safflower (Flos Carthami Tinctorii)
  1557: `CARTHAMUS TINCTORIA  (Safflower, American, Mexican or Bastard "Saffron")
  FLOWERS. Standard Infusion 4-8 ounces.
  STATUS : W/C`,

  // Moutan Bark / Tree Peony Root Bark (Cortex Radicis Moutan)
  1582: `*PAEONIA  (Peony)
  ROOT. Tincture [Fresh Root 1:2, Dry Root, 1:5, 60% alcohol] 10-25 drops up
  to  4X a day.  Cold Infusion, 1-2 ounces. Capsules, #00, 2-3 at a time.
  STATUS : W/C`,

  // Nutmeg (Semen Myristicae Fragrantis)
  1595: `MYRISTICA  (Nutmeg, Mace)
  SEED.  Tincture [1:5, 75% alcohol] 5-10 drops.
  STATUS : C`,

  // Chinese Wild Ginger (Herba Asari Cum Radice)
  1625: `ASARUM  (Wild Ginger, Canada Snakeroot)
  ROOT.  Tincture [Fresh Root 1:2, Dry Root, 1:5, 60% alcohol] 20-50 drops in
  hot  water.
  HERB. Standard Infusion or simple tea as needed.
  STATUS : W/LA`,

  // Teasel Root (Radix Dipsaci)
  1630: `DIPSACUS  (Teasel)
  HERB.  Standard Infusion, 2-4 ounces to 4X a day.
  STATUS : W/A`,

  // Dandelion (Taraxacum officinale)
  1648: `TARAXACUM  (Dandelion)
  ROOT or LEAF.  Root Fluidextract [1:1, 45% alcohol] 30-60 drops up to 4X a
  day.  Tincture [Fresh Root, 1:2] 1/2 to 1 teaspoon.  Strong Decoction, 2-4
  ounces, to 4X a day.  Leaf as Standard Infusion, 3-6 ounces as needed.
  STATUS : W/C`,

  // Nettle (Urtica dioica)
  1649: `URTICA  (Nettles)
  WHOLE HERB.  Cold or Standard infusion, as needed.
  STATUS : W/C`,

  // Comfrey (Symphytum officinale)
  1650: `SYMPHYTUM  (Comfrey)
  LEAF and ROOT. Leaf, Standard Infusion 2-6 ounces. Root, Cold Infusion, 1-4
  ounces, both to 3X a day,for short term use. Constant use of some cultivated
  strains can irritate or damage the liver.
  STATUS : C`,

  // Elder (Sambucus nigra)
  1651: `SAMBUCUS  (Elder)
  FLOWERS, LEAVES.   Flowers, Standard Infusion 2-4 ounces.  Leaves, Cold
  Infusion 1-2 ounces, both to 3X a day.
  STATUS : W/C`,

  // Hawthorn (Crataegus spp.)
  1652: `CRATAEGUS  (Hawthorn)
  BERRIES, FLOWERING BRANCHES. Tincture [Fresh Plant, 1:2, Dry Berries, 1:5,
  60% alcohol] 10-30 drops, to 3X a day.
  Cold Infusion (berries) 1-2 ounces, to 2X a day.
  STATUS : W/C`,

  // Pipsissewa (Chimaphila umbellata)
  2239: `CHIMAPHILA  (Pipsissewa, Prince's Pine)
  HERB. Tincture [Fresh Plant, 1:2, Dry plant, 1:5, 50% alcohol), 20-50 drops,
  to 4X a day.  Standard Infusion 4-8 ounces.
  STATUS : W/LA`,

  // Psyllium (Plantago ovata)
  2240: `PLANTAGO OVATA  (Psyllium Seed)
  SEED.  Whole seeds, 2-3 tablespoons in 12 ounces warm water or fruit juice.
  HUSKS. 1-2 tablespoons in same, both to 3X a day, usually only once.
  STATUS : C`,

  // White Pond Lily (Nymphaea odorata)
  2242: `NYMPHAEA ODORATA  (White Pond Lily)
  DRIED RHIZOME. Strong Decoction, 1-2 ounces to 4X a day (internally) or an
  appropriate volume as a douche.
  STATUS : W/LA`,

  // Yucca (Yucca spp.)
  2244: `YUCCA (Amole, Spanish Bayonet)
  ROOT.  Capsules, #00, 2-3 , morning and evenings.
  STATUS : W/A`,

  // Chinese Skullcap (Scutellaria baicalensis)
  2274: `SCUTELLARIA  (Skullcap)
  HERB. Tincture  [Fresh Plant, 1:2, Recent Dry Plant, 1:5, 50% alcohol] 20-60
  drops.  Standard Infusion of recent herb, 2-6 ounces, all to 3X a day.
  STATUS : W/C`,

  // Oat (Avena sativa)
  2287: `AVENA  (A. sativa,  A. fatua, Oats, Wild Oats.)
  UNRIPE FRESH SEED, w/"Milky" center.  Fresh Tincture [1:2], 10-20 drops, to
  4X a day.
  STRAW (dry but green stems). Standard Infusion, 4-8 ounces.
  STATUS : W/C`,

  // Oat (Avena sativa)
  2288: `AVENA  (A. sativa,  A. fatua, Oats, Wild Oats.)
  UNRIPE FRESH SEED, w/"Milky" center.  Fresh Tincture [1:2], 10-20 drops, to
  4X a day.
  STRAW (dry but green stems). Standard Infusion, 4-8 ounces.
  STATUS : W/C`,

  // Peyote (Lophophora williamsii)
  2350: `*LOPHOPHORA  (Peyote, Mescal Buttons)
  FRESH PLANT. Tincture [1:2], 20-40 drops to 4X a day.
  ILLEGAL TO POSSESS AT PRESENT.
  STATUS : W/Rare`,

  // Self Heal (Prunella vulgaris)
  2437: `PRUNELLA  (Self Heal, Heal All)
  FRESH PLANT.  Poultice as needed.  Fresh Plant Tincture, [1:2], as needed.
  STATUS : W/A`,

  // Black Pepper (Piper nigrum)
  2498: `PIPER NIGRUM  (Black Pepper)
  PEPPERCORNS.  Tincture [1:5, 65% alcohol] 5-15 drops.
  STATUS : C`,

};
