#!/usr/bin/env python3
"""
Generate search_keywords (synonyms) for all flower_essence_categories rows.

Requires:
  pip install anthropic psycopg2-binary

Usage:
  python3 scripts/generate_fes_synonyms.py

Outputs:
  supabase/migrations/195_flower_essence_synonyms.sql
"""

import anthropic
import psycopg2
import json
import re
import textwrap
import time

DB_DSN = "host=127.0.0.1 port=54322 user=postgres password=postgres dbname=postgres"
OUTPUT = "supabase/migrations/195_flower_essence_synonyms.sql"
BATCH_SIZE = 12  # categories per Claude call

SYSTEM_PROMPT = textwrap.dedent("""\
    You are an expert in flower essence therapy (Bach Flower Remedies and Flower Essence Services).
    For each soul condition category from the Flower Essence Repertory, generate 25–30 search keywords
    and synonyms a user might type when looking for that condition. Include:
    - Common synonyms and near-synonyms
    - Related emotional / psychological states
    - Layperson phrasing (not just clinical terms)
    - Verbs and adjectives as well as nouns (e.g., "feeling guilty", "self-blame")
    - Colloquial expressions (e.g., "beating yourself up")

    Return ONLY a JSON object mapping each input category name to an array of strings.
    No explanations, no markdown fences, just the raw JSON object.
""")

def fetch_categories(conn):
    with conn.cursor() as cur:
        cur.execute("SELECT category FROM herbal.flower_essence_categories ORDER BY category")
        return [row[0] for row in cur.fetchall()]

def generate_synonyms_for_batch(client, batch):
    prompt = (
        "Generate 25–30 search keywords/synonyms for each of these soul condition categories:\n\n"
        + json.dumps(batch, ensure_ascii=False)
    )
    message = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=4096,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": prompt}],
    )
    raw = message.content[0].text.strip()
    # Strip any accidental markdown fences
    raw = re.sub(r'^```json\s*', '', raw)
    raw = re.sub(r'```\s*$', '', raw)
    return json.loads(raw)

def pg_array_literal(words):
    escaped = [w.replace("'", "''") for w in words]
    return "ARRAY[" + ", ".join(f"'{w}'" for w in escaped) + "]"

def main():
    conn = psycopg2.connect(DB_DSN)
    categories = fetch_categories(conn)
    conn.close()
    print(f"Found {len(categories)} categories.")

    client = anthropic.Anthropic()
    results = {}

    for i in range(0, len(categories), BATCH_SIZE):
        batch = categories[i:i + BATCH_SIZE]
        print(f"  Batch {i // BATCH_SIZE + 1}: {batch[0]} … {batch[-1]}")
        try:
            synonyms = generate_synonyms_for_batch(client, batch)
            results.update(synonyms)
        except Exception as e:
            print(f"  ERROR on batch: {e}")
            for cat in batch:
                results[cat] = []
        time.sleep(1)  # avoid rate limits

    lines = [
        "-- Migration 195: search_keywords for flower_essence_categories",
        "-- Generated by scripts/generate_fes_synonyms.py",
        "SET search_path TO herbal, public;",
        "",
    ]
    for cat in categories:
        words = results.get(cat, [])
        if not words:
            continue
        arr = pg_array_literal(words)
        safe_cat = cat.replace("'", "''")
        lines.append(
            f"UPDATE herbal.flower_essence_categories "
            f"SET search_keywords = {arr} "
            f"WHERE category = '{safe_cat}';"
        )

    output_path = OUTPUT
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\nWrote {output_path} ({len(lines)} lines).")
    print("Run migration 194 in Supabase SQL Editor first, then run 195.")

if __name__ == "__main__":
    main()
