-- Set schema
SET search_path TO herbal, public;

-- Insert herbs into herbal schema
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (1, 'Acanthopanax sessiliflorum', 'wu jia pi') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (2, 'Albizzia julibrissin', 'silk tree') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (3, 'Aralia elata', 'Japanese angelica tree') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (4, 'A. manshurica', 'Manchurian aralia') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (5, 'Aralia schmidtii', 'Sakhalin spikenard') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (6, 'Cicer arietinum', 'chickpea') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (7, 'Codonoposis pilosula', 'dang shen') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (8, 'Echinopanax elatus', 'Asian devil’s club') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (9, 'Eleutherococcus senticosus', 'Siberian ginseng') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (10, 'Eucommia ulmoides', 'hardy rubber tree') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (11, 'Ganoderma lucidum', 'reishi mushroom') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (12, 'Hoppea dichotoma Leuzea carthamoides', 'maral root') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (13, 'Ocimum sanctum', 'holy basil') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (14, 'Panax ginseng', 'Korean ginseng') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (15, 'Panax quinquefolius', 'American ginseng') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (16, 'Rhodiola rosea', 'roseroot stonecrop') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (17, 'Schisandra chinensis', 'schizandra') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (18, 'Tinospora cordifolia', 'guduchi') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (19, 'Trichopus zeylanicus', 'arogyappacha') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (20, 'Withania somnifera', 'ashwaganda') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (21, 'Allium sativum', 'garlic') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (22, 'Arctium lappa', 'burdock') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (23, 'Baptisia tinctoria', 'wild indigo') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (24, 'Chionanthus virginicus', 'fringetree') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (25, 'Cimicifuga racemosa', 'black cohosh') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (26, 'Echinacea spp.', 'echinacea') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (27, 'Fumaria officinalis', 'fumitory') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (28, 'Galium aparine', 'cleavers') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (29, 'Guaiacum officinale', 'guaiacum') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (30, 'Hydrastis canadensis', 'goldenseal') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (31, 'Iris versicolor', 'blue flag') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (32, 'Larrea tridentata', 'chaparral') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (33, 'Mahonia aquifolium', 'Oregon grape') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (34, 'Menyanthes trifoliata', 'bogbean') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (35, 'Phytolacca americana', 'poke') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (36, 'Pulsatilla vulgaris', 'pasqueflower') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (37, 'Rumex crispus', 'yellow dock') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (38, 'Sanguinaria canadensis', 'bloodroot') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (39, 'Scrophularia nodosa', 'figwort') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (40, 'Smilax spp.', 'sarsaparilla') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (41, 'Stillingia sylvatica', 'queen’s delight') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (42, 'Trifolium pratense', 'red clover') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (43, 'Urtica dioica', 'nettles') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (44, 'Achillea millefolium', 'yarrow') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (45, 'Althaea officinalis', 'marshmallow') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (46, 'Arctostaphylos uva-ursi', 'bearberry') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (47, 'Capsicum annuum', 'cayenne') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (48, 'Cetraria islandica', 'Iceland moss') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (49, 'Chondrus crispus', 'Irish moss') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (50, 'Eupatorium perfoliatum', 'boneset') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (51, 'Euphrasia spp.', 'eyebright') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (52, 'Geranium maculatum', 'cranesbill') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (53, 'Hyssopus officinalis', 'hyssop') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (54, 'Inula helenium', 'elecampane') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (55, 'Mentha piperita', 'peppermint') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (56, 'Salvia officinalis', 'sage') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (57, 'Sambucus nigra', 'elder') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (58, 'Solidago virgaurea', 'goldenrod') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (59, 'Thymus vulgaris', 'thyme') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (60, 'Tussilago farfara', 'coltsfoot') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (61, 'Verbascum thapsus', 'mullein') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (62, 'Aesculus hippocastanum', 'horse chestnut') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (63, 'Alchemilla arvensis', 'lady’s mantle') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (64, 'Anethum graveolens', 'dill') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (65, 'Angelica archangelica', 'angelica') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (66, 'Apium graveolens', 'celery seed') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (67, 'Asclepias tuberosa', 'pleurisy root') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (68, 'Betula spp.', 'birch') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (69, 'Borago officinalis', 'borage') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (70, 'Calendula officinalis', 'calendula') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (71, 'Capsella bursa-pastoris', 'shepherd’s purse') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (72, 'Caulophyllum thalictroides', 'blue cohosh') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (73, 'Crataegus spp.', 'hawthorn') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (74, 'Dioscorea villosa', 'wild yam') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (75, 'Filipendula ulmaria', 'meadowsweet') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (76, 'Foeniculum vulgare', 'fennel') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (77, 'Gaultheria procumbens', 'wintergreen') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (78, 'Glycyrrhiza glabra', 'licorice') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (79, 'Hamamelis virginiana', 'witch hazel') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (80, 'Harpagophytum procumbens', 'devil’s claw') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (81, 'Hypericum perforatum', 'St. John’s wort') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (82, 'Lavandula spp.', 'lavender') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (83, 'Malva sylvestris', 'mallow') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (84, 'Matricaria recutita', 'chamomile') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (85, 'Plantago major', 'plantain') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (86, 'Populus tremuloides', 'aspen') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (87, 'Salix spp.', 'willow') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (88, 'Stellaria media', 'chickweed') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (89, 'Symphytum officinale', 'comfrey') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (90, 'Tilia platyphyllos', 'linden') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (91, 'Trigonella foenum-graecum', 'fenugreek') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (92, 'Ulmus rubra', 'slippery elm') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (93, 'Viburnum opulus', 'cramp bark') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (94, 'Viburnum prunifolium', 'black haw') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (95, 'Zea mays', 'corn silk') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (96, 'Artemisia abrotanum', 'southernwood') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (97, 'A. absinthium', 'wormwood') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (98, 'Carum carvi', 'caraway') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (99, 'Commiphora molmol', 'myrrh') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (100, 'Coriandrum sativum', 'coriander') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (101, 'Eucalyptus spp.', 'eucalyptus') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (102, 'Gentiana lutea', 'gentian') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (103, 'Juniperus communis', 'juniper') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (104, 'Ligusticum porteri', 'osha') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (105, 'Myroxylon balsamum var. pereirae', 'balsam of Peru') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (106, 'Olea europaea', 'olive') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (107, 'Origanum majorana', 'marjoram') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (108, 'Pimpinella anisum', 'aniseed') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (109, 'Rosmarinus officinalis', 'rosemary') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (110, 'Ruta graveolens', 'rue') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (111, 'Syzygium aromaticum', 'clove') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (112, 'Usnea spp.', 'usnea') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (113, 'Armoracia rusticana', 'horseradish') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (114, 'Arnica montana', 'arnica') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (115, 'Artemisia absinthium', 'wormwood') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (116, 'Artemisia vulgaris', 'mugwort') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (117, 'Brassica spp.', 'mustard') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (118, 'E. purpureum', 'gravel root') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (119, 'Fucus vesiculosus', 'kelp') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (120, 'Myrica cerifera', 'bayberry') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (121, 'Petroselinum crispum', 'parsley') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (122, 'Tanacetum parthenium', 'feverfew') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (123, 'Taraxacum officinale', 'dandelion') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (124, 'Zanthoxylum americanum', 'prickly ash') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (125, 'Zingiber officinale', 'ginger') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (126, 'Daucus carota', 'wild carrot') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (127, 'Drosera rotundifolia', 'sundew') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (128, 'Elettaria cardamomum', 'cardamom') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (129, 'Eschscholzia californica', 'California poppy') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (130, 'Humulus lupulus', 'hops') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (131, 'Lactuca virosa', 'wild lettuce') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (132, 'Leonurus cardiaca', 'motherwort') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (133, 'Lobelia inflata', 'lobelia') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (134, 'Lycopus spp.', 'bugleweed') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (135, 'Melissa officinalis', 'lemon balm') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (136, 'M. pulegium', 'pennyroyal') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (137, 'Nepeta cataria', 'catnip') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (138, 'Passiflora incarnata', 'passionflower') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (139, 'Piper methysticum', 'kava kava') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (140, 'Piscidia erythrina', 'Jamaica dogwood') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (141, 'Prunus serotina', 'wild cherry bark') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (142, 'Salvia officinalis var. rubia', 'red sage') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (143, 'Scutellaria lateriflora', 'skullcap') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (144, 'Symplocarpus foetidus', 'skunk cabbage') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (145, 'Turnera diffusa', 'damiana') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (146, 'Valeriana officinalis', 'valerian') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (147, 'Verbena officinalis', 'vervain') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (148, 'V . prunifolium', 'black haw') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (149, 'Acacia catechu', 'black catechu') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (150, 'Agrimonia eupatoria', 'agrimony') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (151, 'Camellia sinensis', 'tea') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (152, 'Cola acuminata', 'kola') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (153, 'Equisetum arvense', 'horsetail') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (154, 'Polygonum bistorta', 'bistort') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (155, 'Quercus spp.', 'oak') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (156, 'Rheum palmatum', 'rhubarb') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (157, 'Rubus idaeus', 'raspberry') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (158, 'R. villosus', 'blackberry') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (159, 'Vinca major', 'periwinkle') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (160, 'A. vulgaris', 'mugwort') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (161, 'Berberis vulgaris', 'barberry') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (162, 'Centaurium erythraea', 'centaury') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (163, 'Marrubium vulgare', 'horehound') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (164, 'Tanacetum vulgare', 'tansy') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (165, 'Coleus forskohlii', 'coleus') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (166, 'Convallaria majalis', 'lily of the valley') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (167, 'Cytisus scoparius', 'Scotch broom') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (168, 'Ginkgo biloba', 'ginkgo') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (169, 'Urginea maritima', 'squill') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (170, 'Cinnamomum spp.', 'cinnamon') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (171, 'Eucalyptus globulus', 'eucalyptus') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (172, 'Thymus spp.', 'thyme') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (173, 'Chelidonium majus', 'celandine') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (174, 'Chelone glabra', 'balmony') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (175, 'Cynara scolymus', 'artichoke') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (176, 'Euonymus atropurpureus', 'wahoo') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (177, 'Juglans cinerea', 'butternut') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (178, 'Leptandra virginica', 'black root') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (179, 'Peumus boldus', 'boldo') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (180, 'Taraxacum officinale root', 'dandelion') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (181, 'Avena sativa', 'oat') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (182, 'Elymus repens', 'couch grass') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (183, 'Linum usitatissimum', 'flax') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (184, 'Agathosma betulina', 'buchu') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (185, 'Collinsonia canadensis', 'stoneroot') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (186, 'Cucurbita pepo', 'pumpkin') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (187, 'Eryngium maritimum', 'sea holly') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (188, 'E.purpureum', 'gravel root') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (189, 'Parietaria judaica', 'pellitory of the wall') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (190, 'Serenoa repens', 'saw palmetto') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (191, 'Marsdenia condurango', 'condurango') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (192, 'Mitchella repens', 'partridgeberry') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (193, 'T. vulgare', 'tansy') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (194, 'Tropaeolum majus', 'nasturtium') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (195, 'Vitex agnus-castus', 'chasteberry') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (196, 'Bellis perennis', 'English daisy') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (197, 'Cephaelis ipecacuanha', 'ipecac') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (198, 'Hieracium pilosella', 'mouse ear') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (199, 'Myroxylon balsamum var. balsamum', 'Tolu balsam') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (200, 'Polygala senega', 'Seneca snakeroot') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (201, 'Populus candicans', 'balm of Gilead') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (202, 'Primula veris', 'cowslip') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (203, 'Viola odorata', 'sweet violet') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (204, 'Grindelia camporum', 'gumweed') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (205, 'Pulmonaria officinalis', 'lungwort') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (206, 'Thuja occidentalis', 'thuja') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (207, 'Aloe vera', 'aloe') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (208, 'Curcuma longa', 'turmeric') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (209, 'Rhamnus cathartica', 'buckthorn') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (210, 'R. purshiana', 'cascara sagrada') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (211, 'Silybum marianum', 'milk thistle') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (212, 'Stachys officinalis', 'wood betony') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (213, 'Allium cepa', 'onion') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (214, 'A.sativum', 'garlic') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (215, 'Fagopyrum esculentum', 'buckwheat') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (216, 'Viscum album', 'mistletoe') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (217, 'Panax spp.', 'ginseng') ON CONFLICT (latin_name) DO NOTHING;
INSERT INTO herbal.herbs (id, latin_name, common_name) VALUES (218, 'Senna alexandrina', 'senna') ON CONFLICT (latin_name) DO NOTHING;

-- Insert primary actions
INSERT INTO herbal.primary_actions (id, name) VALUES (1, 'Adaptogens') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (2, 'Alteratives') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (3, 'Anticatarrhal') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (4, 'Anti-inflammatory') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (5, 'Antimicrobial') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (6, 'Antirheumatic') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (7, 'Antispasmodic') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (8, 'Astringent') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (9, 'Bitter') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (10, 'Cardiac Remedies') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (11, 'Carminative') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (12, 'Cholagogue') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (13, 'Demulcent') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (14, 'Diuretic') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (15, 'Emmenagogue') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (16, 'Expectorant') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (17, 'Hepatic') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (18, 'Hypnotic') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (19, 'Hypotensive') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (20, 'Nervine') ON CONFLICT (name) DO NOTHING;
INSERT INTO herbal.primary_actions (id, name) VALUES (21, 'Stimulant') ON CONFLICT (name) DO NOTHING;

-- Body systems are already inserted in the schema migration
-- If you need to re-insert them:
-- DELETE FROM herbal.body_systems;
-- INSERT INTO herbal.body_systems (id, name) VALUES (1, 'Cardiovascular');
-- INSERT INTO herbal.body_systems (id, name) VALUES (2, 'Respiratory');
-- INSERT INTO herbal.body_systems (id, name) VALUES (3, 'Digestive');
-- INSERT INTO herbal.body_systems (id, name) VALUES (4, 'Urinary');
-- INSERT INTO herbal.body_systems (id, name) VALUES (5, 'Reproductive');
-- INSERT INTO herbal.body_systems (id, name) VALUES (6, 'Musculoskeletal');
-- INSERT INTO herbal.body_systems (id, name) VALUES (7, 'Nervous');
-- INSERT INTO herbal.body_systems (id, name) VALUES (8, 'Skin');
