SET search_path TO herbal, public;

-- Insert all 143 TCM herbs from Dui Yao source data.
-- TCM latin names use the descriptive form (e.g. "Radix X") rather than binomial
-- nomenclature, so they are distinct from any existing Western herb records.
-- ON CONFLICT updates pinyin_name and is_tcm so this is safe to re-run.

INSERT INTO herbal.herbs (latin_name, common_name, pinyin_name, is_tcm)
VALUES
  ('Bulbus Lilii', 'Lily Bulb', 'Bai He', TRUE),
  ('Rhizoma Bletillae Striatae', 'Bletilla Rhizome', 'Bai Ji', TRUE),
  ('Fructus Tribuli Terrestris', 'Caltrop Fruit / Puncturevine', 'Bai Ji Li', TRUE),
  ('Radix Cynanchi Stautonii', 'Swallowwort Root', 'Bai Qian', TRUE),
  ('Radix Albus Paeoniae Lactiflorae', 'White Peony Root', 'Bai Shao', TRUE),
  ('Rhizoma Atractylodis Macrocephalae', 'White Atractylodes Rhizome', 'Bai Zhu', TRUE),
  ('Semen Biotae Orientalis', 'Biota Seed / Arborvitae Seed', 'Bai Zi Ren', TRUE),
  ('Radix Isatidis Seu Baphicacanthi', 'Isatis Root / Woad Root', 'Ban Lan Gen', TRUE),
  ('Rhizoma Pinelliae Ternatae', 'Pinellia Rhizome', 'Ban Xia', TRUE),
  ('Carapax Amydae Sinensis', 'Turtle Shell (Soft-Shelled)', 'Bie Jia', TRUE),
  ('Semen Arecae Catechu', 'Betel Nut / Areca Seed', 'Bing Lang', TRUE),
  ('Fructus Psoraleae Corylifoliae', 'Psoralea Fruit / Babchi', 'Bu Gu Zhi', TRUE),
  ('Fructus Xanthii', 'Cocklebur Fruit / Xanthium Fruit', 'Cang Er Zi', TRUE),
  ('Rhizoma Atractylodis', 'Black Atractylodes Rhizome', 'Cang Zhu', TRUE),
  ('Radix Bupleuri', 'Bupleurum Root', 'Chai Hu', TRUE),
  ('Periostracum Cicadae', 'Cicada Slough / Cicada Molting', 'Chan Tui', TRUE),
  ('Pericarpium Citri Reticulatae', 'Tangerine Peel', 'Chen Pi', TRUE),
  ('Radix Rubrus Paeoniae Lactiflorae', 'Red Peony Root', 'Chi Shao', TRUE),
  ('Bulbus Fritillariae Cirrhosae', 'Sichuan Fritillaria Bulb', 'Chuan Bei Mu', TRUE),
  ('Fructus Meliae Toosendan', 'Sichuan Pagoda Tree Fruit / Melia Toosendan', 'Chuan Lian Zi', TRUE),
  ('Radix Ligustici Wallicii', 'Szechuan Lovage Root / Ligusticum', 'Chuan Xiong', TRUE),
  ('Magnetitum', 'Magnetite / Lodestone', 'Ci Shi', TRUE),
  ('Radix Et Rhizoma Rhei', 'Rhubarb Root', 'Da Huang', TRUE),
  ('Fructus Zizyphi Jujubae', 'Jujube / Chinese Red Date', 'Da Zao', TRUE),
  ('Semen Praeparatum Sojae', 'Prepared Soybean / Fermented Black Soybean', 'Dan Dou Chi', TRUE),
  ('Pulvis Arisaematis Cum Felle Bovis', 'Bile-Processed Arisaema / Bile Arisaema Powder', 'Dan Nan Xing', TRUE),
  ('Radix Salviae Miltiorrhizae', 'Red Sage Root / Salvia Root', 'Dan Shen', TRUE),
  ('Radix Angelicae Sinensis', 'Chinese Angelica Root / Dong Quai', 'Dang Gui', TRUE),
  ('Radix Codonopsitis Pilosulae', 'Codonopsis Root', 'Dang Shen', TRUE),
  ('Cortex Radicis Lycii Chinensis', 'Lycium Root Bark / Wolfberry Root Bark', 'Di Gu Pi', TRUE),
  ('Flos Caryophylli', 'Clove Flower Bud', 'Ding Xiang', TRUE),
  ('Radix Angelicae Pubescentis', 'Pubescent Angelica Root', 'Du Huo', TRUE),
  ('Cortex Eucommiae Ulmoidis', 'Eucommia Bark', 'Du Zhong', TRUE),
  ('Gelatinum Corii Asini', 'Donkey Hide Gelatin / Ass-Hide Glue', 'E Jiao', TRUE),
  ('Rhizoma Curcumae Zedoariae', 'Zedoary Rhizome / Curcuma Zedoary', 'E Zhu', TRUE),
  ('Radix Ledebouriellae Divaricatae', 'Saposhnikovia Root / Ledebouriella Root', 'Fang Feng', TRUE),
  ('Sclerotium Poriae Cocos', 'Poria / Hoelen', 'Fu Ling', TRUE),
  ('Fructus Levis Tritici Aestivi', 'Light Wheat Grain', 'Fu Xiao Mai', TRUE),
  ('Radix Lateralis Praeparatus Aconiti Carmichaeli', 'Prepared Aconite Root / Prepared Aconite', 'Fu Zi', TRUE),
  ('Radix Glycyrrhizae', 'Licorice Root', 'Gan Cao', TRUE),
  ('Dry Rhizoma Zingiberis', 'Dried Ginger', 'Gan Jiang', TRUE),
  ('Rhizoma Alpiniae Officinari', 'Galangal Rhizome', 'Gao Liang Jiang', TRUE),
  ('Radix Puerariae', 'Kudzu Root', 'Ge Gen', TRUE),
  ('Fructus Lycii Chinensis', 'Wolfberry Fruit', 'Gou Qi Zi', TRUE),
  ('Fructus Trichosanthis Kirlowii', 'Trichosanthes Fruit', 'Gua Lou', TRUE),
  ('Plastrum Testudinis', 'Tortoise Plastron', 'Gui Ban', TRUE),
  ('Ramulus Cinnamomi Cassiae', 'Cinnamon Twig', 'Gui Zhi', TRUE),
  ('Spora Lygodii', 'Lygodium Spores', 'Hai Jin Sha', TRUE),
  ('Cortex Erythrinae', 'Erythrina Bark', 'Hai Tong Pi', TRUE),
  ('Radix Stephaniae Tetrandrae', 'Stephania Root', 'Han Fang Ji', TRUE),
  ('Herba Ecliptae Prostratae', 'Eclipta', 'Han Lian Cao', TRUE),
  ('Fructus Terminaliae Chebulae', 'Terminalia Fruit / Chebulic Myrobalan', 'He Zi', TRUE),
  ('Flos Carthami Tinctorii', 'Safflower', 'Hong Hua', TRUE),
  ('Semen Juglandis Regiae', 'Walnut Kernel', 'Hu Tao Ren', TRUE),
  ('Talcum', 'Talc', 'Hua Shi', TRUE),
  ('Cortex Phellodendri', 'Phellodendron Bark / Cork Tree Bark', 'Huang Bai', TRUE),
  ('Rhizoma Coptidis Chinensis', 'Coptis Rhizome', 'Huang Lian', TRUE),
  ('Radix Astragali Membranacei', 'Astragalus Root / Milk Vetch Root', 'Huang Qi', TRUE),
  ('Radix Scutellariae Baicalensis', 'Scutellaria / Skullcap Root', 'Huang Qin', TRUE),
  ('Herba Agastachis Seu Pogostemi', 'Agastache / Patchouli', 'Huo Xiang', TRUE),
  ('Endothelium Corneum Gigeriae Galli', 'Chicken Gizzard Lining', 'Ji Nei Jin', TRUE),
  ('Radix Platycodi Grandiflori', 'Platycodon Root', 'Jie Geng', TRUE),
  ('Herba Desmodii Seu Lysimachiae', 'Gold Coin Grass', 'Jin Qian Cao', TRUE),
  ('Flos Lonicerae Japonicae', 'Honeysuckle Flower', 'Jin Yin Hua', TRUE),
  ('Fructus Rosae Laevigatae', 'Cherokee Rose Fruit', 'Jin Ying Zi', TRUE),
  ('Semen Citri Reticulatae', 'Tangerine Seed', 'Ju He', TRUE),
  ('Epicarpium Rubrum Citri Reticulatae', 'Red Tangerine Peel', 'Ju Hong', TRUE),
  ('Flos Chrysanthemi Morifolii', 'Chrysanthemum Flower', 'Ju Hua', TRUE),
  ('Fructus Litchi Chinensis', 'Lychee Seed', 'Li Zhi He', TRUE),
  ('Fructus Forsythiae Suspensae', 'Forsythia Fruit', 'Lian Qiao', TRUE),
  ('Semen Nelumbinis Nuciferae', 'Lotus Seed', 'Lian Zi', TRUE),
  ('Os Draconis', 'Dragon Bone', 'Long Gu', TRUE),
  ('Herba Ephedrae', 'Ephedra', 'Ma Huang', TRUE),
  ('Radix Ephedrae', 'Ephedra Root', 'Ma Huang Gen', TRUE),
  ('Tuber Ophiopogonis Japonici', 'Ophiopogon Tuber', 'Mai Men Dong', TRUE),
  ('Mirabilium', 'Mirabilitum / Glauber''s Salt', 'Mang Xiao', TRUE),
  ('Resina Myrrhae', 'Myrrh', 'Mo Yao', TRUE),
  ('Cortex Radicis Moutan', 'Moutan Bark / Tree Peony Root Bark', 'Mu Dan Pi', TRUE),
  ('Concha Ostreae', 'Oyster Shell', 'Mu Li', TRUE),
  ('Radix Auklandiae Lappae', 'Costus Root / Saussurea Root', 'Mu Xiang', TRUE),
  ('Semen Cucurbitae Moschatae', 'Pumpkin Seed', 'Nan Gua Zi', TRUE),
  ('Fructus Ligustri Lucidi', 'Ligustrum Fruit', 'Nu Zhen Zi', TRUE),
  ('Herba Eupatorii Fortunei', 'Eupatorium', 'Pei Lan', TRUE),
  ('Herba Taraxaci Mongolici Cum Radice', 'Dandelion', 'Pu Gong Ying', TRUE),
  ('Pollen Typhae', 'Cattail Pollen', 'Pu Huang', TRUE),
  ('Radix Peucedani', 'Peucedanum Root', 'Qian Hu', TRUE),
  ('Semen Euryalis Ferocis', 'Euryale Seed', 'Qian Shi', TRUE),
  ('Radix Et Rhizoma Notopterygii', 'Notopterygium Root', 'Qiang Huo', TRUE),
  ('Radix Gentianae Macrophyllae', 'Large Leaf Gentian Root', 'Qin Jiao', TRUE),
  ('Pericarpium Citri Reticulatae Viride', 'Green Tangerine Peel (Unripe)', 'Qing Pi', TRUE),
  ('Semen Myristicae Fragrantis', 'Nutmeg', 'Rou Dou Kou', TRUE),
  ('Cortex Cinnamomi Cassiae', 'Cinnamon Bark', 'Rou Gui', TRUE),
  ('Resina Olibani', 'Frankincense', 'Ru Xiang', TRUE),
  ('Rhizoma Sparganii', 'Bur-Reed Rhizome / Sparganium', 'San Leng', TRUE),
  ('Radix Pseudoginseng', 'Pseudoginseng Root / Notoginseng', 'San Qi', TRUE),
  ('Cortex Radicis Mori Albi', 'Mulberry Root Bark', 'Sang Bai Pi', TRUE),
  ('Ramulus Loranthi Seu Visci', 'Mulberry Mistletoe Stem', 'Sang Ji Sheng', TRUE),
  ('Folium Mori Albi', 'Mulberry Leaf', 'Sang Ye', TRUE),
  ('Ramulus Mori Albi', 'Mulberry Twig', 'Sang Zhi', TRUE),
  ('Fructus Amomi', 'Cardamom Fruit', 'Sha Ren', TRUE),
  ('Semen Astragali Complanati', 'Flattened Milkvetch Seed', 'Sha Yuan Zi', TRUE),
  ('Radix Sophorae Subprostratae', 'Sophora Root', 'Shan Dou Gen', TRUE),
  ('Rhizoma Belamcandae', 'Belamcanda Rhizome', 'She Gan', TRUE),
  ('Uncooked Radix Rehmanniae', 'Uncooked Rehmannia Root', 'Sheng Di', TRUE),
  ('Uncooked Rhizoma Zingiberis', 'Fresh Ginger', 'Sheng Jiang', TRUE),
  ('Rhizoma Cimicifugae', 'Black Cohosh Rhizome / Cimicifuga', 'Sheng Ma', TRUE),
  ('Rhizoma Acori Graminei', 'Acorus Rhizome / Sweetflag Rhizome', 'Shi Chang Pu', TRUE),
  ('Calx Khaki', 'Persimmon Calyx', 'Shi Di', TRUE),
  ('Gypsum Fibrosum', 'Gypsum', 'Shi Gao', TRUE),
  ('Cooked Radix Rehmanniae', 'Prepared Rehmannia Root', 'Shu Di', TRUE),
  ('Semen Panici Miliacei', 'Millet', 'Shu Mi', TRUE),
  ('Semen Zizyphi Spinosae', 'Sour Jujube Seed / Zizyphus', 'Suan Zao Ren', TRUE),
  ('Lignum Santali Albi', 'White Sandalwood', 'Tan Xiang', TRUE),
  ('Semen Pruni Persicae', 'Peach Kernel', 'Tao Ren', TRUE),
  ('Tuber Aspargi Cochinensis', 'Asparagus Tuber', 'Tian Men Dong', TRUE),
  ('Semen Lepidii', 'Pepperweed Seed / Lepidium Seed', 'Ting Li Zi', TRUE),
  ('Feces Trogopterori Seu Pteromi', 'Flying Squirrel Feces', 'Wu Ling Zhi', TRUE),
  ('Fructus Schisandrae Chinensis', 'Schisandra Fruit', 'Wu Wei Zi', TRUE),
  ('Radix Linderae Strychnifoliae', 'Lindera Root', 'Wu Yao', TRUE),
  ('Fructus Evodiae Rutecarpae', 'Evodia Fruit', 'Wu Zhu Yu', TRUE),
  ('Herba Asari Cum Radice', 'Chinese Wild Ginger', 'Xi Xin', TRUE),
  ('Rhizoma Cyperi Rotundi', 'Cyperus Rhizome', 'Xiang Fu', TRUE),
  ('Bulbus Allii', 'Allium Bulb', 'Xie Bai', TRUE),
  ('Flos Magnoliae Liliflorae', 'Magnolia Flower Bud', 'Xin Yi Hua', TRUE),
  ('Semen Pruni Armeniacae', 'Apricot Kernel / Bitter Apricot Seed', 'Xing Ren', TRUE),
  ('Radix Dipsaci', 'Teasel Root', 'Xu Duan', TRUE),
  ('Flos Inulae', 'Inula Flower / Elecampane Flower', 'Xuan Fu Hua', TRUE),
  ('Radix Scrophulariae Ningpoensis', 'Scrophularia Root / Figwort Root', 'Xuan Shen', TRUE),
  ('Rhizoma Corydalis Yanhusuo', 'Corydalis Rhizome', 'Yan Hu Suo', TRUE),
  ('Herba Leonuri Heterophylli', 'Motherwort', 'Yi Mu Cao', TRUE),
  ('Fructus Alpiniae Oxyphyllae', 'Black Cardamom Fruit / Alpinia Fruit', 'Yi Zhi Ren', TRUE),
  ('Tuber Curcumae', 'Curcuma Tuber', 'Yu Jin', TRUE),
  ('Radix Polygalae Tenuifoliae', 'Polygala Root', 'Yuan Zhi', TRUE),
  ('Rhizoma Alismatis', 'Alisma Rhizome', 'Ze Xie', TRUE),
  ('Fructus Citri Aurantii', 'Bitter Orange Fruit', 'Zhi Ke', TRUE),
  ('Rhizoma Anemarrhenae Aspheloidis', 'Anemarrhena Rhizome', 'Zhi Mu', TRUE),
  ('Fructus Immaturus Citri Aurantii', 'Unripe Bitter Orange', 'Zhi Shi', TRUE),
  ('Fructus Gardeniae Jasminoidis', 'Gardenia Fruit', 'Zhi Zi', TRUE),
  ('Caulis Bambusae In Taeniis', 'Bamboo Shavings', 'Zhu Ru', TRUE),
  ('Folium Bambusae', 'Bamboo Leaf', 'Zhu Ye', TRUE),
  ('Herba Violae Yedoensis Cum Radice', 'Violet', 'Zi Hua Di Ding', TRUE),
  ('Folium Et Caulis Perillae Frutescentis', 'Perilla Leaf and Stem', 'Zi Su', TRUE),
  ('Radix Asteris Tatarici', 'Aster Root', 'Zi Wan', TRUE)
ON CONFLICT (latin_name) DO UPDATE
  SET pinyin_name = EXCLUDED.pinyin_name,
      is_tcm = TRUE;

DO $$ BEGIN
  RAISE NOTICE 'Migration 081 complete: inserted/updated 143 TCM herbs';
  RAISE NOTICE 'TCM herb count: %', (SELECT count(*) FROM herbal.herbs WHERE is_tcm = TRUE);
END $$;
