SET search_path TO herbal, public;

-- Add synonyms column (alternate common names for search)
ALTER TABLE herbal.herbs ADD COLUMN IF NOT EXISTS synonyms TEXT[] NOT NULL DEFAULT '{}';

-- ─── Populate synonyms by latin name ──────────────────────────────────────────
-- Updates apply to all plant-part variants of the same species.

UPDATE herbal.herbs SET synonyms = ARRAY['Korean Mint','Giant Hyssop','Huo Xiang'] WHERE latin_name = 'Agastache rugosa';
UPDATE herbal.herbs SET synonyms = ARRAY['Church Steeples','Sticklewort','Common Agrimony'] WHERE latin_name = 'Agrimonia eupatoria';
UPDATE herbal.herbs SET synonyms = ARRAY['Lucerne','Buffalo Herb','Purple Medick'] WHERE latin_name = 'Medicago sativa';
UPDATE herbal.herbs SET synonyms = ARRAY['Aloe Vera','Burn Plant','Cape Aloe','True Aloe','Barbados Aloe'] WHERE latin_name = 'Aloe vera';
UPDATE herbal.herbs SET synonyms = ARRAY['White Ginseng','Sang','Xi Yang Shen','North American Ginseng'] WHERE latin_name = 'Panax quinquefolius';
UPDATE herbal.herbs SET synonyms = ARRAY['European Angelica','Garden Angelica','Holy Ghost','Wild Angelica'] WHERE latin_name = 'Angelica archangelica';
UPDATE herbal.herbs SET synonyms = ARRAY['Anise','Sweet Cumin','Anise Seed'] WHERE latin_name = 'Pimpinella anisum';
UPDATE herbal.herbs SET synonyms = ARRAY['Mountain Tobacco','Leopard''s Bane','Wolf''s Bane','Mountain Arnica'] WHERE latin_name = 'Arnica montana';
UPDATE herbal.herbs SET synonyms = ARRAY['Globe Artichoke','Garden Artichoke'] WHERE latin_name = 'Cynara scolymus';
UPDATE herbal.herbs SET synonyms = ARRAY['Indian Ginseng','Winter Cherry','Withania','Ashwaganda'] WHERE latin_name = 'Withania somnifera';
UPDATE herbal.herbs SET synonyms = ARRAY['Quaking Aspen','Trembling Aspen','Popple'] WHERE latin_name = 'Populus tremuloides';
UPDATE herbal.herbs SET synonyms = ARRAY['Huang Qi','Milk Vetch','Yellow Vetch','Bei Qi'] WHERE latin_name = 'Astragalus membranaceus';
UPDATE herbal.herbs SET synonyms = ARRAY['Brahmi','Water Hyssop','Herb of Grace'] WHERE latin_name = 'Bacopa monnieri';
UPDATE herbal.herbs SET synonyms = ARRAY['Poplar Buds','Gilead Balm'] WHERE latin_name = 'Populus candicans';
UPDATE herbal.herbs SET synonyms = ARRAY['Turtlehead','Snakehead','Salt-Rheum Weed','White Turtlehead'] WHERE latin_name = 'Chelone glabra';
UPDATE herbal.herbs SET synonyms = ARRAY['European Barberry','Common Barberry','Jaundice Berry'] WHERE latin_name = 'Berberis vulgaris';
UPDATE herbal.herbs SET synonyms = ARRAY['Wax Myrtle','Candleberry','Waxberry','Southern Bayberry'] WHERE latin_name = 'Myrica cerifera';
UPDATE herbal.herbs SET synonyms = ARRAY['Uva Ursi','Kinnikinnick','Mountain Box','Bear''s Grape','Hogberry'] WHERE latin_name = 'Arctostaphylos uva-ursi';
UPDATE herbal.herbs SET synonyms = ARRAY['European Blueberry','Whortleberry','Wild Blueberry'] WHERE latin_name = 'Vaccinium myrtillus';
UPDATE herbal.herbs SET synonyms = ARRAY['Silver Birch','White Birch','Paper Birch'] WHERE latin_name = 'Betula spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['Snakeweed','Patience Dock','Serpent Root','Red Bistort'] WHERE latin_name = 'Polygonum bistorta';
UPDATE herbal.herbs SET synonyms = ARRAY['Catechu','Kutch','Dark Catechu','Wadalee Gum'] WHERE latin_name = 'Acacia catechu';
UPDATE herbal.herbs SET synonyms = ARRAY['Bugbane','Rattleroot','Squawroot','Black Snakeroot','Cimicifuga'] WHERE latin_name = 'Actaea racemosa';
UPDATE herbal.herbs SET synonyms = ARRAY['Stagbush','American Sloe'] WHERE latin_name = 'Viburnum prunifolium';
UPDATE herbal.herbs SET synonyms = ARRAY['Fetid Horehound','Black Stinking Horehound'] WHERE latin_name = 'Ballota nigra';
UPDATE herbal.herbs SET synonyms = ARRAY['Bowman''s Root','Culver''s Root','Culver''s Physic'] WHERE latin_name = 'Leptandra virginica';
UPDATE herbal.herbs SET synonyms = ARRAY['Bramble','Dewberry','Common Blackberry'] WHERE latin_name = 'Rubus villosus';
UPDATE herbal.herbs SET synonyms = ARRAY['Holy Thistle','St. Benedict''s Thistle','Cnicus'] WHERE latin_name = 'Cnicus benedictus';
UPDATE herbal.herbs SET synonyms = ARRAY['Coon Root','Indian Paint','Red Root','Tetterwort','Sweet Slumber'] WHERE latin_name = 'Sanguinaria canadensis';
UPDATE herbal.herbs SET synonyms = ARRAY['Squawroot','Papoose Root','Blue Ginseng','Yellow Ginseng'] WHERE latin_name = 'Caulophyllum thalictroides';
UPDATE herbal.herbs SET synonyms = ARRAY['Wild Iris','Poison Iris','Flag Lily','Harlequin Blue Flag','Liver Lily'] WHERE latin_name = 'Iris versicolor';
UPDATE herbal.herbs SET synonyms = ARRAY['American Vervain','Wild Hyssop','Simpler''s Joy'] WHERE latin_name = 'Verbena hastata';
UPDATE herbal.herbs SET synonyms = ARRAY['Buckbean','Marsh Clover','Water Shamrock','Marsh Trefoil'] WHERE latin_name = 'Menyanthes trifoliata';
UPDATE herbal.herbs SET synonyms = ARRAY['Boldina','Boldo-Do-Chile'] WHERE latin_name = 'Peumus boldus';
UPDATE herbal.herbs SET synonyms = ARRAY['Thoroughwort','Agueweed','Common Boneset','Feverwort','Sweating Plant'] WHERE latin_name = 'Eupatorium perfoliatum';
UPDATE herbal.herbs SET synonyms = ARRAY['Starflower','Cool Tankard','Bee Bread'] WHERE latin_name = 'Borago officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Bookoo','Bucku','Short Buchu'] WHERE latin_name = 'Agathosma betulina';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Buckthorn','Waythorn','Purging Buckthorn','Hart''s Thorn'] WHERE latin_name = 'Rhamnus cathartica';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Buckwheat','Beech Wheat'] WHERE latin_name = 'Fagopyrum esculentum';
UPDATE herbal.herbs SET synonyms = ARRAY['Gypsywort','Water Horehound','Sweet Bugle'] WHERE latin_name = 'Lycopus spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['Chai Hu','Hare''s Ear Root','Thorow-Wax'] WHERE latin_name = 'Bupleurum falcatum';
UPDATE herbal.herbs SET synonyms = ARRAY['Bei Chai Hu','Chai Hu','Thorow-Wax'] WHERE latin_name = 'Bupleurum chinense';
UPDATE herbal.herbs SET synonyms = ARRAY['Gobo','Beggar''s Buttons','Burr Root','Greater Burdock','Clotbur','Lappa'] WHERE latin_name = 'Arctium lappa';
UPDATE herbal.herbs SET synonyms = ARRAY['White Walnut','Oilnut','White Walnut Bark'] WHERE latin_name = 'Juglans cinerea';
UPDATE herbal.herbs SET synonyms = ARRAY['Pot Marigold','Mary''s Gold','English Marigold','Gold Bloom'] WHERE latin_name = 'Calendula officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Golden Poppy','Cup of Gold','Eschscholzia'] WHERE latin_name = 'Eschscholzia californica';
UPDATE herbal.herbs SET synonyms = ARRAY['Caraway Seed','Wild Caraway','Persian Cumin'] WHERE latin_name = 'Carum carvi';
UPDATE herbal.herbs SET synonyms = ARRAY['Cardamon','Green Cardamom','True Cardamom'] WHERE latin_name = 'Elettaria cardamomum';
UPDATE herbal.herbs SET synonyms = ARRAY['Sacred Bark','California Buckthorn','Cascara','Chittem Bark'] WHERE latin_name = 'Rhamnus purshiana';
UPDATE herbal.herbs SET synonyms = ARRAY['Cashew Nut','Cashew Tree'] WHERE latin_name = 'Anacardium occidentale';
UPDATE herbal.herbs SET synonyms = ARRAY['Catmint','Catnep','Catswort','Field Balm'] WHERE latin_name = 'Nepeta cataria';
UPDATE herbal.herbs SET synonyms = ARRAY['Hot Pepper','Red Pepper','Chilli','Capsicum','Bird Pepper','Chili Pepper'] WHERE latin_name = 'Capsicum annuum';
UPDATE herbal.herbs SET synonyms = ARRAY['Greater Celandine','Swallowwort','Tetterwort','Garden Celandine'] WHERE latin_name = 'Chelidonium majus';
UPDATE herbal.herbs SET synonyms = ARRAY['Smallage','Wild Celery'] WHERE latin_name = 'Apium graveolens';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Centaury','European Centaury','Bitter Herb'] WHERE latin_name = 'Centaurium erythraea';
UPDATE herbal.herbs SET synonyms = ARRAY['German Chamomile','Wild Chamomile','Scented Mayweed','Hungarian Chamomile'] WHERE latin_name = 'Matricaria recutita';
UPDATE herbal.herbs SET synonyms = ARRAY['Creosote Bush','Greasewood','Larrea','Gobernadora'] WHERE latin_name = 'Larrea tridentata';
UPDATE herbal.herbs SET synonyms = ARRAY['Chaste Tree','Vitex','Abraham''s Balm','Monk''s Pepper','Agnus Castus'] WHERE latin_name = 'Vitex agnus-castus';
UPDATE herbal.herbs SET synonyms = ARRAY['Garbanzo Bean','Bengal Gram','Egyptian Pea'] WHERE latin_name = 'Cicer arietinum';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Chickweed','Starweed','Winter Weed','Satin Flower'] WHERE latin_name = 'Stellaria media';
UPDATE herbal.herbs SET synonyms = ARRAY['Ceylon Cinnamon','True Cinnamon','Cassia'] WHERE latin_name = 'Cinnamomum spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['Cassia Bark','Chinese Cinnamon','Chinese Cassia'] WHERE latin_name = 'Cinnamomum aromaticum';
UPDATE herbal.herbs SET synonyms = ARRAY['Clary','Clear Eye','Muscatel Sage'] WHERE latin_name = 'Salvia sclarea';
UPDATE herbal.herbs SET synonyms = ARRAY['Goosegrass','Clivers','Sticky Willy','Bedstraw','Catchweed','Grip Grass'] WHERE latin_name = 'Galium aparine';
UPDATE herbal.herbs SET synonyms = ARRAY['Cloves','Clove Tree','Eugenia caryophyllata'] WHERE latin_name = 'Syzygium aromaticum';
UPDATE herbal.herbs SET synonyms = ARRAY['Dang Shen','Poor Man''s Ginseng','Bellflower Root'] WHERE latin_name = 'Codonopsis pilosula';
UPDATE herbal.herbs SET synonyms = ARRAY['Arabian Coffee','Common Coffee'] WHERE latin_name = 'Coffea arabica';
UPDATE herbal.herbs SET synonyms = ARRAY['Forskolin','Indian Coleus','Makandi'] WHERE latin_name = 'Coleus forskohlii';
UPDATE herbal.herbs SET synonyms = ARRAY['Coughwort','Foalswort','Horsehoof','Bull''s Foot','Horse-Hoof'] WHERE latin_name = 'Tussilago farfara';
UPDATE herbal.herbs SET synonyms = ARRAY['Knitbone','Boneset','Bruisewort','Consound','Healing Herb'] WHERE latin_name = 'Symphytum officinale';
UPDATE herbal.herbs SET synonyms = ARRAY['Eagle Vine','Condurango Bark'] WHERE latin_name = 'Marsdenia condurango';
UPDATE herbal.herbs SET synonyms = ARRAY['Cilantro Seed','Chinese Parsley','Dhania'] WHERE latin_name = 'Coriandrum sativum';
UPDATE herbal.herbs SET synonyms = ARRAY['Maize Silk','Zea Stigma','Corn'] WHERE latin_name = 'Zea mays';
UPDATE herbal.herbs SET synonyms = ARRAY['Yan Hu Suo'] WHERE latin_name = 'Corydalis yanhusuo';
UPDATE herbal.herbs SET synonyms = ARRAY['Quack Grass','Dog Grass','Twitch Grass','Witch Grass','Quick Grass','Creeping Wheat Grass'] WHERE latin_name = 'Elymus repens';
UPDATE herbal.herbs SET synonyms = ARRAY['Paigle','Keys of Heaven','Fairy Cups','Our Lady''s Keys'] WHERE latin_name = 'Primula veris';
UPDATE herbal.herbs SET synonyms = ARRAY['Guelder Rose','European Cranberry Bush','Snowball Tree','High Bush Cranberry'] WHERE latin_name = 'Viburnum opulus';
UPDATE herbal.herbs SET synonyms = ARRAY['American Cranberry','Large Cranberry'] WHERE latin_name = 'Vaccinium macrocarpon';
UPDATE herbal.herbs SET synonyms = ARRAY['Wild Geranium','American Cranesbill','Spotted Cranesbill','Alum Root'] WHERE latin_name = 'Geranium maculatum';
UPDATE herbal.herbs SET synonyms = ARRAY['Italian Cypress','Mediterranean Cypress'] WHERE latin_name = 'Cupressus sempervirens';
UPDATE herbal.herbs SET synonyms = ARRAY['Danshen','Salvia Root','Red Sage Root','Chinese Sage','Tan Shen','Dan Shen Root'] WHERE latin_name = 'Salvia miltiorrhiza';
UPDATE herbal.herbs SET synonyms = ARRAY['Mexican Damiana','Turnera','Old Woman''s Broom'] WHERE latin_name = 'Turnera diffusa';
UPDATE herbal.herbs SET synonyms = ARRAY['Lion''s Tooth','Pissabed','Taraxacum','Blowball','Wet-A-Bed'] WHERE latin_name = 'Taraxacum officinale';
UPDATE herbal.herbs SET synonyms = ARRAY['Grapple Plant','Wood Spider','Devil''s Root','Harpago'] WHERE latin_name = 'Harpagophytum procumbens';
UPDATE herbal.herbs SET synonyms = ARRAY['Pacific Devil''s Club','Alaskan Ginseng'] WHERE latin_name = 'Oplopanax horridus';
UPDATE herbal.herbs SET synonyms = ARRAY['Dillweed','Dill Seed','Garden Dill'] WHERE latin_name = 'Anethum graveolens';
UPDATE herbal.herbs SET synonyms = ARRAY['Dang Gui','Chinese Angelica','Female Ginseng','Tang Kuei'] WHERE latin_name = 'Angelica sinensis';
UPDATE herbal.herbs SET synonyms = ARRAY['Mountain Pine','Swiss Mountain Pine'] WHERE latin_name = 'Pinus pumilio';
UPDATE herbal.herbs SET synonyms = ARRAY['Purple Coneflower','Coneflower','Kansas Snakeroot','Echinacea'] WHERE latin_name = 'Echinacea spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['Kansas Snakeroot','Narrow-Leaf Coneflower'] WHERE latin_name = 'Echinacea angustifolia';
UPDATE herbal.herbs SET synonyms = ARRAY['Elderberry','Elderflower','Black Elder','Bore Tree','Boor Tree'] WHERE latin_name = 'Sambucus nigra';
UPDATE herbal.herbs SET synonyms = ARRAY['Elfdock','Elfwort','Horse-Heal','Scabwort','Yellow Starwort','Wild Sunflower'] WHERE latin_name = 'Inula helenium';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Daisy','Lawn Daisy','Bruisewort'] WHERE latin_name = 'Bellis perennis';
UPDATE herbal.herbs SET synonyms = ARRAY['Blue Gum','Fever Tree','Tasmanian Bluegum','Gum Tree'] WHERE latin_name = 'Eucalyptus spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['Night Willowherb','King''s Cure-All','Evening Star','German Rampion'] WHERE latin_name = 'Oenothera biennis';
UPDATE herbal.herbs SET synonyms = ARRAY['Euphrasia','Meadow Eyebright'] WHERE latin_name = 'Euphrasia spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['False Spikenard','Wild Spikenard','Solomon''s Plume'] WHERE latin_name = 'Smilacina racemosa';
UPDATE herbal.herbs SET synonyms = ARRAY['Sweet Fennel','Roman Fennel','Finocchio','Fenkel'] WHERE latin_name = 'Foeniculum vulgare';
UPDATE herbal.herbs SET synonyms = ARRAY['Methi','Greek Clover','Greek Hay-Seed','Bird''s Foot'] WHERE latin_name = 'Trigonella foenum-graecum';
UPDATE herbal.herbs SET synonyms = ARRAY['Featherfew','Bachelor''s Buttons','Midsummer Daisy'] WHERE latin_name = 'Tanacetum parthenium';
UPDATE herbal.herbs SET synonyms = ARRAY['Knotted Figwort','Throatwort','Carpenter''s Square'] WHERE latin_name = 'Scrophularia nodosa';
UPDATE herbal.herbs SET synonyms = ARRAY['Linseed','Common Flax','Flaxseed','Linseeds'] WHERE latin_name = 'Linum usitatissimum';
UPDATE herbal.herbs SET synonyms = ARRAY['White Fringetree','Old Man''s Beard','Grancy Greybeard','Snowdrop Tree'] WHERE latin_name = 'Chionanthus virginicus';
UPDATE herbal.herbs SET synonyms = ARRAY['Earth Smoke','Fumaria','Beggary','Wax Dolls','Hedge Fumitory'] WHERE latin_name = 'Fumaria officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Stinking Rose','Allium','Poor Man''s Treacle','Ail'] WHERE latin_name = 'Allium sativum';
UPDATE herbal.herbs SET synonyms = ARRAY['Yellow Gentian','Bitter Root','Bitterwort','Great Yellow Gentian'] WHERE latin_name = 'Gentiana lutea';
UPDATE herbal.herbs SET synonyms = ARRAY['Ginger Root','Common Ginger','Jamaica Ginger','Sheng Jiang'] WHERE latin_name = 'Zingiber officinale';
UPDATE herbal.herbs SET synonyms = ARRAY['Maidenhair Tree','Ginkgo Biloba'] WHERE latin_name = 'Ginkgo biloba';
UPDATE herbal.herbs SET synonyms = ARRAY['Korean Ginseng','Asian Ginseng','Chinese Ginseng','Red Ginseng','Ren Shen'] WHERE latin_name = 'Panax ginseng';
UPDATE herbal.herbs SET synonyms = ARRAY['Galega','Italian Fitch','Professor-Weed','French Lilac'] WHERE latin_name = 'Galega officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['European Goldenrod','Woundwort'] WHERE latin_name = 'Solidago virgaurea';
UPDATE herbal.herbs SET synonyms = ARRAY['Yellow Root','Ground Raspberry','Indian Turmeric','Orange Root'] WHERE latin_name = 'Hydrastis canadensis';
UPDATE herbal.herbs SET synonyms = ARRAY['Indian Pennywort','Brahmi','Asiatic Pennywort','Centella','Tiger Grass'] WHERE latin_name = 'Centella asiatica';
UPDATE herbal.herbs SET synonyms = ARRAY['Grapeseed Extract','OPC','Proanthocyanidin','Grape Vine'] WHERE latin_name = 'Vitis vinifera';
UPDATE herbal.herbs SET synonyms = ARRAY['Joe Pye Weed','Purple Boneset','Gravel Weed','Kidney Root','Trumpet Weed'] WHERE latin_name = 'Eupatorium purpureum';
UPDATE herbal.herbs SET synonyms = ARRAY['Grindelia','Gumweed','Rosinweed','Curly-Top Gumweed'] WHERE latin_name = 'Grindelia squarrosa';
UPDATE herbal.herbs SET synonyms = ARRAY['Rosinweed','Gumweed'] WHERE latin_name = 'Grindelia camporum';
UPDATE herbal.herbs SET synonyms = ARRAY['Lignum Vitae','Ironwood','Pockwood','Guaiac'] WHERE latin_name = 'Guaiacum officinale';
UPDATE herbal.herbs SET synonyms = ARRAY['Guarana Seed','Brazilian Cocoa','Zoom'] WHERE latin_name = 'Paullinia cupana';
UPDATE herbal.herbs SET synonyms = ARRAY['Tinospora','Amrita','Giloya','Heart-Leaved Moonseed','Gurcha'] WHERE latin_name = 'Tinospora cordifolia';
UPDATE herbal.herbs SET synonyms = ARRAY['Indian Bdellium','Gum Guggul','Mukul Myrrh'] WHERE latin_name = 'Commiphora mukul';
UPDATE herbal.herbs SET synonyms = ARRAY['Gurmar','Sugar Destroyer','Cowplant'] WHERE latin_name = 'Gymnema sylvestre';
UPDATE herbal.herbs SET synonyms = ARRAY['Eucommia','Du Zhong','Chinese Rubber Tree'] WHERE latin_name = 'Eucommia ulmoides';
UPDATE herbal.herbs SET synonyms = ARRAY['Whitethorn','Maythorn','Quickthorn','May Blossom'] WHERE latin_name = 'Crataegus spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['Wild Pansy','Johnny-Jump-Up','Love-in-Idleness','Heart''s Ease'] WHERE latin_name = 'Viola tricolor';
UPDATE herbal.herbs SET synonyms = ARRAY['Immortelle','Curry Plant','Everlasting','Strawflower'] WHERE latin_name = 'Helichrysum italicum';
UPDATE herbal.herbs SET synonyms = ARRAY['Roselle','Red Sorrel','Karkade','Flor de Jamaica'] WHERE latin_name = 'Hibiscus sabdariffa';
UPDATE herbal.herbs SET synonyms = ARRAY['Tulsi','Sacred Basil','Rama Tulsi','Holy Herb'] WHERE latin_name = 'Ocimum sanctum';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Hops','Lupulus','Hop','Hop Vine'] WHERE latin_name = 'Humulus lupulus';
UPDATE herbal.herbs SET synonyms = ARRAY['White Horehound','Marrubium','Common Horehound'] WHERE latin_name = 'Marrubium vulgare';
UPDATE herbal.herbs SET synonyms = ARRAY['Conker Tree','Buckeye'] WHERE latin_name = 'Aesculus hippocastanum';
UPDATE herbal.herbs SET synonyms = ARRAY['Red Cole','Mountain Radish'] WHERE latin_name = 'Armoracia rusticana';
UPDATE herbal.herbs SET synonyms = ARRAY['Shavegrass','Pewter Wort','Scouring Rush','Field Horsetail','Bottlebrush'] WHERE latin_name = 'Equisetum arvense';
UPDATE herbal.herbs SET synonyms = ARRAY['Wild Hydrangea','Seven Barks','Smooth Hydrangea'] WHERE latin_name = 'Hydrangea arborescens';
UPDATE herbal.herbs SET synonyms = ARRAY['Hyssopus','Common Hyssop'] WHERE latin_name = 'Hyssopus officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Cetraria','Iceland Lichen'] WHERE latin_name = 'Cetraria islandica';
UPDATE herbal.herbs SET synonyms = ARRAY['Amla','Amalaki','Emblic Myrobalan'] WHERE latin_name = 'Phyllanthus emblica';
UPDATE herbal.herbs SET synonyms = ARRAY['Ipecacuanha','Ipecac Root','Brazilian Ipecac'] WHERE latin_name = 'Cephaelis ipecacuanha';
UPDATE herbal.herbs SET synonyms = ARRAY['Carrageen','Carrageenan','Pearl Moss'] WHERE latin_name = 'Chondrus crispus';
UPDATE herbal.herbs SET synonyms = ARRAY['Piscidia','Fish Poison Tree','West Indian Dogwood'] WHERE latin_name = 'Piscidia erythrina';
UPDATE herbal.herbs SET synonyms = ARRAY['Piscidia','Fish Poison Tree','West Indian Dogwood'] WHERE latin_name = 'Piscidia piscipula';
UPDATE herbal.herbs SET synonyms = ARRAY['Juniper Berry','Common Juniper','Gin Plant'] WHERE latin_name = 'Juniperus communis';
UPDATE herbal.herbs SET synonyms = ARRAY['Kava Kava','Awa','Pepper Root','Intoxicating Pepper'] WHERE latin_name = 'Piper methysticum';
UPDATE herbal.herbs SET synonyms = ARRAY['Bladderwrack','Rockweed','Sea Oak','Sea Kelp','Bladder Fucus','Black Tangle'] WHERE latin_name = 'Fucus vesiculosus';
UPDATE herbal.herbs SET synonyms = ARRAY['Oarweed','Kombu','Sea Tangle'] WHERE latin_name = 'Laminaria digitata';
UPDATE herbal.herbs SET synonyms = ARRAY['Sugar Kelp','Sea Belt'] WHERE latin_name = 'Saccharina latissima';
UPDATE herbal.herbs SET synonyms = ARRAY['Bishop''s Weed','Toothpick Plant','Toothpick Ammi'] WHERE latin_name = 'Ammi visnaga';
UPDATE herbal.herbs SET synonyms = ARRAY['Kola Nut','Cola Nut','Bitter Kola','Guru Nut'] WHERE latin_name = 'Cola acuminata';
UPDATE herbal.herbs SET synonyms = ARRAY['Kola','Cola','Abata Kola'] WHERE latin_name = 'Cola vera';
UPDATE herbal.herbs SET synonyms = ARRAY['Katuki','Picrorhiza','Kutki Root'] WHERE latin_name = 'Picrorrhiza kurroa';
UPDATE herbal.herbs SET synonyms = ARRAY['Alchemilla','Lion''s Foot','Dewcup','Bear''s Foot'] WHERE latin_name = 'Alchemilla vulgaris';
UPDATE herbal.herbs SET synonyms = ARRAY['English Lavender','True Lavender','Common Lavender'] WHERE latin_name = 'Lavandula spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Lemon'] WHERE latin_name = 'Citrus limon';
UPDATE herbal.herbs SET synonyms = ARRAY['Melissa','Bee Balm','Sweet Balm','Garden Balm','Heart''s Delight'] WHERE latin_name = 'Melissa officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Lemon Beebrush','Verbena','Louisa'] WHERE latin_name = 'Aloysia citrodora';
UPDATE herbal.herbs SET synonyms = ARRAY['Small Periwinkle','Myrtle','Running Myrtle'] WHERE latin_name = 'Vinca minor';
UPDATE herbal.herbs SET synonyms = ARRAY['Liquorice','Sweet Root','Spanish Juice','Licorice Root','Sweetwood'] WHERE latin_name = 'Glycyrrhiza glabra';
UPDATE herbal.herbs SET synonyms = ARRAY['Golden Senecio','Squaw Weed','Golden Groundsel'] WHERE latin_name = 'Senecio aureus';
UPDATE herbal.herbs SET synonyms = ARRAY['Convallaria','May Lily','Our Lady''s Tears','Muguet'] WHERE latin_name = 'Convallaria majalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Lime Flower','Lime Tree','Basswood','Linden Blossom','Tilleul','Linden Flower'] WHERE latin_name = 'Tilia platyphyllos';
UPDATE herbal.herbs SET synonyms = ARRAY['Indian Tobacco','Puke Weed','Asthma Weed','Vomit Wort','Emetic Herb'] WHERE latin_name = 'Lobelia inflata';
UPDATE herbal.herbs SET synonyms = ARRAY['Desert Parsley','Biscuitroot','Fern-Leaf Lomatium','Lomatium Root'] WHERE latin_name = 'Lomatium dissectum';
UPDATE herbal.herbs SET synonyms = ARRAY['Love Parsley','Garden Lovage','Sea Parsley'] WHERE latin_name = 'Levisticum officinale';
UPDATE herbal.herbs SET synonyms = ARRAY['Jerusalem Cowslip','Spotted Dog','Soldiers and Sailors'] WHERE latin_name = 'Pulmonaria officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Chinese Ephedra','Ephedra','Joint Fir'] WHERE latin_name = 'Ephedra sinica';
UPDATE herbal.herbs SET synonyms = ARRAY['Peruvian Maca','Lepidium','Peruvian Ginseng','Maca Root'] WHERE latin_name = 'Lepidium meyenii';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Madder','Dyer''s Madder'] WHERE latin_name = 'Rubia tinctorum';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Mallow','Cheeses','High Mallow','Blue Mallow'] WHERE latin_name = 'Malva sylvestris';
UPDATE herbal.herbs SET synonyms = ARRAY['Manchurian Aralia','Aralia'] WHERE latin_name = 'Aralia manshurica';
UPDATE herbal.herbs SET synonyms = ARRAY['Sweet Marjoram','Knotted Marjoram'] WHERE latin_name = 'Origanum majorana';
UPDATE herbal.herbs SET synonyms = ARRAY['Mallards','Mortification Root','Schloss Tea','White Mallow'] WHERE latin_name = 'Althaea officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Bridewort','Lady of the Meadow','Dolloff','Queen of the Meadow','Spiraea'] WHERE latin_name = 'Filipendula ulmaria';
UPDATE herbal.herbs SET synonyms = ARRAY['Silymarin','Holy Thistle','Marian Thistle','Mary Thistle','Carduus Marianus'] WHERE latin_name = 'Silybum marianum';
UPDATE herbal.herbs SET synonyms = ARRAY['European Mistletoe','Birdlime','All-Heal'] WHERE latin_name = 'Viscum album';
UPDATE herbal.herbs SET synonyms = ARRAY['Lion''s Ear','Throw-Wort','Heartwort'] WHERE latin_name = 'Leonurus cardiaca';
UPDATE herbal.herbs SET synonyms = ARRAY['Mouse-Ear Hawkweed','Pilosella'] WHERE latin_name = 'Hieracium pilosella';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Mugwort','Felon Herb','St. John''s Plant','Chrysanthemum Weed'] WHERE latin_name = 'Artemisia vulgaris';
UPDATE herbal.herbs SET synonyms = ARRAY['White Mulberry','Sang Ye','Silkworm Mulberry'] WHERE latin_name = 'Morus alba';
UPDATE herbal.herbs SET synonyms = ARRAY['Great Mullein','Aaron''s Rod','Flannel Plant','Velvet Dock','Witch''s Taper','Candlewick Plant'] WHERE latin_name = 'Verbascum thapsus';
UPDATE herbal.herbs SET synonyms = ARRAY['Commiphora','Gum Myrrh','Common Myrrh','Somalian Myrrh'] WHERE latin_name = 'Commiphora molmol';
UPDATE herbal.herbs SET synonyms = ARRAY['Stinging Nettle','Common Nettle','Burn Nettle','Common Stinging Nettle'] WHERE latin_name = 'Urtica dioica';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Oak','English Oak','Pedunculate Oak'] WHERE latin_name = 'Quercus spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['American White Oak'] WHERE latin_name = 'Quercus alba';
UPDATE herbal.herbs SET synonyms = ARRAY['Oats','Common Oat','Wild Oat','Avena'] WHERE latin_name = 'Avena sativa';
UPDATE herbal.herbs SET synonyms = ARRAY['Coach Whip','Coachwhip','Jacob''s Staff'] WHERE latin_name = 'Fouquieria splendens';
UPDATE herbal.herbs SET synonyms = ARRAY['Olive Leaf','Olive Tree'] WHERE latin_name = 'Olea europaea';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Onion','Garden Onion','Bulb Onion'] WHERE latin_name = 'Allium cepa';
UPDATE herbal.herbs SET synonyms = ARRAY['Wild Marjoram','Common Oregano','Mountain Marjoram'] WHERE latin_name = 'Origanum vulgare';
UPDATE herbal.herbs SET synonyms = ARRAY['Mountain Grape','Holly-Leaved Barberry','Mahonia','Creeping Barberry'] WHERE latin_name = 'Mahonia aquifolium';
UPDATE herbal.herbs SET synonyms = ARRAY['Porter''s Osha','Colorado Cough Root','Bear Medicine','Bear Root'] WHERE latin_name = 'Ligusticum porteri';
UPDATE herbal.herbs SET synonyms = ARRAY['Garden Parsley','Herb Peters','Rock Parsley','Curly Parsley'] WHERE latin_name = 'Petroselinum crispum';
UPDATE herbal.herbs SET synonyms = ARRAY['Parsley Breakstone','Breakstone Parsley','Field Lady''s Mantle','Aphanes'] WHERE latin_name = 'Aphanes arvensis';
UPDATE herbal.herbs SET synonyms = ARRAY['Squaw Vine','Twinberry','Deer Berry','Running Box'] WHERE latin_name = 'Mitchella repens';
UPDATE herbal.herbs SET synonyms = ARRAY['Pulsatilla','Wind Flower','Prairie Crocus','Easter Flower','Anemone'] WHERE latin_name = 'Pulsatilla vulgaris';
UPDATE herbal.herbs SET synonyms = ARRAY['Maypop','Apricot Vine','True Passionflower','Wild Passionflower','Purple Passionflower'] WHERE latin_name = 'Passiflora incarnata';
UPDATE herbal.herbs SET synonyms = ARRAY['Taheebo','Lapacho','Ipe Roxo','Purple Lapacho'] WHERE latin_name = 'Tabebuia impetiginosa';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Peach','Garden Peach'] WHERE latin_name = 'Prunus persica';
UPDATE herbal.herbs SET synonyms = ARRAY['Pellitory','Wall Pellitory','Lichwort'] WHERE latin_name = 'Parietaria judaica';
UPDATE herbal.herbs SET synonyms = ARRAY['Pudding Grass','Run-By-The-Ground','Lurk-In-The-Ditch','Squaw Mint'] WHERE latin_name = 'Mentha pulegium';
UPDATE herbal.herbs SET synonyms = ARRAY['Brandy Mint','Lamb Mint','Balm Mint'] WHERE latin_name = 'Mentha piperita';
UPDATE herbal.herbs SET synonyms = ARRAY['Greater Periwinkle','Big-Leaf Periwinkle'] WHERE latin_name = 'Vinca major';
UPDATE herbal.herbs SET synonyms = ARRAY['Mescal Button','Mescaline Cactus','Peyotl'] WHERE latin_name = 'Lophophora williamsii';
UPDATE herbal.herbs SET synonyms = ARRAY['Lesser Celandine','Smallwort','Fig Buttercup'] WHERE latin_name = 'Ranunculus ficaria';
UPDATE herbal.herbs SET synonyms = ARRAY['Prince''s Pine','Ground Holly','King''s Cure'] WHERE latin_name = 'Chimaphila umbellata';
UPDATE herbal.herbs SET synonyms = ARRAY['Broadleaf Plantain','Common Plantain','Waybread','Ripple Grass','Greater Plantain'] WHERE latin_name = 'Plantago major';
UPDATE herbal.herbs SET synonyms = ARRAY['Butterfly Weed','Orange Root','Wind Root','Chigger Flower','Tuber Root'] WHERE latin_name = 'Asclepias tuberosa';
UPDATE herbal.herbs SET synonyms = ARRAY['Pokeweed','Pokeberry','Ink Plant','Poke','American Nightshade'] WHERE latin_name = 'Phytolacca americana';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Poppy','Field Poppy','Corn Poppy'] WHERE latin_name = 'Papaver spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['Toothache Tree','Yellow Wood','Northern Prickly Ash'] WHERE latin_name = 'Zanthoxylum americanum';
UPDATE herbal.herbs SET synonyms = ARRAY['Hai Er Shen','Pseudostellaria Root','Taizihen'] WHERE latin_name = 'Pseudostellaria heterophylla';
UPDATE herbal.herbs SET synonyms = ARRAY['Chinese Privet','Wax-Leaf Privet','Nu Zhen Zi'] WHERE latin_name = 'Ligustrum lucidum';
UPDATE herbal.herbs SET synonyms = ARRAY['Ispaghul','Psyllium Husk','Blond Psyllium','Ispaghula'] WHERE latin_name = 'Plantago ovata';
UPDATE herbal.herbs SET synonyms = ARRAY['Pumpkin Seed','Field Pumpkin'] WHERE latin_name = 'Cucurbita pepo';
UPDATE herbal.herbs SET synonyms = ARRAY['Stillingia','Yaw Root','Cockup Hat'] WHERE latin_name = 'Stillingia sylvatica';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Ragwort','Tansy Ragwort','Stinking Willie'] WHERE latin_name = 'Senecio jacobaea';
UPDATE herbal.herbs SET synonyms = ARRAY['Red Raspberry','European Raspberry'] WHERE latin_name = 'Rubus idaeus';
UPDATE herbal.herbs SET synonyms = ARRAY['Meadow Clover','Purple Clover','Wild Clover','Trefoil'] WHERE latin_name = 'Trifolium pratense';
UPDATE herbal.herbs SET synonyms = ARRAY['New Jersey Tea','Mountain Sweet','Wild Snowball'] WHERE latin_name = 'Ceanothus americanus';
UPDATE herbal.herbs SET synonyms = ARRAY['Di Huang','Chinese Foxglove','Glutinous Rehmannia','Shu Di Huang'] WHERE latin_name = 'Rehmannia glutinosa';
UPDATE herbal.herbs SET synonyms = ARRAY['Lingzhi','Ling Zhi','Spirit Plant','Ganoderma'] WHERE latin_name = 'Ganoderma lucidum';
UPDATE herbal.herbs SET synonyms = ARRAY['Peruvian Rhatany','Mapato','Pumacuchu'] WHERE latin_name = 'Krameria triandra';
UPDATE herbal.herbs SET synonyms = ARRAY['Roseroot','Golden Root','Arctic Root','Rose Root','King''s Crown'] WHERE latin_name = 'Rhodiola rosea';
UPDATE herbal.herbs SET synonyms = ARRAY['Chinese Rhubarb','Turkish Rhubarb','Da Huang','Indian Rhubarb','Medicinal Rhubarb'] WHERE latin_name = 'Rheum palmatum';
UPDATE herbal.herbs SET synonyms = ARRAY['English Chamomile','Garden Chamomile','True Chamomile','Double Chamomile'] WHERE latin_name = 'Chamaemelum nobile';
UPDATE herbal.herbs SET synonyms = ARRAY['Rosehips','Dog Rose','Rose Hip','Wild Rose'] WHERE latin_name = 'Rosa spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['Compass Plant','Polar Plant','Old Man','Dew of the Sea'] WHERE latin_name = 'Rosmarinus officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Herb of Grace','Herbygrass','Countryman''s Treacle','Garden Rue'] WHERE latin_name = 'Ruta graveolens';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Sage','Garden Sage','Broadleaf Sage','Culinary Sage'] WHERE latin_name = 'Salvia officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['White Sandalwood','East Indian Sandalwood'] WHERE latin_name = 'Santalum album';
UPDATE herbal.herbs SET synonyms = ARRAY['Smilax','Red Sarsaparilla','Honduran Sarsaparilla','Mexican Sarsaparilla'] WHERE latin_name = 'Smilax spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['Ague Tree','Cinnamon Wood','Saloop'] WHERE latin_name = 'Sassafras albidum';
UPDATE herbal.herbs SET synonyms = ARRAY['Sabal','Palmetto Berry','Fan Palm'] WHERE latin_name = 'Serenoa repens';
UPDATE herbal.herbs SET synonyms = ARRAY['Schisandra','Five Flavor Berry','Wu Wei Zi','Chinese Magnolia Vine','Magnolia Berry'] WHERE latin_name = 'Schisandra chinensis';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Broom','Broom','Spartium'] WHERE latin_name = 'Cytisus scoparius';
UPDATE herbal.herbs SET synonyms = ARRAY['Scotch Pine','Common Pine','Forest Pine'] WHERE latin_name = 'Pinus sylvestris';
UPDATE herbal.herbs SET synonyms = ARRAY['Sea Eryngo','Eryngo'] WHERE latin_name = 'Eryngium maritimum';
UPDATE herbal.herbs SET synonyms = ARRAY['Heal All','Blue Curls','Selfheal','Heart of the Earth'] WHERE latin_name = 'Prunella vulgaris';
UPDATE herbal.herbs SET synonyms = ARRAY['Senega','Milkwort','Mountain Flax','Snake Root','Seneca Root'] WHERE latin_name = 'Polygala senega';
UPDATE herbal.herbs SET synonyms = ARRAY['Alexandrian Senna','Tinnevelly Senna','Egyptian Senna','Cassia Senna'] WHERE latin_name = 'Senna alexandrina';
UPDATE herbal.herbs SET synonyms = ARRAY['Asparagus Root','Wild Asparagus','Satavar','Satmuli'] WHERE latin_name = 'Asparagus racemosus';
UPDATE herbal.herbs SET synonyms = ARRAY['Caseweed','St. James'' Weed','Mother''s Heart','Pickpocket'] WHERE latin_name = 'Capsella bursa-pastoris';
UPDATE herbal.herbs SET synonyms = ARRAY['Chinese Black Mushroom','Lentinus','Oak Mushroom','Forest Mushroom'] WHERE latin_name = 'Lentinus edodes';
UPDATE herbal.herbs SET synonyms = ARRAY['Eleuthero','Eleutherococcus','Devil''s Shrub','Ciwujia','Wujiaseng'] WHERE latin_name = 'Eleutherococcus senticosus';
UPDATE herbal.herbs SET synonyms = ARRAY['Silk-Tassel Bush','Garrya'] WHERE latin_name = 'Garrya fremontii';
UPDATE herbal.herbs SET synonyms = ARRAY['Coast Silk-Tassel','Garrya'] WHERE latin_name = 'Garrya elliptica';
UPDATE herbal.herbs SET synonyms = ARRAY['Mimosa','Persian Silk Tree','Albizzia'] WHERE latin_name = 'Albizia julibrissin';
UPDATE herbal.herbs SET synonyms = ARRAY['Scullcap','Mad Dog Skullcap','Blue Pimpernel','American Skullcap','Hooded Willow Herb'] WHERE latin_name = 'Scutellaria lateriflora';
UPDATE herbal.herbs SET synonyms = ARRAY['Huang Qin','Baikal Skullcap','Baical Skullcap','Chinese Baical Skullcap'] WHERE latin_name = 'Scutellaria baicalensis';
UPDATE herbal.herbs SET synonyms = ARRAY['Meadow Cabbage','Polecat Weed','Fetid Hellebore'] WHERE latin_name = 'Symplocarpus foetidus';
UPDATE herbal.herbs SET synonyms = ARRAY['Red Elm','Indian Elm','Moose Elm','Sweet Elm','Gray Elm'] WHERE latin_name = 'Ulmus rubra';
UPDATE herbal.herbs SET synonyms = ARRAY['King Solomon''s Seal','Common Solomon''s Seal','American Solomon''s Seal'] WHERE latin_name = 'Polygonatum biflorum';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Sorrel','Garden Sorrel','Broad-Leaved Sorrel'] WHERE latin_name = 'Rumex acetosa';
UPDATE herbal.herbs SET synonyms = ARRAY['Old Man','Lad''s Love','Appleringie','Boy''s Love'] WHERE latin_name = 'Artemisia abrotanum';
UPDATE herbal.herbs SET synonyms = ARRAY['American Spikenard','Petty Morel','Indian Root','Spignet'] WHERE latin_name = 'Aralia racemosa';
UPDATE herbal.herbs SET synonyms = ARRAY['Toothache Plant','Eyeball Plant','Electric Daisy','Paracress'] WHERE latin_name = 'Acmella oleracea';
UPDATE herbal.herbs SET synonyms = ARRAY['Garden Spinach','Common Spinach'] WHERE latin_name = 'Spinacia oleracea';
UPDATE herbal.herbs SET synonyms = ARRAY['Sea Onion','Sea Squill','Scilla'] WHERE latin_name = 'Urginea maritima';
UPDATE herbal.herbs SET synonyms = ARRAY['Hypericum','Klamath Weed','Goatweed','Tipton Weed','Rosin Rose','St. John''s Wort'] WHERE latin_name = 'Hypericum perforatum';
UPDATE herbal.herbs SET synonyms = ARRAY['Chanca Piedra','Seed Under Leaf','Phyllanthus'] WHERE latin_name = 'Phyllanthus amarus';
UPDATE herbal.herbs SET synonyms = ARRAY['Horse Balm','Richwood','Heal-All (alt)'] WHERE latin_name = 'Collinsonia canadensis';
UPDATE herbal.herbs SET synonyms = ARRAY['Round-Leaved Sundew','Drosera','Lustwort'] WHERE latin_name = 'Drosera rotundifolia';
UPDATE herbal.herbs SET synonyms = ARRAY['Sweet Orange','Orange Blossom'] WHERE latin_name = 'Citrus sinensis';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Tansy','Bitter Buttons','Cow Bitter'] WHERE latin_name = 'Tanacetum vulgare';
UPDATE herbal.herbs SET synonyms = ARRAY['Green Tea','Black Tea','White Tea','Oolong','Camellia'] WHERE latin_name = 'Camellia sinensis';
UPDATE herbal.herbs SET synonyms = ARRAY['Australian Tea Tree','Melaleuca'] WHERE latin_name = 'Melaleuca spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['White Cedar','Northern White Cedar','Tree of Life','Arborvitae','Yellow Cedar'] WHERE latin_name = 'Thuja occidentalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Thyme','Garden Thyme','English Thyme'] WHERE latin_name = 'Thymus vulgaris';
UPDATE herbal.herbs SET synonyms = ARRAY['Tolu','Balsam of Tolu'] WHERE latin_name = 'Myroxylon balsamum var. balsamum';
UPDATE herbal.herbs SET synonyms = ARRAY['Indian Balsam','Peruvian Balsam'] WHERE latin_name = 'Myroxylon balsamum var. pereirae';
UPDATE herbal.herbs SET synonyms = ARRAY['Indian Saffron','Curcumin','Yellow Root','Haldi'] WHERE latin_name = 'Curcuma longa';
UPDATE herbal.herbs SET synonyms = ARRAY['Old Man''s Beard','Tree Moss','Beard Lichen','Lung Lichen','Tree''s Dandruff'] WHERE latin_name = 'Usnea spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['All-Heal','Garden Heliotrope','Setwall','Capon''s Tail'] WHERE latin_name = 'Valeriana officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Vervain','Holy Herb','Enchanter''s Plant','Juno''s Tears','Pigeon''s Grass'] WHERE latin_name = 'Verbena officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Sweet Violet','English Violet','Common Violet','Florist''s Violet','Garden Violet'] WHERE latin_name = 'Viola odorata';
UPDATE herbal.herbs SET synonyms = ARRAY['Burning Bush','Spindle Tree','Arrow-Wood'] WHERE latin_name = 'Euonymus atropurpureus';
UPDATE herbal.herbs SET synonyms = ARRAY['Palm-Leaved Coltsfoot','Coltsfoot Butterbur'] WHERE latin_name = 'Petasites palmatus';
UPDATE herbal.herbs SET synonyms = ARRAY['White Mustard','Brown Mustard'] WHERE latin_name = 'Brassica alba';
UPDATE herbal.herbs SET synonyms = ARRAY['White Water Lily','Fragrant Water Lily','American White Waterlily'] WHERE latin_name = 'Nymphaea odorata';
UPDATE herbal.herbs SET synonyms = ARRAY['Bai Shao','Chinese Peony','Lactiflora Peony'] WHERE latin_name = 'Paeonia lactiflora';
UPDATE herbal.herbs SET synonyms = ARRAY['Queen Anne''s Lace','Bird''s Nest','Bishop''s Lace','Wild Carrot Seed'] WHERE latin_name = 'Daucus carota';
UPDATE herbal.herbs SET synonyms = ARRAY['Black Cherry','Rum Cherry','Mountain Black Cherry'] WHERE latin_name = 'Prunus serotina';
UPDATE herbal.herbs SET synonyms = ARRAY['Rattlebush','Horse-Fly Weed','Rattleweed','Indigo Weed'] WHERE latin_name = 'Baptisia tinctoria';
UPDATE herbal.herbs SET synonyms = ARRAY['Opium Lettuce','Bitter Lettuce','Lactucarium','Acrid Lettuce'] WHERE latin_name = 'Lactuca virosa';
UPDATE herbal.herbs SET synonyms = ARRAY['Colic Root','Devil''s Bones','China Root','Rheumatism Root','Atlantic Yam'] WHERE latin_name = 'Dioscorea villosa';
UPDATE herbal.herbs SET synonyms = ARRAY['White Willow','Crack Willow','Pussy Willow'] WHERE latin_name = 'Salix spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['Checkerberry','Teaberry','Mountain Tea','Boxberry','Eastern Teaberry'] WHERE latin_name = 'Gaultheria procumbens';
UPDATE herbal.herbs SET synonyms = ARRAY['Snapping Hazel','Spotted Alder','Tobacco Wood','Winter Bloom'] WHERE latin_name = 'Hamamelis virginiana';
UPDATE herbal.herbs SET synonyms = ARRAY['Bishop''s Wort','Betony','Lousewort'] WHERE latin_name = 'Stachys officinalis';
UPDATE herbal.herbs SET synonyms = ARRAY['Absinth','Bitter Herb','Green Ginger','Old Woman','Absinthe'] WHERE latin_name = 'Artemisia absinthium';
UPDATE herbal.herbs SET synonyms = ARRAY['Acanthopanax','Siberian Ginseng (alt)'] WHERE latin_name = 'Acanthopanax sessiliflorum';
UPDATE herbal.herbs SET synonyms = ARRAY['Milfoil','Common Yarrow','Knight''s Milfoil','Soldier''s Woundwort','Nosebleed Plant','Achillea'] WHERE latin_name = 'Achillea millefolium';
UPDATE herbal.herbs SET synonyms = ARRAY['Curly Dock','Narrow Dock','Rumex','Sour Dock'] WHERE latin_name = 'Rumex crispus';
UPDATE herbal.herbs SET synonyms = ARRAY['Carolina Jasmine','Yellow Jessamine','Evening Trumpet Flower'] WHERE latin_name = 'Gelsemium sempervirens';
UPDATE herbal.herbs SET synonyms = ARRAY['Yerba del Manso','Swamp Root','Lizard Tail'] WHERE latin_name = 'Anemopsis californica';
UPDATE herbal.herbs SET synonyms = ARRAY['Mate','Paraguay Tea','Jesuit''s Tea','Brazilian Tea'] WHERE latin_name = 'Ilex paraguayensis';
UPDATE herbal.herbs SET synonyms = ARRAY['Bear''s Weed','Consumptive''s Weed','Gum Plant','Mountain Balm','Tar Weed'] WHERE latin_name = 'Eriodictyon californicum';
UPDATE herbal.herbs SET synonyms = ARRAY['Ilang-Ilang','Perfume Tree'] WHERE latin_name = 'Cananga odorata';
UPDATE herbal.herbs SET synonyms = ARRAY['Johimbe','Yohimbine Tree'] WHERE latin_name = 'Pausinystalia johimbe';
UPDATE herbal.herbs SET synonyms = ARRAY['Spanish Bayonet','Yucca Root'] WHERE latin_name = 'Yucca spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['White Turmeric','Wild Ginger (alt)','Kachur'] WHERE latin_name = 'Curcuma zedoaria';
UPDATE herbal.herbs SET synonyms = ARRAY['Gum Benzoin','Benjamin Tree','Benzoin Resin'] WHERE latin_name = 'Styrax benzoin';
UPDATE herbal.herbs SET synonyms = ARRAY['Bitter Orange','Seville Orange','Sour Orange'] WHERE latin_name = 'Citrus aurantium';
UPDATE herbal.herbs SET synonyms = ARRAY['Bergamot Orange','Citrus Bergamia'] WHERE latin_name = 'Citrus aurantium ssp. bergamia';
UPDATE herbal.herbs SET synonyms = ARRAY['Corn Mint','Field Mint','Japanese Mint'] WHERE latin_name = 'Mentha arvensis var. piperascens';
UPDATE herbal.herbs SET synonyms = ARRAY['Kani Koorka','Southernmost Indian Herb'] WHERE latin_name = 'Trichopus zeylanicus';
UPDATE herbal.herbs SET synonyms = ARRAY['Common Chicory','Succory','Coffeeweed','Blue Daisy'] WHERE latin_name = 'Cichorium intybus';
UPDATE herbal.herbs SET synonyms = ARRAY['American Black Walnut','Eastern Black Walnut'] WHERE latin_name = 'Juglans nigra';
UPDATE herbal.herbs SET synonyms = ARRAY['Du Zhong','Chinese Rubber Tree','Eucommia Bark'] WHERE latin_name = 'Eucommia ulmoides';
UPDATE herbal.herbs SET synonyms = ARRAY['Garden Nasturtium','Indian Cress'] WHERE latin_name = 'Tropaeolum majus';
UPDATE herbal.herbs SET synonyms = ARRAY['California Spikenard','Aralia'] WHERE latin_name = 'Aralia californica';
UPDATE herbal.herbs SET synonyms = ARRAY['Japanese Angelica','Aralia'] WHERE latin_name = 'Aralia elata';
UPDATE herbal.herbs SET synonyms = ARRAY['Sweet Basil','Common Basil'] WHERE latin_name = 'Ocimum basilicum';
UPDATE herbal.herbs SET synonyms = ARRAY['Maral','Rhaponticum','Ecdysterone Plant'] WHERE latin_name = 'Leuzea carthamoides';
UPDATE herbal.herbs SET synonyms = ARRAY['Manzanita Berry'] WHERE latin_name = 'Arctostaphylos manzanita';
UPDATE herbal.herbs SET synonyms = ARRAY['Black Mustard Seed'] WHERE latin_name = 'Brassica nigra';
UPDATE herbal.herbs SET synonyms = ARRAY['Wild Mustard','Brown Mustard','Yellow Mustard'] WHERE latin_name = 'Brassica spp.';
UPDATE herbal.herbs SET synonyms = ARRAY['Solomon''s Seal','Wild Solomon''s Seal'] WHERE latin_name = 'Polygonatum biflorum';
UPDATE herbal.herbs SET synonyms = ARRAY['Oplopanax','Siberian Devil''s Club'] WHERE latin_name = 'Oplopanax elatus';

DO $$ BEGIN
  RAISE NOTICE 'Migration 192 complete: synonyms column added and populated for all herbs.';
END $$;
