-- Migration 193: Flower Essence Repertory data
-- Source: Flower Essence Repertory - Cleaned.txt
-- Tables: flower_essence_plants, flower_essence_condition_entries,
--         flower_essence_category_see_also
-- Generated by scripts/import_flower_essences.py

SET search_path TO herbal, public;

-- ============================================================
-- Table: flower_essence_plants (Part Two profiles)
-- ============================================================

CREATE TABLE IF NOT EXISTS herbal.flower_essence_plants (
  id                    SERIAL PRIMARY KEY,
  name                  TEXT NOT NULL,
  latin_name            TEXT,
  color                 TEXT,
  kit                   TEXT,
  positive_qualities    TEXT,
  patterns_of_imbalance TEXT,
  description           TEXT,
  cross_references      TEXT[] DEFAULT ARRAY[]::TEXT[],
  UNIQUE (name, latin_name)
);

GRANT ALL ON TABLE herbal.flower_essence_plants
  TO postgres, anon, authenticated, service_role;
GRANT ALL ON SEQUENCE herbal.flower_essence_plants_id_seq
  TO postgres, anon, authenticated, service_role;
ALTER TABLE herbal.flower_essence_plants ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='herbal' AND tablename='flower_essence_plants'
      AND policyname='anon_read'
  ) THEN
    CREATE POLICY "anon_read" ON herbal.flower_essence_plants
      FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='herbal' AND tablename='flower_essence_plants'
      AND policyname='service_write'
  ) THEN
    CREATE POLICY "service_write" ON herbal.flower_essence_plants
      FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ============================================================
-- Table: flower_essence_condition_entries (Part One)
-- ============================================================

CREATE TABLE IF NOT EXISTS herbal.flower_essence_condition_entries (
  id          SERIAL PRIMARY KEY,
  category    TEXT NOT NULL,
  plant_name  TEXT NOT NULL,
  plant_id    INTEGER REFERENCES herbal.flower_essence_plants(id),
  description TEXT,
  UNIQUE (category, plant_name)
);

CREATE INDEX IF NOT EXISTS idx_fece_category
  ON herbal.flower_essence_condition_entries(category);
CREATE INDEX IF NOT EXISTS idx_fece_plant_id
  ON herbal.flower_essence_condition_entries(plant_id);

GRANT ALL ON TABLE herbal.flower_essence_condition_entries
  TO postgres, anon, authenticated, service_role;
GRANT ALL ON SEQUENCE herbal.flower_essence_condition_entries_id_seq
  TO postgres, anon, authenticated, service_role;
ALTER TABLE herbal.flower_essence_condition_entries ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='herbal' AND tablename='flower_essence_condition_entries'
      AND policyname='anon_read'
  ) THEN
    CREATE POLICY "anon_read" ON herbal.flower_essence_condition_entries
      FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='herbal' AND tablename='flower_essence_condition_entries'
      AND policyname='service_write'
  ) THEN
    CREATE POLICY "service_write" ON herbal.flower_essence_condition_entries
      FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ============================================================
-- Table: flower_essence_category_see_also (Part One See Also)
-- ============================================================

CREATE TABLE IF NOT EXISTS herbal.flower_essence_category_see_also (
  from_category TEXT NOT NULL,
  to_category   TEXT NOT NULL,
  PRIMARY KEY (from_category, to_category)
);

CREATE INDEX IF NOT EXISTS idx_fecsa_from
  ON herbal.flower_essence_category_see_also(from_category);
CREATE INDEX IF NOT EXISTS idx_fecsa_to
  ON herbal.flower_essence_category_see_also(to_category);

GRANT ALL ON TABLE herbal.flower_essence_category_see_also
  TO postgres, anon, authenticated, service_role;
ALTER TABLE herbal.flower_essence_category_see_also ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='herbal' AND tablename='flower_essence_category_see_also'
      AND policyname='anon_read'
  ) THEN
    CREATE POLICY "anon_read" ON herbal.flower_essence_category_see_also
      FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='herbal' AND tablename='flower_essence_category_see_also'
      AND policyname='service_write'
  ) THEN
    CREATE POLICY "service_write" ON herbal.flower_essence_category_see_also
      FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;

