-- Migration 295: Class 65 quiz — Fertility and Pregnancy
-- 30 MCQ questions derived from class note snippets

SET search_path TO herbal, public;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM herbal.class_quiz_questions
    WHERE class_name = 'BHC - Class 65 - Fertility and Pregnancy'
  ) THEN
    RAISE NOTICE 'Class 65 quiz questions already loaded, skipping';
    RETURN;
  END IF;

  INSERT INTO herbal.class_quiz_questions
    (class_name, question_text, option_a, option_b, option_c, option_d,
     correct_option, explanation, snippet_text, section_header, sort_order)
  VALUES

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Dong Quai and Vitex are rotated bi-weekly for hormone balance. Which phase does Dong Quai support?',
   'Luteal phase — progesterone building',
   'Follicular phase — anabolic, building, and circulation stimulating',
   'Menstrual phase — hemostatic and tonifying',
   'Ovulatory phase — pituitary stimulating',
   'b',
   'The notes describe Dong Quai as anabolic, building, and circulation stimulating, used for 2 weeks in the follicular phase before rotating to Vitex.',
   'Dong Quai (anabolic, building + circ stim), 2 weeks, Vitex (more targets the pituitary as a dopamine agonist - sense of safety to promote ovulation - can then calm elevated prolactin levels), 2 weeks, rotate',
   'Hormone Balance', 10),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Which herb acts as a dopamine agonist targeting the pituitary to promote ovulation and calm elevated prolactin?',
   'Dong Quai',
   'Sage',
   'Vitex',
   'Licorice',
   'c',
   'Vitex is described as targeting the pituitary as a dopamine agonist, creating a sense of safety to promote ovulation, and calming elevated prolactin levels.',
   'Vitex (more targets the pituitary as a dopamine agonist - sense of safety to promote ovulation - can then calm elevated prolactin levels), 2 weeks, rotate',
   'Hormone Balance', 20),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'For threatened miscarriage, what is the recommended ratio of Cramp Bark to Wild Yam?',
   '1 part Cramp Bark to 2 parts Wild Yam',
   '1 part Cramp Bark to 1 part Wild Yam',
   '2 parts Cramp Bark to 1 part Wild Yam',
   '3 parts Cramp Bark to 1 part Wild Yam',
   'c',
   'The notes specify 2 parts Cramp Bark to 1 part Wild Yam for the threatened miscarriage antispasmodic formula.',
   '2p Cramp Bark / 1p Wild Yam / 1/2 - 1 tsp every 30-60 mins for up to 4 hours',
   'Threatened Miscarriage', 30),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'What is the dosing schedule for the Cramp Bark + Wild Yam threatened miscarriage formula?',
   '1 tsp every 4 hours for up to 2 days',
   '1/2–1 tsp every 30–60 min for up to 4 hours; repeat up to 2x/day for up to 3 days',
   '2 tsp every 2 hours for up to 6 hours',
   '1 tsp every hour around the clock until symptoms resolve',
   'b',
   'The notes give a specific protocol: 1/2–1 tsp every 30–60 min for up to 4 hours, repeated up to 2x/day for up to 3 days.',
   '1/2 - 1 tsp every 30-60 mins for up to 4 hours / depends on severity of the symptoms / repeat up to 2x in a day for up to 3 days',
   'Threatened Miscarriage', 40),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Which herb is described as specific for drying up lactation after pregnancy loss?',
   'Red Raspberry',
   'Chamomile',
   'Yarrow',
   'Sage',
   'd',
   'The notes state "Sage = specific for drying up the lactation" in the context of pregnancy loss recovery.',
   'Sage = specific for drying up the lactation',
   'Pregnancy Loss', 50),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Why should Red Raspberry be avoided in miscarriage-prone patients?',
   'It is an emmenagogue that stimulates the pituitary',
   'Its astringency can tighten the uterus',
   'It reduces progesterone levels',
   'It contains phytoestrogens that disrupt implantation',
   'b',
   'The notes explicitly state to "very much avoid Red Raspberry — astringency can tighten the uterus" for miscarriage-prone patients.',
   'very much avoid Red Raspberry - astringency can tighten the uterus',
   'Materia Medica', 60),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Which condition does Ligusticum wallichii address in PCOS treatment?',
   'Elevated prolactin and anovulation',
   'Elevated testosterone and hirsutism',
   'Blood and yin deficiency with uterine undernourishment',
   'Insulin resistance and fat metabolism',
   'c',
   'The notes describe Ligusticum wallichii as a blood and yin tonic that nourishes the uterus, used in PCOS treatments.',
   'Ligusticum wallichii — blood and yin tonic / nourishes uterus',
   'Fertility Support', 70),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Which herb should be preferred over Cramp Bark when a pregnant patient also has high blood pressure?',
   'Wild Yam',
   'Black Cohosh',
   'Black Haw',
   'Hawthorn',
   'c',
   'The notes state "Black Haw if high BP issues as well" and "Black Haw — first choice over Cramp Bark" for hypertension in pregnancy.',
   'Black Haw if high BP issues as well / Black Haw — first choice over Cramp Bark',
   'Materia Medica', 80),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Reishi is used for hypertension in pregnancy. How should it be administered during pregnancy?',
   'As a standardised extract capsule for precise dosing',
   'As a tincture combined with Hawthorn',
   'As food (not powders), since mushrooms can be hard on the liver',
   'As a daily adaptogenic tea blend',
   'c',
   'The notes specify to use Reishi "just as food, not powders, during pregnancies — mushrooms can be a little hard on the liver to process."',
   'use just as food, not powders, during pregnancies — mushrooms can be a little hard on the liver to process',
   'Blood Pressure in Pregnancy', 90),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'In the Iron Tonic Syrup recipe, what volume of molasses is used?',
   '1 cup',
   '1/2 cup',
   '3 cups',
   '2 cups',
   'd',
   'The Iron Tonic Syrup recipe specifies 2 cups of molasses.',
   '- 4 T dried nettle / - 3 T alfalfa / - 2 T raspberry leaf / - 1 T dried yellow dock / - 1 T hawthorn berries / - 1 T goji berries / - 1 tsp rose hips / - 1/2 c dried apricots / - 2 c molasses / - 1 c organic pomegranate or black cherry concentrate (not juice)',
   'Iron Tonic Syrup', 100),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'What does Astragalus contribute to fertility support according to Lisa''s notes?',
   'Suppresses prolactin and supports progesterone production',
   'Supports sperm motility and semen quality; contains isoflavones and saponin triterpenes for hormone modulation',
   'Reduces elevated testosterone and restores menses',
   'Blood and yin tonic that nourishes the uterus',
   'b',
   'Lisa''s notes state Astragalus "supports sperm motility and semen quality / isoflavones + saponin triterpens (hormone mod)".',
   'Astragalus — supports sperm motility and semen quality / isofalvones + saponin triterpens (hormone mod)',
   'Fertility Tea', 110),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Which herb suppresses prolactin levels and is listed among PCOS treatments in the generated notes?',
   'Vitex',
   'Licorice',
   'Salvia officinalis (Sage)',
   'Saw Palmetto',
   'c',
   'The generated notes list "Salvia officinalis: suppresses prolactin" in the PCOS treatments section.',
   'Salvia officinalis: suppresses prolactin',
   'Fertility Support', 120),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Red Clover''s significant phytoestrogenic capacity means it should be avoided in which conditions?',
   'Amenorrhea, hypothyroidism, and adrenal fatigue',
   'Ovarian cancer, estrogen-responsive cancers, and endometrial hyperplasia',
   'PCOS, hyperprolactinemia, and anovulatory cycles',
   'Iron deficiency, anemia, and heavy bleeding',
   'b',
   'The notes specify avoiding Red Clover in "ovarian cancer, estrogen-responsive cancers, endometrial hyperplasia" due to significant phytoestrogenic capacity.',
   'Red Clover — Significant phytoestrogen capacity — Avoid in hyperestrogenic conditions: Ovarian cancer / Estrogen-responsive cancers / Endometrial hyperplasia',
   'Benefits and Actions', 130),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'White Peony (Paeonia lactiflora) has which of the following properties?',
   'Diuretic, lymphatic, and antifungal',
   'Emmenagogue, thermogenic, and prolactin-suppressing',
   'Blood and yin tonic, mast cell stabilizing, calms fibroblast production',
   'Smooth muscle antispasmodic, adaptogenic, and phytoestrogenic',
   'c',
   'Lisa''s notes describe White Peony as "blood and yin tonic / mast cell stabilizing / calms fibroblast production."',
   'Paeonia lactiflora / White Peony / blood and yin tonic / mast cell stabilizing / calms fibroblast production',
   'Materia Medica', 140),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Licorice is described as reducing which two hormones in fertility/PCOS treatment?',
   'FSH and LH',
   'Estrogen and progesterone',
   'Testosterone and prolactin',
   'Cortisol and adrenaline',
   'c',
   'The notes state Licorice "reduces testosterone and prolactin levels / reduce elevated testosterone and restore menses."',
   'Licorice — reduces testosterone and prolactin levels / reduce elevated testosterone and restore menses',
   'Fertility Tea', 150),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'For constipation in pregnancy, what is the correct escalation order from gentlest to strongest?',
   'Yellow dock → dandelion root → marshmallow root',
   'Dandelion root → marshmallow root → yellow dock',
   'Marshmallow root → dandelion root → yellow dock',
   'Yellow dock → marshmallow root → dandelion root',
   'c',
   'Lisa''s notes give the order: "marshmallow root — dandelion root — finally, escalate to here: yellow dock."',
   'marshmallow root - nourishing and moistening the bowel / dandelion root - escalate to here / yellow dock - finally, escalate to here',
   'Digestive Support', 160),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Why is Panax ginseng used cautiously in fertility patients who are not well-nourished?',
   'It suppresses ovulation in depleted individuals',
   'It can lead to burnout and a nervous system wound too tight or jumpy',
   'It raises prolactin levels in the short term',
   'It is phytoestrogenic and can disrupt hormonal cycling',
   'b',
   'The notes state ginseng should be avoided "if not well-nourished — can lead to burnout / nervous system response: wound too tight, jumpy."',
   'Panax ginseng — qi tonic / caution: avoid if not well-nourished / can lead to burnout / nervous system response: wound too tight, jumpy',
   'Fertility Support', 170),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Which herb is described as safe and penetrating to the tissues for immune support during pregnancy?',
   'Echinacea',
   'Astragalus',
   'Usnea',
   'Reishi',
   'c',
   'Lisa''s notes describe Usnea as "safe and penetrating to the tissues" for immune support in pregnancy.',
   'usnea — safe and penetrating to the tissues',
   'Immune Support', 180),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Inositol found in legumes is described as an alternative treatment to which pharmaceutical for PCOS?',
   'Metformin',
   'Clomiphene',
   'Spironolactone',
   'Letrozole',
   'c',
   'The generated notes state inositol is "alternative treatment to spironolactone" for reducing elevated testosterone.',
   'Inositol — Reduces elevated testosterone / Restores menses / Alternative treatment to spironolactone',
   'Benefits and Actions', 190),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'For morning sickness, what preparatory method does the class recommend before reaching for herbs?',
   'A small glass of ginger juice before bed',
   'A snack kept by the bed to eat before getting up',
   'Peppermint steam inhalation in the morning',
   'Chamomile tea sipped throughout the night',
   'b',
   'Lisa''s notes state: "effective to have a snack right by the bed, for when wake up — can interrupt this morning sickness cycle."',
   'effective to have a snack right by the bed, for when wake up / can interrupt this morning sickness cycle',
   'Nausea and Vomiting', 200),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Wild yam is described as what type of agent in the context of pregnancy care?',
   'Phytoestrogen and hormonal modulator',
   'Autonomic nerve relaxant and smooth muscle antispasmodic',
   'Diuretic and renal tonic',
   'Galactagogue and uterine tonic',
   'b',
   'Lisa''s notes identify Wild Yam as "autonomic nerve relaxant, specifically for GI symptoms" and the generated notes call it a "smooth muscle antispasmodic."',
   'Wild Yam — smooth muscle antispasmodic / useful if history of pregnancy loss',
   'Headaches and Cramps', 210),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'What does Chamomile bind to in the nervous system, making it useful for anxiety during pregnancy?',
   'Opioid receptors',
   'Serotonin receptors',
   'GABA receptors',
   'Dopamine receptors',
   'c',
   'The generated notes state Chamomile "binds to GABA receptors for anxiety."',
   'Chamomile — calming, anti-inflammatory / binds to GABA receptors for anxiety',
   'Headaches and Cramps', 220),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Echinacea is considered safe in pregnancy, but which part of the plant should be avoided?',
   'The flowers',
   'The leaves',
   'The roots',
   'The seeds',
   'c',
   'The generated notes state: "Echinacea — safe during pregnancy — avoid roots, prefer nourishing broths."',
   'Echinacea — safe during pregnancy / supports immune system / avoid roots, prefer nourishing broths',
   'Immune Support', 230),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Calcium and iron should not be taken together. According to the notes, what does calcium do?',
   'Oxidises iron, rendering it inactive',
   'Blocks the absorption of iron',
   'Converts ferrous iron to ferric form, which is poorly absorbed',
   'Increases iron excretion through the kidneys',
   'b',
   'Lisa''s notes state "calcium blocks the absorption of iron."',
   'calcium blocks the absorption of iron',
   'Iron Tonic Syrup', 240),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Which herb in the fertility tea is described as cardioprotective and must be dried a rich green to be high quality?',
   'Astragalus',
   'Licorice',
   'Alfalfa',
   'Red Clover',
   'c',
   'Lisa''s notes describe Alfalfa as "cardioprotective / if it''s not dried rich green, it''s not the best."',
   'Alfalfa — highly nutritive / support hormone regulation and metabolism / rich in chlorophyll / cardioprotective / if it''s not dried rich green, it''s not the best',
   'Fertility Tea', 250),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'For sleep support during pregnancy, what rotation strategy is recommended?',
   'Combine all sleep herbs into a single formula for maximum effect',
   'Use the same herb nightly for consistency and tolerance-building',
   'Rotate to a different remedy as soon as the current one becomes less effective',
   'Use herbs only in the final trimester when sleep disruption is most severe',
   'c',
   'Lisa''s notes state: "unless you figure out the issue, your body will overcome the remedy — so rotate as soon as it''s not as effective."',
   'unless you figure out the issue, your body will overcome the remedy / so rotate as soon as it''s not as effective',
   'Sleep and Insomnia', 260),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Urtica (nettles) is recommended for which hormonal condition associated with anovulatory infertility?',
   'Low progesterone and luteal phase defect',
   'Elevated testosterone in PCOS/PMOS',
   'Elevated prolactin causing suppressed FSH and LH',
   'Low estrogen and premature ovarian insufficiency',
   'b',
   'Lisa''s notes state Urtica "helps with elevated testosterone / with the hormone regulation issues of PMOS."',
   'Urtica urens, U. dioica — nettles, if suspect anovulatory issues / help with elevated testosterone / with the hormone regulation issues of PMOS',
   'Materia Medica', 270),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Magnesium is cited for which serious pregnancy complication?',
   'Gestational diabetes',
   'Preeclamptic seizures',
   'Placental abruption',
   'Group B strep infection',
   'b',
   'The generated notes state "Magnesium for seizures, poorly understood condition" in the context of preeclampsia.',
   'Magnesium for seizures, poorly understood condition / Protein and magnesium preventative',
   'Blood Pressure in Pregnancy', 280),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Rose petal, calendula, and yarrow are cited for which postpartum use?',
   'Galactagogue support and milk letdown',
   'Postpartum depression and nervous system support',
   'Topical wound healing after tissue tears',
   'Iron restoration and anemia recovery',
   'c',
   'The generated notes list rose petal, calendula, and yarrow for healing in postpartum care, in the context of sitz baths and tissue repair.',
   'Use of rose petal, calendula, yarrow for healing',
   'Postpartum Care', 290),

  ('BHC - Class 65 - Fertility and Pregnancy',
   'Which herb in the fertility tea is noted to protect against oxidative stress and support sperm motility?',
   'Licorice',
   'Kudzu',
   'Astragalus',
   'Red Clover',
   'c',
   'Lisa''s notes specifically attribute "protects from oxidative stress" and "supports sperm motility and semen quality" to Astragalus.',
   'Astragalus — protects from oxidative stress / AI / circ stim / immune mod / supports sperm motility and semen quality',
   'Fertility Tea', 300);

END $$;
