-- Migration 312: BHC Class 36 - Constitution I — quiz questions (50 MCQ)
-- Source: migration 311 snippets for class_name 'BHC - Class 36 - Constitution I'
-- Sections: Cold, Dry, Hot, Wet, Thompson's, Upper GI, Lower GI, Liver,
--           Kidneys, Reproductive - Female, Reproductive - Male, Respiratory,
--           Cardiovascular, Lymph / Immune, Skin, Musculoskeletal

SET search_path TO herbal, public;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM herbal.class_quiz_questions
             WHERE class_name = 'BHC - Class 36 - Constitution I') THEN
    RAISE NOTICE 'Class 36 quiz already loaded, skipping';
    RETURN;
  END IF;

  INSERT INTO herbal.class_quiz_questions
    (class_name, question_text, option_a, option_b, option_c, option_d,
     correct_option, explanation, snippet_text, section_header, sort_order)
  VALUES

  -- Q1 — Cold: blood building
  ('BHC - Class 36 - Constitution I',
   'Which group of herbs is recommended as blood builders for a cold constitution?',
   'Nettles, Burdock, Cleavers, Astragalus',
   'Dong Quai, Ashwagandha, Lemon Balm, Alfalfa, White Peony, Licorice',
   'Rhodiola, Schisandra, Kava, Milky Oats',
   'Turmeric, Milk Thistle, Dandelion root, Sarsaparilla',
   'b',
   'Blood builders for the cold constitution are warming and nourishing: Dong Quai, Ashwagandha, Lemon Balm, Alfalfa, White Peony, and Licorice. Nettles is excluded because it is cooling and drying.',
   'Blood building herbs for cold constitution: Dong Quai, Ashwagandha, Lemon Balm, Alfalfa, White Peony, Licorice.',
   'Cold', 10),

  -- Q2 — Cold: Nettles NOT for cold
  ('BHC - Class 36 - Constitution I',
   'Why is Nettles NOT recommended for the cold constitution?',
   'It is too stimulating and can aggravate anxiety',
   'It is an anabolic stimulant contraindicated in deficiency states',
   'It is cooling and drying — the opposite of what a cold constitution needs',
   'It interferes with thyroid hormone metabolism',
   'c',
   'The class notes explicitly state Nettles is excluded from cold constitution blood builders because it is "cooling and drying" — directly counterproductive for a constitution that needs warmth and moisture.',
   'Nettles NOT recommended for cold constitution — cooling and drying.',
   'Cold', 20),

  -- Q3 — Cold: circ stimulants
  ('BHC - Class 36 - Constitution I',
   'Which herbs are listed as circulatory stimulants (blood AND lymph) for the cold constitution?',
   'Ginkgo, Hawthorn berry, Rosemary, Red Root',
   'Dong Quai, Prickly Ash, Cayenne, Poke root, Calendula, Ocotillo',
   'Wild Ginger, Ocotillo, Black Cohosh, Poke (little poke)',
   'Rhodiola, Eleuthero, Ashwagandha, Schisandra',
   'b',
   'The cold constitution circ stimulants (blood and lymph) listed are: Dong Quai, Prickly Ash, Cayenne, Poke root (lymph), Calendula (lymph), and Ocotillo (lymph). Option c is the female reproductive deficiency circ stimulant list.',
   'Circ stimulants (blood and lymph) for cold constitution: Dong Quai, Prickly Ash, Cayenne, Poke root (lymph), Calendula (lymph), Ocotillo (lymph).',
   'Cold', 30),

  -- Q4 — Cold: Tulsi
  ('BHC - Class 36 - Constitution I',
   'What are Tulsi''s (Holy Basil) listed actions for the cold constitution?',
   'Demulcent, anti-inflammatory, hepatic, lowers cholesterol',
   'Hormone balancer, tissue protective against microbes/toxins/stress, nourishes reproductive organs',
   'Circ stimulant, lymphagogue, bitter tonic, diaphoretic',
   'Adaptogen, HPA modulator, adrenal restorative, cortisol regulator',
   'b',
   'Tulsi for the cold constitution: hormone balancer, tissue protective in face of microbes/toxin/stress, nourishes reproductive organs.',
   'Tulsi (Holy Basil) for cold constitution: hormone balancer, tissue protective in face of microbes/toxin/stress, nourish to reproductive organs.',
   'Cold', 40),

  -- Q5 — Cold: Ginger — Hoffman vs Lisa perspective
  ('BHC - Class 36 - Constitution I',
   'Regarding Ginger for the cold constitution, David Hoffman and Lisa have different emphases. Which correctly distinguishes them?',
   'Hoffman: warms the lungs; Lisa: warms the digestive tract',
   'Hoffman: moves blood to extremities; Lisa: heat for internal organs',
   'Hoffman: stimulates bile secretion; Lisa: diaphoretic sweat response',
   'Hoffman: lymphatic action; Lisa: stimulates HPA axis',
   'b',
   'The notes state: "David Hoffman → blood to extremities; Lisa → heat for internal organs." Both agree Ginger stimulates the migrating motor complex and has big impacts on cold bodies.',
   'Ginger for cold constitution: heats up and stimulates the migrating motor complex of the small intestine; big impacts on cold bodies; warms internal organs (liver, lungs); David Hoffman → blood to extremities; Lisa → heat for internal organs.',
   'Cold', 50),

  -- Q6 — Cold: alteratives
  ('BHC - Class 36 - Constitution I',
   'The class notes recommend combining Marshmallow root (for cold constitution) with which herbs to make it more suitable?',
   'Turmeric and Black Pepper',
   'Licorice and Ashwagandha',
   'Cinnamon or Cardamom',
   'Ginger and Prickly Ash',
   'c',
   'The notes list alteratives for cold constitution as "Burdock, Slippery Elm, Marshmallow root with Cinnamon or Cardamom" — the warming spices counteract Marshmallow''s coolness for cold types.',
   'Alteratives for cold constitution: Burdock, Slippery Elm, Marshmallow root with Cinnamon or Cardamom. Cold body tends toward sluggish metabolism and bowel stagnation.',
   'Cold', 60),

  -- Q7 — Dry: Licorice spotlight
  ('BHC - Class 36 - Constitution I',
   'In the dry constitution section, Licorice is described as a "model adaptogen." Which of the following is NOT listed among its actions?',
   'Cortisol modulator supporting HPA dysregulation (adrenal fatigue)',
   'Supports anabolic activity (building tissue, muscle, baby)',
   'Stimulates diuresis and clears dampness from the lower burner',
   'Has influence on every body system and immune modulating',
   'c',
   'The notes describe Licorice as: model adaptogen, TCM harmonizer, addresses exhaustion and debility, improves insulin resistance, cortisol modulator, HPA support, immune modulating, supports anabolic activity, influence on every body system. Diuresis/clearing dampness is not listed — that is more a damp-drying action.',
   'Licorice for dry constitution: moistening adaptogen. Model adaptogen; in TCM almost in every formula as harmonizer; addresses exhaustion and debility; improves insulin resistance; cortisol modulator; supports HPA dysregulation (adrenal fatigue); immune modulating; supports anabolic activity (tissue, muscle, baby); influence on every body system.',
   'Dry', 70),

  -- Q8 — Dry: moistening adaptogens
  ('BHC - Class 36 - Constitution I',
   'Which adaptogens are specifically listed as moistening for the dry constitution?',
   'Rhodiola, Ashwagandha, Eleuthero',
   'Shatavari, Schisandra, Ginsengs, Licorice',
   'Tulsi, Reishi, Ginseng, Devil''s Club',
   'Milky Oats, Kava, Passionflower, Skullcap',
   'b',
   'The moistening adaptogens for dry constitution are: Shatavari, Schisandra, Ginsengs, Licorice. Option a includes Rhodiola and Eleuthero which are listed for the wet constitution.',
   'Moistening adaptogens for dry constitution: Shatavari, Schisandra, Ginsengs, Licorice.',
   'Dry', 80),

  -- Q9 — Dry: nervines
  ('BHC - Class 36 - Constitution I',
   'Which nervines are specifically recommended for the dry constitution?',
   'Passionflower and Skullcap',
   'Valerian and Hops',
   'Milky Oats and Kava',
   'St. John''s Wort and Motherwort',
   'c',
   'The notes list Milky Oats and Kava as nervines for the dry constitution. These are moistening nervines appropriate for the dry constitution''s anxiety and hyperactivity pattern.',
   'Milky Oats as nervine for dry constitution.',
   'Dry', 90),

  -- Q10 — Dry: demulcents
  ('BHC - Class 36 - Constitution I',
   'The demulcent herbs listed for the dry constitution are:',
   'Comfrey root, Licorice, Slippery Elm, Plantain',
   'Marshmallow, Slippery Elm, Cinnamon, Cardamom',
   'Aloe vera, Flaxseed, Psyllium, Shatavari',
   'Wild Yam, Licorice, Calendula, Violet',
   'b',
   'The demulcents listed for dry constitution are Marshmallow, Slippery Elm, Cinnamon, and Cardamom. The latter two serve dual roles as spices that add warmth while providing demulcent action.',
   'Marshmallow as demulcent for dry constitution: Marshmallow, Slippery Elm, Cinnamon, Cardamom.',
   'Dry', 100),

  -- Q11 — Dry: Nettles caveat
  ('BHC - Class 36 - Constitution I',
   'Nettles can be used for the dry constitution but with which important modification?',
   'Only use as a tea, never as a tincture — the alcohol is too drying',
   'Use together with moistening herbs like Lemon Balm',
   'Use only in spring when fresh plant is available',
   'Combine with demulcents and increase dietary fat intake',
   'b',
   'The notes say Nettles "can be drying — use together with moistening, e.g. Lemon Balm" for the dry constitution. This balances Nettles'' drying tendency with Lemon Balm''s moistening action.',
   'Nettles for dry constitution: can be drying — use together with moistening herbs like Lemon Balm.',
   'Dry', 110),

  -- Q12 — Hot: Black Cohosh spotlight
  ('BHC - Class 36 - Constitution I',
   'Black Cohosh is described in the hot constitution section as working via which mechanism for PMS and menopausal symptoms?',
   'Direct estrogen receptor agonism and aromatase inhibition',
   'Pituitary influence on serotonin production; serotonin agonist supporting estrogen balance and melatonin production',
   'Adrenal cortex stimulation increasing progesterone precursors',
   'Prostaglandin inhibition similar to NSAIDs, plus uterine relaxation',
   'b',
   'The notes state Black Cohosh "works via pituitary influence on serotonin production; serotonin agonist (estrogen balance); melatonin production." It is listed for PMS with muscle pain and insomnia, and the note suggests considering it before SSRIs.',
   'Black Cohosh: classic arthritis/fibromyalgia plant; extreme muscle tension; tension headaches; PMS with tight squeezing cramps; muscle tightness with menopause; associated with chronic pain and negative self-talk; serotonin agonist (estrogen balance); melatonin production; works via pituitary influence on serotonin production; PMS with muscle pain and insomnia; consider before resorting to SSRIs.',
   'Hot', 120),

  -- Q13 — Hot: liver alteratives
  ('BHC - Class 36 - Constitution I',
   'The liver alteratives for the hot constitution include all of the following EXCEPT:',
   'Dandelion root and Chicory',
   'Sarsaparilla and Sassafras',
   'Burdock and Slippery Elm',
   'Licorice and Astragalus',
   'c',
   'Liver alteratives for hot constitution are: Dandelion root, Chicory, Sarsaparilla, Sassafras, Licorice, Astragalus. Burdock and Slippery Elm are cold constitution alteratives — Burdock appears in wet constitution and Slippery Elm in cold.',
   'Liver alteratives for hot constitution: Dandelion root, Chicory, Sarsaparilla, Sassafras, Licorice, Astragalus.',
   'Hot', 130),

  -- Q14 — Hot: anti-inflammatories
  ('BHC - Class 36 - Constitution I',
   'Which two herbs are listed as anti-inflammatories for the hot constitution?',
   'Turmeric and Boswellia',
   'Echinacea and Astragalus',
   'St. John''s Wort and Willow',
   'Gentian and Artichoke leaf',
   'c',
   'The notes list St. John''s Wort (SJW) and Willow as the anti-inflammatory herbs for the hot constitution. Turmeric and Milk Thistle appear as hepatics, not AIs in this classification.',
   'Willow as anti-inflammatory for hot constitution.',
   'Hot', 140),

  -- Q15 — Hot: bitters
  ('BHC - Class 36 - Constitution I',
   'Which herb is described for the hot constitution as "hot-reducing, liver-supporting, alterative" and a bitter tonic?',
   'Gentian',
   'Artichoke leaf',
   'Oregon Grape Root',
   'Orange peel',
   'c',
   'The notes give Oregon Grape Root the three-part description: "hot-reducing, liver-supporting, alterative. Bitter tonic." — making it especially well-suited for hot types with liver congestion.',
   'Oregon Grape Root for hot constitution: hot-reducing, liver-supporting, alterative. Bitter tonic.',
   'Hot', 150),

  -- Q16 — Hot: lymph alteratives
  ('BHC - Class 36 - Constitution I',
   'The lymph alteratives listed for the hot constitution are:',
   'Poke, Queen''s Delight, Yerba Mansa',
   'Red Root, Cleavers, Calendula',
   'Ocotillo, Red Root, Baptisia',
   'Echinacea, Thuja, Astragalus',
   'b',
   'For the hot constitution, lymph alteratives are Red Root, Cleavers, and Calendula. Echinacea is listed separately as an alterative. Options a and c mix in lymph/immune section herbs.',
   'Lymph alteratives for hot constitution: Red Root, Cleavers, Calendula.',
   'Hot', 160),

  -- Q17 — Wet: Reishi spotlight
  ('BHC - Class 36 - Constitution I',
   'Reishi is highlighted in the wet constitution section because it helps with metabolic syndrome. Which environmental chemicals does it specifically help the body metabolize?',
   'Heavy metals (lead, mercury, arsenic)',
   'BPA and triclosan',
   'Pesticides (glyphosate, organophosphates)',
   'Excess estrogens and xenoestrogens',
   'b',
   'The notes specifically state Reishi "helps metabolize BPA and triclosan" alongside its role in metabolizing cortisol when stuck in overdrive — relevant to wet metabolic syndrome.',
   'Reishi Mushroom: protects against oxidative stress; adrenal and thyroid imbalance; wet as metabolic syndrome (aging changes — elevated lipids, weight gain, ankle swelling, visceral fat); helps body metabolize cortisol when stuck in overdrive; helps metabolize BPA and triclosan.',
   'Wet', 170),

  -- Q18 — Wet: waste-eliminating alteratives
  ('BHC - Class 36 - Constitution I',
   'The waste-eliminating alteratives for the wet constitution are:',
   'Burdock, Dandelion root, Sarsaparilla, Baptisia (Wild Indigo)',
   'Red Root, Cleavers, Calendula, Echinacea',
   'Burdock, Cleavers, Yellow Dock, Iris (Blue Flag)',
   'Dandelion root, Artichoke leaf, Turmeric, Milk Thistle',
   'a',
   'The wet constitution waste-eliminating alteratives are Burdock, Dandelion root, Sarsaparilla, and Baptisia (Wild Indigo). These move waste out rather than just stimulating secretions.',
   'Alteratives (waste eliminating) for wet constitution: Burdock, Dandelion root, Sarsaparilla, Baptisia (Wild Indigo).',
   'Wet', 180),

  -- Q19 — Wet: adaptogen caveat
  ('BHC - Class 36 - Constitution I',
   'Which adaptogen is listed for the wet constitution but with the important caveat that it should NOT be used if the person is both hot AND wet?',
   'Rhodiola',
   'Schisandra berry',
   'Ashwagandha',
   'Eleuthero',
   'c',
   'The notes list adaptogens for wet constitution as "Rhodiola, Ashwagandha (as long as not hot/wet), Schisandra berry." Ashwagandha is warming, so it would be contraindicated in the hot/wet combination.',
   'Adaptogens for wet constitution: Rhodiola, Ashwagandha (not if hot/wet), Schisandra berry.',
   'Wet', 190),

  -- Q20 — Wet: circ stimulants
  ('BHC - Class 36 - Constitution I',
   'Circulatory stimulants for the wet constitution include all of the following EXCEPT:',
   'Hawthorn berry and Rosemary',
   'Ginkgo and Ginger',
   'Wild Ginger and Ocotillo',
   'Prickly Ash and Red Root',
   'c',
   'The wet constitution circ stimulants are: Ginger, Prickly Ash, Red Root, Hawthorn berry, Rosemary, Ginkgo. Wild Ginger and Ocotillo appear in the female reproductive deficiency circ stimulant list, not the wet constitution list.',
   'Circ stimulants for wet constitution: Ginger, Prickly Ash, Red Root, Hawthorn berry, Rosemary, Ginkgo.',
   'Wet', 200),

  -- Q21 — Thompson's: Lobelia role
  ('BHC - Class 36 - Constitution I',
   'In Thompson''s Standard Protocol, what is Lobelia''s specific role?',
   'Stoke the fire — increase metabolic rate',
   'Stimulate digestion: purging → elimination of waste',
   'Gentle removal of waste via berberine action',
   'Enhance digestive secretions (bile and enzymes)',
   'b',
   'In Thompson''s protocol: Lobelia = stimulate digestion (purging → elimination of waste), Cayenne = stoke the fire, Bayberry = gentle removal of waste, Barberry = enhance digestive secretions, Myrrh = restorative.',
   'Thompson''s Standard Protocol: Lobelia — stimulate digestion: purging → elimination of waste.',
   'Thompson''s Standard Protocol', 210),

  -- Q22 — Thompson's: Bayberry vs Barberry
  ('BHC - Class 36 - Constitution I',
   'In Thompson''s Standard Protocol, what distinguishes Bayberry from Barberry?',
   'Bayberry enhances digestive secretions; Barberry provides gentle removal of waste via berberine',
   'Bayberry provides gentle removal of waste via berberine; Barberry enhances digestive secretions',
   'Bayberry is the restorative; Barberry stookes the fire',
   'Bayberry and Barberry have the same role — interchangeable in the protocol',
   'b',
   'Bayberry (myrica) = berberine, more gentle removal of waste. Barberry = enhance digestive secretions. They are distinct roles even though both are berberine-containing plants.',
   'Thompson''s Standard Protocol: Bayberry (myrica) — berberine, more gentle removal of waste.',
   'Thompson''s Standard Protocol', 220),

  -- Q23 — Thompson's: Myrrh role
  ('BHC - Class 36 - Constitution I',
   'In Thompson''s Standard Protocol, Myrrh resin (used with cherry pits) serves which function?',
   'Stimulate bile flow and portal circulation',
   'Antimicrobial to clear gut pathogens',
   'Restorative',
   'Diaphoretic to open skin elimination',
   'c',
   'The protocol assigns Myrrh resin (with cherry pits) the restorative role — the final step after the purging, firing, and waste-removal steps.',
   'Thompson''s Standard Protocol: Myrrh resin (with cherry pits) — restorative.',
   'Thompson''s Standard Protocol', 230),

  -- Q24 — Upper GI deficiency: berberine plants
  ('BHC - Class 36 - Constitution I',
   'For Upper GI deficiency, which berberine-containing plants are used to stimulate secretions?',
   'Barberry, Dandelion root, Yellow Dock, Turmeric',
   'Oregon Grape Root, Barberry, Gentian, Bogbean',
   'Blue Flag, Milk Thistle, Poke, Yellow Dock',
   'Bayberry, Goldenseal, Coptis, Phellodendron',
   'b',
   'Upper GI deficiency berberine plants: Oregon Grape Root, Barberry, Gentian, and Bogbean. These stimulate digestive secretions when there is insufficient bile and liver function.',
   'Upper GI deficiency: stimulate secretions with berberine plants — Oregon Grape Root, Barberry, Gentian, Bogbean.',
   'Upper GI', 240),

  -- Q25 — Upper GI excess with pain
  ('BHC - Class 36 - Constitution I',
   'For Upper GI excess with pain, which antispasmodics are recommended?',
   'Cramp Bark, Black Haw, Valerian, Passionflower',
   'Wild Yam, Fennel, Hops, Catnip, Silk Tassel',
   'Lobelia, Skullcap, Kava, Jamaican Dogwood',
   'Marshmallow, Comfrey root, Licorice, Aloe',
   'b',
   'The antispasmodics for Upper GI excess with pain are: Wild Yam, Fennel, Hops, Catnip, and Silk Tassel. Option d is the demulcent list for Upper GI excess (without pain).',
   'Upper GI excess with pain: antispasmodics — Wild Yam, Fennel, Hops, Catnip, Silk Tassel.',
   'Upper GI', 250),

  -- Q26 — Upper GI deficiency: functional stimulants
  ('BHC - Class 36 - Constitution I',
   'Which herbs serve as functional stimulants for Upper GI deficiency (distinct from berberine plants)?',
   'Licorice, Slippery Elm, Marshmallow, Wild Yam',
   'Cayenne, Angelica, Prickly Ash, Ginseng',
   'Ginger, Turmeric, Artichoke leaf, Gentian',
   'Fennel, Cardamom, Cinnamon, Chamomile',
   'b',
   'Functional stimulants for Upper GI deficiency: Cayenne, Angelica, Prickly Ash, and Ginseng — they stimulate overall digestive function rather than secretions specifically.',
   'Upper GI deficiency: functional stimulants — Cayenne, Angelica, Prickly Ash, Ginseng.',
   'Upper GI', 260),

  -- Q27 — Lower GI: Cinnamon
  ('BHC - Class 36 - Constitution I',
   'Cinnamon is unique in the Lower GI section because:',
   'It is the only herb that works via the enteric nervous system',
   'It is good for both Lower GI deficiency (peristalsis) and excess (soft stools)',
   'It combines berberine and demulcent actions simultaneously',
   'It is contraindicated in hot constitution and only for cold/dry types',
   'b',
   'The notes explicitly state: "Cinnamon (good for both deficiency and excess)" — it is listed in both the constipative/dry deficiency group AND the excess group, making it unusually versatile.',
   'Lower GI: Cinnamon good for both deficiency and excess.',
   'Lower GI', 270),

  -- Q28 — Lower GI excess
  ('BHC - Class 36 - Constitution I',
   'For Lower GI excess (soft stools, fermentation in gut), which herbs are recommended?',
   'Slippery Elm, Marshmallow, Licorice, Comfrey',
   'Ocotillo, Fringetree, Yellow Dock, Cinnamon',
   'Bugleweed, Silk Tassel, Bayberry, Turkey rhubarb (rhubarb root)',
   'Gentian, Bogbean, Barberry, Cayenne',
   'c',
   'Lower GI excess herbs: Bugleweed/Lycopis, Silk Tassel, Bayberry, and Turkey rhubarb (rhubarb root). Plus Cinnamon which works for both. Option b is the congestive deficiency list.',
   'Lower GI excess: Bugleweed/Lycopis, Silk Tassel, Bayberry, Turkey rhubarb (rhubarb root).',
   'Lower GI', 280),

  -- Q29 — Lower GI congestive deficiency
  ('BHC - Class 36 - Constitution I',
   'For Lower GI deficiency due to congestive stagnation (rather than dryness), which herbs are indicated?',
   'Bogbean, Cinnamon, Licorice, Yellow Dock',
   'Ocotillo, Fringetree, Yellow Dock',
   'Bugleweed, Silk Tassel, Bayberry',
   'Burdock, Dandelion root, Red Root',
   'b',
   'Congestive/stagnation type Lower GI deficiency uses Ocotillo, Fringetree, and Yellow Dock — these address stagnation rather than dryness. Option a is the constipative/dry deficiency group.',
   'Lower GI deficiency (congestive/stagnation type): stimulate — Ocotillo, Fringetree, Yellow Dock.',
   'Lower GI', 290),

  -- Q30 — Liver deficiency: berberine plants
  ('BHC - Class 36 - Constitution I',
   'Which berberine plants are used for liver deficiency to stimulate liver metabolism?',
   'Barberry, Oregon Grape Root, Bogbean',
   'Blue Flag (Iris all spp.), Milk Thistle, Poke (extreme cases only)',
   'Dandelion root, Mugwort, Artichoke leaf',
   'Yellow Dock, Burdock, Bugleweed',
   'b',
   'Liver deficiency berberine plants: Blue Flag (Iris all spp.), Milk Thistle, and Poke (used only in extreme cases or as a small part of the formula).',
   'Liver deficiency: stimulate liver metabolism with berberine plants — Blue Flag (Iris all spp.), Milk Thistle, Poke (extreme cases).',
   'Liver', 300),

  -- Q31 — Liver excess: anabolic coolers
  ('BHC - Class 36 - Constitution I',
   'To cool the anabolic tendency in liver excess, which herbs are used?',
   'Red Clover, Alfalfa, Lemon Balm, Nettles',
   'Dandelion root and Mugwort',
   'Burdock, Bugleweed, Milk Thistle, Devil''s Club',
   'Prickly Ash, Ginkgo, Hawthorn',
   'c',
   'To cool liver excess anabolic tendency: Burdock, Bugleweed, Milk Thistle, and Devil''s Club. Note Milk Thistle appears in BOTH liver deficiency (berberine) and liver excess (anabolic cooler). Option a is the mineral-rich blood buffers for liver excess.',
   'Liver excess: cool the anabolic tendency — Burdock, Bugleweed, Milk Thistle, Devil''s Club.',
   'Liver', 310),

  -- Q32 — Liver excess: mineral-rich herbs
  ('BHC - Class 36 - Constitution I',
   'For liver excess, mineral-rich herbs are used to buffer the blood. These are:',
   'Ashwagandha, Shatavari, White Peony, Dong Quai',
   'Red Clover, Red Raspberry leaf, Alfalfa, Lemon Balm, Nettles',
   'Dandelion root, Burdock root, Nettles, Yellow Dock',
   'Tulsi, Oat straw, Horsetail, Nettle seed',
   'b',
   'For liver excess, mineral-rich herbs to buffer blood: Red Clover, Red Raspberry leaf, Alfalfa, Lemon Balm, and Nettles. These are high-mineral herbs that reduce anabolic excess.',
   'Liver excess: mineral-rich herbs to buffer blood — Red Clover, Red Raspberry leaf, Alfalfa, Lemon Balm, Nettles.',
   'Liver', 320),

  -- Q33 — Liver excess: bile stimulants
  ('BHC - Class 36 - Constitution I',
   'Which herbs stimulate bile secretion for liver excess WITHOUT stimulating liver metabolism?',
   'Blue Flag (Iris) and Poke',
   'Burdock and Bugleweed',
   'Dandelion root and Mugwort (Artemisia vulgaris)',
   'Milk Thistle and Yellow Dock',
   'c',
   'Dandelion root and Mugwort stimulate bile secretion without stimulating liver metabolism — an important distinction from Blue Flag and Milk Thistle, which do stimulate liver metabolism.',
   'Liver excess: Dandelion root to stimulate bile secretion without stimulating liver metabolism.',
   'Liver', 330),

  -- Q34 — Kidneys deficiency: Dong Quai
  ('BHC - Class 36 - Constitution I',
   'In the kidney deficiency section, what is Dong Quai''s specific mechanism?',
   'Stimulates nephrons directly and increases GFR',
   'Improves renal blood supply and hormonal stimulation',
   'Acts as an aldosterone antagonist to prevent sodium retention',
   'Diuretic that clears excess uric acid from the kidneys',
   'b',
   'For kidney deficiency, Dong Quai''s role is to "improve renal blood supply and hormonal stimulation" — distinct from Horsetail (stimulates nephrons) and Licorice/Ginsengs (adrenal/hormonal support).',
   'Kidney deficiency: Dong Quai to improve renal blood supply and hormonal stimulation.',
   'Kidneys', 340),

  -- Q35 — Kidneys excess: Blue Flag
  ('BHC - Class 36 - Constitution I',
   'In kidney excess (holding salt and water), Blue Flag (Iris) serves as what type of agent?',
   'Lymphagogue to drain interstitial fluid',
   'Diuretic cooler via direct tubular action',
   'Metabolic cooler / diuretic cooler to dilate renal arteries',
   'Aldosterone modulator to reduce sodium retention',
   'c',
   'Blue Flag (Iris) for kidney excess is described as a "metabolic cooler / diuretic cooler" to dilate renal arteries. It heads the kidney excess list.',
   'Kidney excess: Blue Flag (Iris) as metabolic cooler to dilate renal arteries.',
   'Kidneys', 350),

  -- Q36 — Repro Female deficiency: anabolic stimulants
  ('BHC - Class 36 - Constitution I',
   'The anabolic stimulants for female reproductive deficiency are:',
   'Motherwort, Damiana, Vitex, Anemone (Pasqueflower)',
   'Wild Ginger, Ocotillo, Black Cohosh, Poke',
   'Dong Quai, Blue Cohosh, Licorice, White Peony, Ginsengs',
   'Wild Yam, Yellow Pond Lily, Trillium, Black Haw, Cramp Bark',
   'c',
   'Female reproductive deficiency anabolic stimulants: Dong Quai, Blue Cohosh, Licorice, White Peony, Ginsengs. Option a is the HPA stimulant list; option b is the circ stimulant list; option d is the excess cooling list.',
   'Female reproductive deficiency: anabolic stimulants — Dong Quai, Blue Cohosh, Licorice, White Peony, Ginsengs.',
   'Reproductive - Female', 360),

  -- Q37 — Repro Female deficiency: HPA stimulants
  ('BHC - Class 36 - Constitution I',
   'For female reproductive deficiency, which herbs stimulate the HPA axis?',
   'Dong Quai, Blue Cohosh, Licorice, White Peony',
   'Wild Ginger, Ocotillo, Black Cohosh, Poke',
   'Motherwort, Damiana, Vitex, Anemone (Pasqueflower)',
   'Astragalus, Echinacea, Thuja, Myrrh',
   'c',
   'HPA stimulants for female reproductive deficiency: Motherwort, Damiana, Vitex, and Anemone (Pasqueflower). These improve the pituitary-ovarian-adrenal communication central to hormonal health.',
   'Female reproductive deficiency: Anemone (Pasqueflower) to stimulate HPA.',
   'Reproductive - Female', 370),

  -- Q38 — Repro Female excess: cooling herbs (new herbs)
  ('BHC - Class 36 - Constitution I',
   'For female reproductive excess (short cycles < 24 days), which herbs cool the system? (Two of these are newly added herbs in this class.)',
   'Cramp Bark, Black Haw, Wild Yam, Eleuthero, Vitex',
   'Wild Yam, Yellow Pond Lily, Trillium, Black Haw, Cramp Bark',
   'Dong Quai, White Peony, Vitex, Black Cohosh, Licorice',
   'Motherwort, Damiana, Pasqueflower, Blue Cohosh',
   'b',
   'Female reproductive excess cooling herbs: Wild Yam, Yellow Pond Lily, Trillium, Black Haw, Cramp Bark. Yellow Pond Lily (Nuphar lutea) and Trillium (Trillium spp.) are two of the three new herbs added to the DB from this class.',
   'Female reproductive excess (short cycles < 24 days): cool the system — Wild Yam, Yellow Pond Lily, Trillium, Black Haw, Cramp Bark.',
   'Reproductive - Female', 380),

  -- Q39 — Repro Female: Vitex dual role
  ('BHC - Class 36 - Constitution I',
   'Vitex (Chasteberry) appears in the female reproductive section for both:',
   'Liver support and kidney support',
   'Deficiency (HPA stimulant) and excess (anabolic cooler)',
   'Deficiency (anabolic stimulant) and excess (lymphagogue)',
   'Hot constitution and cold constitution',
   'b',
   'Vitex is listed twice: in deficiency as an HPA stimulant (alongside Motherwort, Damiana, Anemone) and in excess as an anabolic cooler (alongside White Peony and Eleuthero). This bidirectionality reflects its modulatory, not stimulatory, action.',
   'Female reproductive excess: Vitex as anabolic cooler (also listed for deficiency HPA stimulation).',
   'Reproductive - Female', 390),

  -- Q40 — Repro Male: lifestyle note
  ('BHC - Class 36 - Constitution I',
   'The class notes include which specific lifestyle note under male reproductive deficiency?',
   'Excessive exercise can deplete testosterone and impair sperm quality',
   'Beer can influence sperm count',
   'Screen time and blue light suppress LH production',
   'Low dietary fat impairs androgen synthesis',
   'b',
   'The notes specifically flag: "beer can influence sperm count" under male reproductive deficiency — a memorable clinical pearl about alcohol''s estrogenic effects from hops.',
   'Male reproductive deficiency: Dong Quai, Licorice, White Peony, Ginsengs — improve hormone use, pelvic circulation, HPA Axis. Note: beer can influence sperm count.',
   'Reproductive - Male', 400),

  -- Q41 — Repro Male excess
  ('BHC - Class 36 - Constitution I',
   'Male reproductive excess (oiliness from excess testosterone) is treated with:',
   'Saw Palmetto, Nettle root, Pygeum, Stinging Nettle',
   'Licorice, White Peony, Shatavari, Dong Quai',
   'Wild Yam, Yellow Pond Lily, Trillium, Viburnums (Cramp Bark, Black Haw)',
   'Vitex, Eleuthero, Schisandra, Ashwagandha',
   'c',
   'Male reproductive excess herbs: Wild Yam, Yellow Pond Lily, Trillium, Viburnums (Cramp Bark, Black Haw) — the same cooling/anti-anabolic approach as female reproductive excess, notably also including the two new herbs.',
   'Male reproductive excess (oiliness from excess testosterone): Wild Yam, Yellow Pond Lily, Trillium, Viburnums (Cramp Bark, Black Haw).',
   'Reproductive - Male', 410),

  -- Q42 — Respiratory deficiency: parasympathetic
  ('BHC - Class 36 - Constitution I',
   'For respiratory deficiency, which herbs increase parasympathetic function?',
   'Osha and California Spikenard',
   'Pulsatilla (Pasqueflower) and Lobelia (small doses)',
   'Queen''s Delight and Mullein',
   'Grindelia and Licorice',
   'b',
   'Respiratory deficiency parasympathetic herbs: Pulsatilla (Pasqueflower) and Lobelia in small doses. These support rest-and-digest function to improve cardiopulmonary output. Osha/Spikenard address mucus secretion, not parasympathetic tone.',
   'Respiratory deficiency: increase parasympathetic function — Pulsatilla (Pasqueflower), Lobelia (small doses).',
   'Respiratory', 420),

  -- Q43 — Respiratory: California Spikenard
  ('BHC - Class 36 - Constitution I',
   'What is California Spikenard (Aralia californica) specifically used for in the respiratory system?',
   'Cooling excess mucus production in respiratory excess',
   'Increase mucus secretion in tissues for respiratory deficiency',
   'Stimulate lymph drainage in respiratory congestion',
   'Anti-spasmodic for bronchospasm and asthma',
   'b',
   'California Spikenard (Aralia, mapped from "Aralia" in the notes) is used to "increase mucus secretion in tissues" for respiratory deficiency — the opposite of what one might expect, moistening dry respiratory tissue.',
   'Respiratory deficiency: Aralia (California Spikenard) to increase mucus secretion in tissues.',
   'Respiratory', 430),

  -- Q44 — Respiratory excess: thyroid note
  ('BHC - Class 36 - Constitution I',
   'For respiratory excess, the notes suggest considering which differential diagnosis?',
   'Adrenal fatigue causing exaggerated stress response and hyperventilation',
   'A thyroid picture, especially hyperventilation with stress',
   'Mast cell activation syndrome as driver of airway excess',
   'Parasympathetic dominance causing overproduction of mucus',
   'b',
   'The notes state respiratory excess "may be thyroid picture with hyperventilation under stress" — an important differential to keep in mind when cooling herbs (Mullein, Horsetail, Grindelia, Licorice, Wild Cherry) don''t give a complete response.',
   'Respiratory excess: cool excess overproduction — Mullein, Horsetail, Grindelia, Licorice, Wild Cherry. May be a thyroid picture (esp. hyperventilation with stress).',
   'Respiratory', 440),

  -- Q45 — Cardiovascular deficiency signs
  ('BHC - Class 36 - Constitution I',
   'Which physical signs indicate cardiovascular deficiency according to the class notes?',
   'Elevated blood pressure and resting tachycardia',
   'Thready or shallow pulse, mottled/mosaic skin pattern on thighs and upper arms',
   'Edema in the lower extremities with venous insufficiency',
   'Irregular heart rhythm and exercise intolerance',
   'b',
   'Cardiovascular deficiency signs: thready or shallow pulse, mottled/mosaic skin pattern on thighs and upper arms. These visual and palpatory findings indicate poor peripheral perfusion.',
   'Cardiovascular deficiency: vasodilators — Ginkgo, Prickly Ash, Anemone (Pasqueflower), Ginger. Signs: thready/shallow pulse, mottled skin on thighs/upper arms.',
   'Cardiovascular', 450),

  -- Q46 — Lymph/Immune deficiency: lymphagogues
  ('BHC - Class 36 - Constitution I',
   'The lymphagogues for lymph/immune deficiency are:',
   'Astragalus, Marshmallow, Baptisia, Echinacea, Cypress',
   'Red Root, Yerba Mansa, Ocotillo, Poke, Queen''s Delight (Stilingia)',
   'Chinese Skullcap, Licorice, Thuja, Myrrh',
   'Calendula, Cleavers, Red Root, Echinacea',
   'b',
   'Lymphagogues for immune deficiency: Red Root, Yerba Mansa, Ocotillo, Poke, and Queen''s Delight (Stilingia). Option a is the innate immunity list; option c is the excess/autoimmune + acquired immunity list.',
   'Lymph/Immune deficiency: lymphagogues — Red Root, Yerba Mansa, Ocotillo, Poke, Queen''s Delight (Stilingia).',
   'Lymph / Immune', 460),

  -- Q47 — Lymph/Immune: acquired immunity
  ('BHC - Class 36 - Constitution I',
   'For supporting acquired immune function (as distinct from innate immunity), which herb is specifically listed?',
   'Echinacea',
   'Astragalus',
   'Thuja (red cedar)',
   'Myrrh',
   'c',
   'Thuja (red cedar) is specifically listed to "support acquired immune function" — while Marshmallow, Astragalus, Baptisia, Myrrh, Echinacea, and Cypress support innate immunity. Thuja is the only herb assigned to acquired immunity.',
   'Lymph/Immune deficiency: Thuja (red cedar) to support acquired immune function.',
   'Lymph / Immune', 470),

  -- Q48 — Skin deficiency
  ('BHC - Class 36 - Constitution I',
   'Skin deficiency is said to equal which other system''s deficiency, guiding its treatment?',
   'Kidney deficiency — same fluids system',
   'Liver deficiency — support liver and increase blood supply to skin',
   'Lymph deficiency — clear lymphatic drainage to skin',
   'Adrenal deficiency — address cortisol to improve skin barrier',
   'b',
   'The notes explicitly state: "Skin deficiency (= liver deficiency symptoms; support liver, increase blood supply to skin)" — the skin and liver are treated as mirrors in this constitutional framework.',
   'Skin deficiency (= liver deficiency): stimulate circulation — Calendula, Prickly Ash, Queen''s Delight (Stilingia), Goldenseal root.',
   'Skin', 480),

  -- Q49 — Musculoskeletal deficiency
  ('BHC - Class 36 - Constitution I',
   'For musculoskeletal deficiency (insufficient blood flow and sympathetic NS response), which herbs are recommended?',
   'Black Cohosh, Lobelia, Passionflower, Skullcap',
   'Milky Oats, Kava, Passionflower, Valerian',
   'Kola Nut, Anemone (Pasqueflower), Panax Ginsengs',
   'Ginkgo, Prickly Ash, Ginger, Wild Ginger',
   'c',
   'Musculoskeletal deficiency: Kola Nut, Anemone (Pasqueflower), Panax Ginsengs — stimulate blood flow and sympathetic NS response. Option a is the excess (muscle relaxant) list.',
   'Musculoskeletal deficiency: stimulate blood flow, sympathetic NS response — Kola Nut, Anemone (Pasqueflower), Panax Ginsengs.',
   'Musculoskeletal', 490),

  -- Q50 — Musculoskeletal excess
  ('BHC - Class 36 - Constitution I',
   'For musculoskeletal excess, the therapeutic goal is to "disperse blood from musculature into viscera." Which herbs accomplish this?',
   'Kola Nut, Anemone (Pasqueflower), Ginseng, Prickly Ash',
   'Black Cohosh, Lobelia, Passionflower, Skullcap — plus Milky Oats to cool sympathetic stress',
   'Cramp Bark, Black Haw, Wild Yam, Yellow Pond Lily',
   'Rhodiola, Eleuthero, Schisandra, Ashwagandha',
   'b',
   'Musculoskeletal excess muscle relaxants: Black Cohosh, Lobelia, Passionflower, and Skullcap (disperse blood from musculature into viscera); plus Milky Oats to cool the sympathetic stress response. Option a is the deficiency list.',
   'Musculoskeletal excess: muscle relaxants — Black Cohosh, Lobelia, Passionflower, Skullcap. Disperse blood from musculature into viscera.',
   'Musculoskeletal', 500);

  RAISE NOTICE 'Class 36 quiz — 50 questions inserted.';
END $$;
