-- Migration 337: Class 68 - Integumentary III - Quiz Questions
-- H = 85+ distinct herbs/supplements (ceiling applies)
-- F = 13 named factual items (dosages, formulas, constituents)
-- target = clamp(15 + 85×4 + 13, 20, 50) = 50
-- correct_option distribution: a=12, b=13, c=13, d=12

SET search_path TO herbal, public;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM herbal.class_quiz_questions
             WHERE class_name = 'BHC - Class 68 - Integumentary III') THEN
    RAISE NOTICE 'Class 68 quiz questions already loaded, skipping';
    RETURN;
  END IF;

  INSERT INTO herbal.class_quiz_questions
    (class_name, question_text, option_a, option_b, option_c, option_d,
     correct_option, explanation, snippet_text, section_header, sort_order)
  VALUES

  -- Q1 (c)
  ('BHC - Class 68 - Integumentary III',
   'Ginkgo biloba is described as specific for skin lesions caused by which underlying issue?',
   'Bacterial infection of the dermis',
   'Excess sebum production',
   'Vascular or circulatory insufficiency',
   'Hormonal imbalance in the epidermis',
   'c',
   'The notes specify Ginkgo is "specific for skin lesions due to vascular insufficiency or circulatory insufficiency (i.e. lymph)" and for lesions that have gone into the dermal layer.',
   'Specific for skin lesions due to vascular insufficiency or circulatory insufficiency (i.e. lymph). For wounds or lesions that have gone into the dermal layer.',
   'Integumentary Materia Medica', 10),

  -- Q2 (b)
  ('BHC - Class 68 - Integumentary III',
   'What is the dry plant tincture preparation ratio and menstruum strength for Ginkgo biloba as listed in the integumentary materia medica?',
   '1:3, 40%',
   '1:5, 60%',
   '1:2, 75%',
   '1:4, 50%',
   'b',
   'The notes list Ginkgo as "dry plant tincture 1:5, 60%" with a dose of 30-60 drops up to 3x/day.',
   'Dry plant tincture 1:5, 60%. Dose: 30-60 drops up to 3x / day. Standard infusion: 2-4 oz, 3x / day.',
   'Integumentary Materia Medica', 20),

  -- Q3 (b→a)
  ('BHC - Class 68 - Integumentary III',
   'Dong Quai applied topically has which specific integumentary effect?',
   'Increases photosensitivity',
   'Reduces sebum production',
   'Contracts pores and tightens skin',
   'Dissolves keratin plugs',
   'a',
   'The notes state Dong Quai "can be used topically (tincture or decoction) to increase photosensitivity" and acts as a circulatory stimulant.',
   'Can be used topically (tincture or decoction) to increase photosensitivity. Circulatory stimulant. Warming, moistening and stimulating.',
   'Integumentary Materia Medica', 30),

  -- Q4 (c→d)
  ('BHC - Class 68 - Integumentary III',
   'Gotu Kola is described as specific for which skin presentation in the integumentary materia medica?',
   'Oily, acneiform eruptions',
   'Weeping, fluid-filled blisters',
   'Bright red, urticarial wheals',
   'Dry, scaly eruptions',
   'd',
   'The notes state Gotu Kola is "specific to treating dry scaly eruptions" and is a connective tissue tonic that repairs connective tissue and prevents keloids.',
   'Specific to treating dry scaly eruptions. Connective tissue tonic. Repair connective tissue and prevent keloids. Internally and/or topically.',
   'Integumentary Materia Medica', 40),

  -- Q5 (b→a)
  ('BHC - Class 68 - Integumentary III',
   'What is Gotu Kola''s specific benefit related to wound healing that distinguishes it from other vulneraries?',
   'It repairs connective tissue and prevents keloids',
   'It dissolves biofilms in infected wounds',
   'It stops bleeding through astringent action',
   'It sterilizes wounds through antimicrobial action',
   'a',
   'Gotu Kola is noted as a "connective tissue tonic" that can "repair connective tissue and prevent keloids," making it specific for scar prevention.',
   'Connective tissue tonic. Repair connective tissue and prevent keloids. Internally and/or topically.',
   'Integumentary Materia Medica', 50),

  -- Q6 (c)
  ('BHC - Class 68 - Integumentary III',
   'What is the tincture dose range for Calendula officinalis as listed in the integumentary materia medica?',
   '5-10 ml 4x/day',
   '0.5-1 ml 2x/day',
   '1-4 ml 3x/day',
   '10-30 drops 2x/day',
   'c',
   'The notes list Calendula tincture dose as "1-4 ml 3x/day" and note it helps improve skin''s protective barrier and supports collagen synthesis.',
   'Dose: Tincture: 1-4 ml 3 x day. Helps improve skin''s protective barrier. Helps support collagen synthesis. Poorly healing stasis wounds.',
   'Integumentary Materia Medica', 60),

  -- Q7 (c)
  ('BHC - Class 68 - Integumentary III',
   'Calendula is specifically indicated for which type of wounds in the integumentary materia medica?',
   'Deep puncture wounds with embedded debris',
   'Fresh surgical incisions',
   'Poorly healing stasis wounds in people with poor circulation',
   'Burns requiring rapid re-epithelialization',
   'c',
   'The notes state Calendula is for "poorly healing stasis wounds — people that have wounds outside, poor circulation" and can be used topically or internally.',
   'Poorly healing stasis wounds. People that have wounds outside, poor circulation. Topically or internally.',
   'Integumentary Materia Medica', 70),

  -- Q8 (b→a)
  ('BHC - Class 68 - Integumentary III',
   'What is the maximum recommended dose of Black Cohosh per dose?',
   '25 drops',
   '10 drops',
   '60 drops',
   '40 drops',
   'a',
   'The notes specify "Black Cohosh - max 25 drops/dose is best" and warn it can actually cause headaches if the dose is too high.',
   'Black Cohosh - max 25 drops/dose is best. Black cohosh - can actually cause headaches if dose too high.',
   'Musculo Case Study', 80),

  -- Q9 (c→d)
  ('BHC - Class 68 - Integumentary III',
   'Black Cohosh is described as specific for which musculoskeletal complaint?',
   'Knee joint swelling',
   'Foot cramps',
   'Shoulder impingement',
   'Back tension',
   'd',
   'The notes state "black cohosh - specific for back tension." It is also anti-inflammatory and alterative.',
   'black cohosh - specific for back tension. Black Cohosh - max 25 drops/dose is best.',
   'Musculo Case Study', 90),

  -- Q10 (c)
  ('BHC - Class 68 - Integumentary III',
   'What dosing protocol is described for Pedicularis when treating teeth grinding?',
   'Start at 5 drops and increase slowly',
   'Use a fixed dose of 20 drops 3x/day',
   'Start at 60mL then taper to 35-40mL',
   'Use only at bedtime, 30 drops',
   'c',
   'The notes specify "pedicularis - for teeth grinding, higher dose to start to unwind, then taper off - 60mL -> 35-40mL."',
   'pedicularis - for teeth grinding, higher dose to start to unwind, then taper off - 60mL -> 35-40mL in that.',
   'Musculo Case Study', 100),

  -- Q11 (b→d)
  ('BHC - Class 68 - Integumentary III',
   'What is the formula described for acute muscle tension?',
   'Skullcap + Valerian + Passionflower',
   'Milky Oats + Ashwagandha + Motherwort',
   'Kava + Blue Vervain + Lemon Balm',
   'Pedicularis + Black Cohosh + Ginger',
   'd',
   'The notes state "Pedicularis + Black Cohosh + Ginger -> acute muscle tension."',
   'Pedicularis + Black Cohosh + Ginger -> acute muscle tension.',
   'Musculo Case Study', 110),

  -- Q12 (c)
  ('BHC - Class 68 - Integumentary III',
   'What are the three mast cell stabilizing herbs listed for eczema?',
   'Calendula, Licorice, Nettle',
   'Gotu Kola, Astragalus, Comfrey',
   'White Peony, Baikal Skullcap, Mimosa',
   'Feverfew, Celery Seed, Poke Root',
   'c',
   'The notes list "reduce allergic response in the skin — mast cell stabilizing: white peony, Baikal skullcap, mimosa."',
   'Reduce allergic response in the skin — mast cell stabilizing: white peony, Baikal skullcap, Mimosa.',
   'Eczema', 120),

  -- Q13 (b→a)
  ('BHC - Class 68 - Integumentary III',
   'How is Licorice used for eczema, and what caution applies to internal use?',
   'Topically as solvent extract in flares, rotated in and out; internally can cause a flare',
   'Internally as a decoction; no internal cautions',
   'Only internally as a tincture; topical use ineffective',
   'As a poultice; avoid if taking blood thinners',
   'a',
   'The notes specify Licorice for eczema topically as "solvent extract; use in flares, rotate in and out; decoction, make a wash" and note "internally can cause a flare — worse before it gets better."',
   'Anti-inflammatory: licorice topically (solvent extract); use in flares, rotate in and out; decoction, make a wash. Internally can cause a flare; worse before it gets better.',
   'Eczema', 130),

  -- Q14 (b)
  ('BHC - Class 68 - Integumentary III',
   'What is the dosing protocol for Poke Root used as a lymphatic for eczema?',
   '10-30 drops 3x/day, increasing weekly',
   'Start at 1 drop, then 2, up to 5 — low and slow to avoid a flare',
   'Full dose from the start; reduce if flare occurs',
   '5 drops twice daily as a maintenance dose',
   'b',
   'The notes specify poke root "small doses as lymphatic: 1 drop, then 2, up to 5; low and slow to not cause a flare."',
   'Poke root as a lymphatic — low and slow to not cause a flare — 1 drop, then 2, up to 5.',
   'Eczema', 140),

  -- Q15 (c)
  ('BHC - Class 68 - Integumentary III',
   'What is David Hoffmann''s core psoriasis formula?',
   'Milk Thistle, Dandelion Root, Schizandra',
   'Calendula, Licorice, Dong Quai, Gotu Kola',
   'Burdock, Yellow Dock, Baical Skullcap',
   'Astragalus, Sarsaparilla, Turmeric',
   'c',
   'The notes state "David Hoffman Prescription: Burdock, Yellow Dock, Baical Skullcap." Vervain is added if anxiety is present; Poke Root is added if no tissue change.',
   'David Hoffman Prescription: Burdock, Yellow Dock, Baical Skullcap. If with anxiety: add Verbena (Vervain). If no change in tissue, add Poke 1 drop, then 2.',
   'Psoriasis', 150),

  -- Q16 (c)
  ('BHC - Class 68 - Integumentary III',
   'Which herb is added to David Hoffmann''s psoriasis formula when anxiety is present?',
   'Passionflower',
   'Skullcap',
   'Vervain',
   'Lemon Balm',
   'c',
   'The notes specify "if with anxiety: add Verbena (Vervain)" to the David Hoffmann psoriasis formula.',
   'David Hoffman Prescription: Burdock, Yellow Dock, Baical Skullcap. If with anxiety: add Verbena (Vervain).',
   'Psoriasis', 160),

  -- Q17 (b)
  ('BHC - Class 68 - Integumentary III',
   'In the psoriasis formula, when Poke Root is added, which herb buffers it to protect the liver?',
   'Milk Thistle',
   'Sarsaparilla',
   'Yellow Dock',
   'Dandelion Root',
   'b',
   'The notes state "add Sarsaparilla to buffer the Poke and liver" when Poke Root is added to the psoriasis formula.',
   'If no change in tissue, add Poke 1 drop, then 2.. and add Sarsaparilla to buffer the Poke and liver.',
   'Psoriasis', 170),

  -- Q18 (b→a)
  ('BHC - Class 68 - Integumentary III',
   'The dermatitis formula consists of which four herbs?',
   'Calendula, Licorice, Dong Quai, Gotu Kola',
   'Nettle, Calendula, Astragalus, Comfrey',
   'Burdock, Yellow Dock, Licorice, Calendula',
   'Gotu Kola, White Peony, Mimosa, Chamomile',
   'a',
   'The notes list the dermatitis formula as "Calendula, Licorice, Dong quai, Gotu kola."',
   'Dermatitis formula: Calendula, Licorice, Dong quai, Gotu kola.',
   'Dermatitis', 180),

  -- Q19 (c→a)
  ('BHC - Class 68 - Integumentary III',
   'What is the key point about Reishi mushroom extraction for preserving its full therapeutic value?',
   'Water is required in the extraction; alcohol only loses the complexity of the constituents',
   'Alcohol extraction alone is sufficient and preferred',
   'It must be extracted at high temperature to release beta-glucans',
   'It must be fermented before extraction',
   'a',
   'The notes state "reishi - you need water in the extraction — alcohol only, you lose the complexity of the constituents."',
   'reishi - you need water in the extraction. Alcohol only, you lose the complexity of the constituents.',
   'Musculo Case Study', 190),

  -- Q20 (c)
  ('BHC - Class 68 - Integumentary III',
   'What constituent in Frankincense is cited for combating chronic joint inflammation?',
   'Hypericin',
   'Silymarin',
   'Boswellic acid',
   'Berberine',
   'c',
   'The notes state "frankincense - boswellic acid - joint inflammation — salve with that and arnica."',
   'frankincense - boswellic acid - joint inflammation. Salve with that and arnica.',
   'Musculo Case Study', 200),

  -- Q21 (b→a)
  ('BHC - Class 68 - Integumentary III',
   'Lisa''s sleep tincture includes which three herbs?',
   'Pedicularis, Jamaican Dogwood, Catnip glycerite',
   'Passionflower, Skullcap, Lemon Balm',
   'Valerian, Hops, Lavender',
   'Ashwagandha, Milky Oats, Kava',
   'a',
   'Lisa''s sleep tincture is listed as "Pedicularis, Jamaican Dogwood, Catnip glycerite."',
   '- Sleep tincture: Pedicularis, Jamaican Dogwood, Catnip glycerite.',
   'Lisa (Patient Case)', 210),

  -- Q22 (c→d)
  ('BHC - Class 68 - Integumentary III',
   'Which herb is described as "cooling to the thyroid if heat agitation"?',
   'Bugleweed',
   'Lemon Balm',
   'Skullcap',
   'Motherwort',
   'd',
   'The notes state "motherwort cooling to the thyroid, if heat agitation" in both the personal and generated notes.',
   'motherwort cooling to the thyroid, if heat agitation.',
   'Musculo Case Study', 220),

  -- Q23 (c)
  ('BHC - Class 68 - Integumentary III',
   'Which herb in the nourishing tea formula is specifically noted to require hot water to break cell walls?',
   'Nettle',
   'Horsetail',
   'Red Clover',
   'Alfalfa',
   'c',
   'The notes state "red clover - complex, so hot water necessary to break cell walls (infusion)."',
   'red clover - complex, so hot water necessary to break cell walls (infusion).',
   'Nourishing Tea Formula', 230),

  -- Q24 (b→d)
  ('BHC - Class 68 - Integumentary III',
   'Oat Straw is described as having what quality requirement for best results?',
   'Must be dried in the shade to preserve volatile oils',
   'Must be prepared as a cold infusion only',
   'Should be decocted for a minimum of 30 minutes',
   'Needs to be green and freshly dried',
   'd',
   'The notes state "Oat Straw - really needs to be green and freshly dried."',
   'Oat Straw - really needs to be green and freshly dried.',
   'Musculo Case Study', 240),

  -- Q25 (b)
  ('BHC - Class 68 - Integumentary III',
   'Passionflower is described as better used in what manner for sleep support?',
   'Only at bedtime as a single large dose',
   'As a sleep tonic taken throughout the day so you are ready for the night',
   'Combined with valerian for enhanced sedation',
   'As an essential oil applied to the pillow',
   'b',
   'The notes state passionflower is "better as a ''sleep tonic'' rather than putting you to sleep — take it throughout the day so you are ready for the night."',
   'passionflower better as a "sleep tonic" rather than putting you to sleep — take it throughout the day so you are ready for the night.',
   'Musculo Case Study', 250),

  -- Q26 (d)
  ('BHC - Class 68 - Integumentary III',
   'Which herb is described as "specific for back tension" in this class?',
   'Pedicularis',
   'Skullcap',
   'Blue Vervain',
   'Black Cohosh',
   'd',
   'The notes state "black cohosh - specific for back tension."',
   'black cohosh - specific for back tension.',
   'Musculo Case Study', 260),

  -- Q27 (b)
  ('BHC - Class 68 - Integumentary III',
   'Blue Vervain is noted for tension in which specific area of the body?',
   'Lower back and sacrum',
   'Neck and shoulders',
   'Hip flexors',
   'Knees and ankles',
   'b',
   'The notes list "blue vervain (neck/shoulders tension)" in the daytime tincture and "jaw tension, stress, anxiety" in the formulation section.',
   'Blue Vervain — Jaw tension, stress, anxiety. Hepatic, nourishes liver.',
   'Sleep Support', 270),

  -- Q28 (b)
  ('BHC - Class 68 - Integumentary III',
   'Which formula is described for restlessness before sleep?',
   'Kava + Passionflower + Ashwagandha',
   'Blue Vervain + Passionflower + Skullcap',
   'Lemon Balm + Valerian + Hops',
   'Milky Oats + Skullcap + Lavender',
   'b',
   'The notes state "formula: blue vervain + passionflower + skullcap -> tending to the restlessness before sleep."',
   'formula: blue vervain + passionflower + skullcap -> tending to the restlessness before sleep.',
   'Musculo Case Study', 280),

  -- Q29 (b)
  ('BHC - Class 68 - Integumentary III',
   'Which three herbs are listed for grief support together?',
   'Hawthorn, Linden, Rose',
   'Bleeding Heart, Mimosa, Motherwort',
   'Passionflower, Lemon Balm, Skullcap',
   'Shatavari, Gotu Kola, Ashwagandha',
   'b',
   'The notes state "bleeding heart -> grief support — mimosa and motherwort as well."',
   'bleeding heart -> grief support. Mimosa and motherwort as well.',
   'Musculo Case Study', 290),

  -- Q30 (b)
  ('BHC - Class 68 - Integumentary III',
   'What is Bleeding Heart (Turkey Corn/Dicentra) specifically noted for in these class notes?',
   'Immune stimulant for skin conditions',
   'Energetically supportive of grief',
   'Antispasmodic for muscle cramps',
   'Circulatory stimulant for cold extremities',
   'b',
   'The generated notes state "Bleeding Heart — Energetically supportive of grief — Reference: Michael Moore''s Materia Medica."',
   'Bleeding Heart — Energetically supportive of grief. Reference: Michael Moore''s Materia Medica.',
   'Bleeding Heart', 300),

  -- Q31 (c→d)
  ('BHC - Class 68 - Integumentary III',
   'Elecampane is described as targeting the lungs but not cough specifically. Which herb is added specifically when cough is present?',
   'Mullein',
   'Horehound',
   'Lobelia',
   'Wild Cherry Bark',
   'd',
   'The notes state "elecampane - targeting the lungs but not cough specifically — with cough = Wild Cherry."',
   'elecampane - targeting the lungs but not cough specifically. With cough = Wild Cherry.',
   'Musculo Case Study', 310),

  -- Q32 (c)
  ('BHC - Class 68 - Integumentary III',
   'Why is mullein flower preferred over mullein leaf for internal use?',
   'The leaf contains toxic pyrrolizidine alkaloids',
   'The flower has higher volatile oil content',
   'Leaf hairs cause respiratory irritation when not well-strained',
   'The leaf is only appropriate for topical use',
   'c',
   'The notes state "prefer mullein flowers to leaf - for nourishing and moistening — mullein leaf hairs when not well-strained" cause irritation.',
   'prefer mullein flowers to leaf - for nourishing and moistening. Mullein leaf hairs when not well-strained.',
   'Musculo Case Study', 320),

  -- Q33 (a)
  ('BHC - Class 68 - Integumentary III',
   'What formula is described for post-menopausal dryness?',
   'Shatavari + Ashwagandha + Gotu Kola (+ licorice as demulcent)',
   'Red Clover + Hops + Astragalus',
   'Shatavari + Black Cohosh + Dong Quai',
   'Milky Oats + Hawthorn + Linden',
   'a',
   'The notes state "formula: shatavari + ashwagandha + gotu kola -> address post-menopausal dryness (+ licorice as demulcent)."',
   'formula: shatavari + ashwagandha + gotu kola -> address post-menopausal dryness (+ licorice as demulcent).',
   'Musculo Case Study', 330),

  -- Q34 (b→a)
  ('BHC - Class 68 - Integumentary III',
   'Hops is noted as estrogenic — in which two conditions should it be avoided?',
   'Breast cancer and endometriosis',
   'Hypothyroidism and PCOS',
   'Fibroids and perimenopause',
   'Osteoporosis and anemia',
   'a',
   'The notes state "avoid in breast cancer and endometriosis, as well as avoid Red Clover, also estrogenic" when discussing Hops.',
   'Hops - nourish aging estrogen (but avoid in breast cancer and endometriosis, as well as avoid Red Clover, also estrogenic).',
   'Post-Menopause', 340),

  -- Q35 (d)
  ('BHC - Class 68 - Integumentary III',
   'Which herb is recommended as a moistening adaptogen for post-menopausal dryness?',
   'Schizandra',
   'Holy Basil',
   'Ashwagandha',
   'Astragalus',
   'd',
   'The notes specifically state "consider moistening adaptogens like astragalus" for post-menopausal tissue dryness.',
   'Post-Menopause Considerations: tissue dryness (estrogen-related); consider moistening adaptogens like astragalus.',
   'Post-Menopause', 350),

  -- Q36 (c)
  ('BHC - Class 68 - Integumentary III',
   'Which herb is cited as helpful as an immune adaptogen specifically for psoriasis?',
   'Astragalus',
   'Echinacea',
   'Reishi Mushroom',
   'Andrographis',
   'c',
   'The notes state "Immune modulation: Reishi helpful as an immune adaptogen" in the psoriasis herbal actions section.',
   'Immune modulation: Reishi helpful as an immune adaptogen.',
   'Psoriasis', 360),

  -- Q37 (b)
  ('BHC - Class 68 - Integumentary III',
   'The nourishing tea formula targets which two conditions?',
   'Thyroid support and hair growth',
   'Bone density and nervous system support',
   'Liver support and hormonal balance',
   'Digestive health and immune support',
   'b',
   'The notes state the nourishing tea formula targets "bone density, nervous system support."',
   'Nourishing Tea Formula: Target: Bone density, nervous system support.',
   'Nourishing Tea Formula', 370),

  -- Q38 (b→a)
  ('BHC - Class 68 - Integumentary III',
   'Which herbs are listed together for hair strength in the personal notes?',
   'Horsetail, Rosemary, Alfalfa, Gotu Kola, Prickly Ash',
   'Alfalfa, Gotu Kola, Reishi, Red Clover, Nettle',
   'Nettle, Oat Straw, Horsetail, Fennel, Lemon Balm',
   'Calendula, Chamomile, Lavender, Rose, Evening Primrose',
   'a',
   'The personal notes list hair strength herbs as "horsetail, rosemary, alfalfa, gotu kola, prickly ash."',
   'hair strength: horsetail, rosemary, alfalfa, gotu kola, prickly ash.',
   'Hair Care', 380),

  -- Q39 (b)
  ('BHC - Class 68 - Integumentary III',
   'Evening Primrose Oil is specifically noted for which hair condition?',
   'Alopecia areata',
   'Premature gray hair',
   'Scalp fungal infections',
   'Thinning hair due to nutrient deficiency',
   'b',
   'The notes state "evening primrose oil used for gray hair recovery" (premature gray).',
   'Evening primrose oil used for gray hair recovery. Gray hair — evening primrose oil for premature gray.',
   'Hair Care', 390),

  -- Q40 (c→a)
  ('BHC - Class 68 - Integumentary III',
   'Rosehip oil is noted as specific for which skin function?',
   'Holding skin pH',
   'Stimulating collagen production',
   'Reducing melanin production',
   'Dissolving fungal biofilms',
   'a',
   'The notes state "Rosehip oil — specific for holding that pH" in the context of maintaining the skin''s acid mantle (4.0-4.2).',
   'Rosehip oil — specific for holding that pH.',
   'Skin pH and Oilination', 400),

  -- Q41 (c→d)
  ('BHC - Class 68 - Integumentary III',
   'What is the ideal skin pH range described in these notes?',
   '6.5 to 7.5',
   '3.0 to 3.5',
   '5.5 to 6.0',
   '4.0 to 4.2',
   'd',
   'The personal notes state "4.2 - 4.0 best pH" for skin, noting that as skin ages it becomes more alkaline, increasing susceptibility to wounding and slower healing.',
   'pH: 4.2 - 4.0 best pH. As skin ages, skin gets more alkaline — more susceptible to wounding, and slower to heal.',
   'Skin pH and Oilination', 410),

  -- Q42 (b)
  ('BHC - Class 68 - Integumentary III',
   'Which of the following is listed as an astringent in the wound wash materia medica?',
   'Mugwort',
   'Red Root',
   'Gotu Kola',
   'Spilanthes',
   'b',
   'The notes list Red Root under Astringents for wound wash alongside Witch Hazel, Oak, Green Tea, Sage, Chamomile, Willow, and Yarrow.',
   'Astringent: Arctostaphylos family (uva ursi, etc), Witch Hazel, Rose family, Oak, Green Tea, Sage, Chamomile, Red Root, Willow, Yarrow.',
   'Wound Care', 420),

  -- Q43 (d)
  ('BHC - Class 68 - Integumentary III',
   'Which of the following is listed as a vulnerary in the wound wash materia medica?',
   'Tansy',
   'Chaparral',
   'Barberry',
   'Self Heal',
   'd',
   'The notes list Self Heal under Vulneraries alongside Gotu Kola, Plantain, Calendula, Lavender, Burdock, Helichrysum, Goldenrod, Chamomile, Chickweed, St. John''s Wort, Marshmallow, and Comfrey.',
   'Vulnerary: Gotu kola, Plantain, Calendula, Lavender, Burdock, Helichrysum, Golden Rod, Chamomile, Self Heal, Chickweed, St Johns Wort, Marshmallow, Comfrey (for shallow stuff).',
   'Wound Care', 430),

  -- Q44 (c→d)
  ('BHC - Class 68 - Integumentary III',
   'Which of the following is listed as an antimicrobial in the wound wash materia medica?',
   'Witch Hazel',
   'Red Root',
   'Helichrysum',
   'Yarrow',
   'd',
   'Yarrow appears in both the Astringent AND Antimicrobial lists in the wound wash materia medica.',
   'Antimicrobial: Mugwort, Chaparral, Myrrh, Goldenseal, Garlic, Baptisia, Tea tree, Yarrow, Lavender, Rosemary, Tansy, Coptis, Thyme, Chamomile, Barberry, Oregon Grape, Yerba Mansa, Spilanthes, Hops.',
   'Wound Care', 440),

  -- Q45 (c)
  ('BHC - Class 68 - Integumentary III',
   'Chaparral is listed under which wound wash action category, and what caution is noted?',
   'Vulnerary; contraindicated in pregnancy',
   'Astringent; can cause photosensitivity',
   'Antioxidant for complex conditions; beware — hard on liver',
   'Antimicrobial; avoid in renal insufficiency',
   'c',
   'Chaparral is listed as an antimicrobial and antioxidant for complex conditions: "Antioxidant — great example: Chaparral (beware hard on liver)."',
   'Antimicrobial: Chaparral. Antioxidant: great example — Chaparral (beware hard on liver).',
   'Wound Care', 450),

  -- Q46 (b)
  ('BHC - Class 68 - Integumentary III',
   'Muscle tension is associated with what underlying physiological issue in these notes?',
   'Excess adrenaline and cortisol',
   'Loss of emolliency and not enough fats — milky oats helps',
   'Calcium and magnesium deficiency alone',
   'Nervous system overstimulation from caffeine',
   'b',
   'The notes state "muscle tension = loss of emolliency and not enough fats -> milky oats helps."',
   'muscle tension = loss of emolliency and not enough fats -> milky oats helps.',
   'Musculo Case Study', 460),

  -- Q47 (c→d)
  ('BHC - Class 68 - Integumentary III',
   'What is Gotu Kola''s dry plant tincture preparation ratio and menstruum strength?',
   '1:3, 40%',
   '1:5, 60%',
   '1:2, 75%',
   '1:5, 50%',
   'd',
   'The notes list Gotu Kola as "Dry plant tincture 1:5, 50%" with dose 15-40 drops up to 4x/day.',
   'Dry plant tincture 1:5, 50%. Dose: 15-40 drops up to 4 x day.',
   'Integumentary Materia Medica', 470),

  -- Q48 (b→a)
  ('BHC - Class 68 - Integumentary III',
   'What contraindication is shared by both Gotu Kola and Dong Quai in the integumentary materia medica?',
   'Pregnancy',
   'Hypertension',
   'Autoimmune conditions',
   'Concurrent antibiotic use',
   'a',
   'Both Gotu Kola and Dong Quai list Pregnancy as a contraindication in the integumentary materia medica.',
   'Gotu Kola: Contraindication: Pregnancy. Dong Quai: Contraindications: Blood thinning agents, Pregnancy, Heavy menstrual bleeding.',
   'Integumentary Materia Medica', 480),

  -- Q49 (b)
  ('BHC - Class 68 - Integumentary III',
   'Lisa''s main tonic tincture contains which combination of herbs?',
   'Passionflower, Skullcap, Lemon Balm, Valerian, Hops',
   'Milky Oats, Hawthorn leaf/flower, Shatavari, Gotu Kola, Bleeding Heart, Black Cohosh, Linden glycerite',
   'Ashwagandha, Holy Basil, Schizandra, Reishi, Astragalus',
   'Pedicularis, Blue Vervain, Kava, Siberian Ginseng, Rhodiola',
   'b',
   'The personal notes list Lisa''s tincture as "milky oats, hawthorn leaf/flower, shatavari, gotu kola, bleeding heart, black cohosh, linden glycerite."',
   'Tincture: milky oats, hawthorn leaf/flower, shatavari, gotu kola, bleeding heart, black cohosh, linden glycerite. (Would add Bacopa now and Mimosa.)',
   'Lisa (Patient Case)', 490),

  -- Q50 (c)
  ('BHC - Class 68 - Integumentary III',
   'Celery Seed''s role in the eczema materia medica is to do what?',
   'Reduce mast cell activation in the skin',
   'Provide antioxidant protection against free radicals',
   'Help the body liquify and eliminate waste through the bowel',
   'Reduce elevated histamine levels',
   'c',
   'The notes state "Celery seed — help the body liquify and eliminate waste through the bowel" in the eczema materia medica.',
   'Celery seed — help the body liquify and eliminate waste through the bowel.',
   'Eczema', 500);

END $$;
