-- Migration 344: Class 69 — Holistic Cancer Support — quiz questions
--
-- H = 48 distinct herbs/supplements identified
-- F = 9 named factual items (2 named formulas, 2 tincture ratios, case study profile,
--     fee schedule, chemo tea list, Feri improvements list, biologics = Vit C)
-- target = clamp(15 + 48×4 + 9×1, 20, 50) = clamp(216, 20, 50) = 50 questions

SET search_path TO herbal, public;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM herbal.class_quiz_questions
             WHERE class_name = 'BHC - Class 69 - Holistic Cancer Support') THEN
    RAISE NOTICE 'Class 69 quiz questions already loaded, skipping';
    RETURN;
  END IF;

  INSERT INTO herbal.class_quiz_questions
    (class_name, question_text, option_a, option_b, option_c, option_d,
     correct_option, explanation, snippet_text, section_header, sort_order)
  VALUES

  -- Q1
  ('BHC - Class 69 - Holistic Cancer Support',
   'Which three herbs were used for digestive ailments (diarrhea and colic) in traditional Black American herbalism?',
   'Black walnut, burdock root, catnip',
   'Garlic, horehound, sage',
   'Mullein, corn shuck, lobelia',
   'Echinacea, pine, sassafras',
   'a',
   'The generated notes specifically list black walnut leaves, burdock root, and catnip for digestive ailments like diarrhea and colic in traditional Black American herbalism.',
   'Black walnut leaves used for digestive ailments — diarrhea and colic — in traditional Black American herbalism.',
   'Traditional Black American Herbal Practices', 10),

  -- Q2
  ('BHC - Class 69 - Holistic Cancer Support',
   'Mullein leaf and corn shuck were used in traditional Black American herbalism to treat which illnesses?',
   'Diarrhea, colic, and digestive cramps',
   'Hormonal imbalance and menstrual irregularity',
   'Measles, malaria, and smallpox',
   'Nervine sedation and anxiety',
   'c',
   'Mullein leaf and corn shuck are specifically listed for illnesses like measles, malaria, and smallpox in traditional Black American herbalism.',
   'Mullein leaf used for illnesses like measles, malaria, and smallpox in traditional Black American herbalism.',
   'Traditional Black American Herbal Practices', 20),

  -- Q3
  ('BHC - Class 69 - Holistic Cancer Support',
   'In traditional Black American herbalism, garlic and red onion are classified as:',
   'Hormonal stabilizers',
   'Anti-bacterial and infection fighters',
   'Nervines and sedatives',
   'Lymphatics and blood cleansers',
   'b',
   'Garlic and red onion are explicitly described as anti-bacterial and infection fighters in the Traditional Black American Herbal Practices section.',
   'Garlic and red onion listed as anti-bacterial and infection fighters in traditional Black American herbalism.',
   'Traditional Black American Herbal Practices', 30),

  -- Q4
  ('BHC - Class 69 - Holistic Cancer Support',
   'Cotton root, bayberry bark, and black cohosh root were listed as what type of herbs in traditional Black American practice?',
   'Lymphatics used for hidden disease',
   'Carminatives for digestive cramps',
   'Antiseptics and analgesics',
   'Hormonal stabilizers',
   'd',
   'The generated notes list cotton root, bayberry bark, and black cohosh root as homeopathic stabilizers (hormonal stabilizers) in traditional Black American herbal practices.',
   'Cotton root listed as a hormonal stabilizer in traditional Black American herbal practices.',
   'Traditional Black American Herbal Practices', 40),

  -- Q5
  ('BHC - Class 69 - Holistic Cancer Support',
   'In the "Use of Herbal Treatment in Cancer Care" section, which four herbs are specifically named as anticarcinogenic?',
   'Marshmallow, cleavers, nettle, witch hazel',
   'Garlic, horehound, sage, echinacea',
   'Damiana, ashwagandha, bacopa, gotu kola',
   'Aloe vera, black walnut, sarsaparilla bark, poke root',
   'd',
   'The generated notes list aloe vera, black walnut, sarsaparilla bark, and poke root as the anticarcinogenic herbs in the cancer care section.',
   'Aloe vera listed as an anticarcinogenic herb for cancer care; immunomodulating and alkaline-rich.',
   'Use of Herbal Treatment in Cancer Care', 50),

  -- Q6
  ('BHC - Class 69 - Holistic Cancer Support',
   'In the Cancer Treatment Support section, what is the gentle initial approach described?',
   'Chlorophyll and aloe-rich treatment for inflammation reduction',
   'Anti-cancer formula 2 with sassafras and comfrey',
   'Aggressive poke root and black walnut from the start',
   'Vitamin C therapy and hyperbaric oxygen',
   'a',
   'The Cancer Treatment Support section describes a chlorophyll and aloe-rich treatment as the gentle initial approach for inflammation reduction before the more aggressive herbs.',
   'Chlorophyll and aloe-rich treatment used as the gentle, initial approach for inflammation reduction in cancer support.',
   'Cancer Treatment Support', 60),

  -- Q7
  ('BHC - Class 69 - Holistic Cancer Support',
   'What specific role does slippery elm play in cancer treatment support?',
   'Lymphatic drainage and blood cleansing',
   'Pain reduction as digestive support during chemotherapy',
   'Anti-tumor activity and immune stimulation',
   'Cooling overheated tissue',
   'b',
   'Slippery elm is described as providing pain reduction as digestive support during chemotherapy in the Cancer Treatment Support section.',
   'Slippery elm for pain reduction as digestive support during chemotherapy.',
   'Cancer Treatment Support', 70),

  -- Q8
  ('BHC - Class 69 - Holistic Cancer Support',
   'Black walnut leaf and poke root are described in the Cancer Treatment Support section as:',
   'Gentle cooling herbs for late-stage cancer',
   'Nervine herbs to calm pain during treatment',
   'Aggressive herbs useful in early cancer stages',
   'Lymphatics for blood cleansing',
   'c',
   'The generated notes describe black walnut leaf and poke root as aggressive herbs useful in early cancer stages.',
   'Black walnut leaf used aggressively (alongside poke root) in early cancer stages; useful for tumor involvement.',
   'Cancer Treatment Support', 80),

  -- Q9
  ('BHC - Class 69 - Holistic Cancer Support',
   'In the Chemotherapy Support section of the generated notes, which herb is recommended for metabolic waste removal?',
   'Cleavers',
   'Marshmallow root',
   'Witch hazel leaf',
   'Slippery elm',
   'a',
   'Cleavers is specifically noted for metabolic waste removal in the Chemotherapy Support section.',
   'Cleavers for metabolic waste removal during chemotherapy.',
   'Chemotherapy Support', 90),

  -- Q10
  ('BHC - Class 69 - Holistic Cancer Support',
   'Cat''s claw appears in which section of the generated class notes?',
   'Traditional Black American Herbal Practices',
   'Herbal Support Strategy',
   'Formulary Development',
   'Chemotherapy Support',
   'd',
   'Cat''s claw appears in the Chemotherapy Support section alongside witch hazel leaf as cooling, anti-inflammatory, and tissue-soothing herbs.',
   'Cat''s claw for cooling, anti-inflammatory, and tissue-soothing support during chemotherapy.',
   'Chemotherapy Support', 100),

  -- Q11
  ('BHC - Class 69 - Holistic Cancer Support',
   'According to the generated notes, which herb provides "blood support and minerals" during chemotherapy?',
   'Cleavers',
   'Marshmallow root',
   'Witch hazel leaf',
   'Nettle',
   'd',
   'Nettle is specifically noted for blood support and minerals in the Chemotherapy Support section of the generated notes.',
   'Nettle for blood support and minerals during chemotherapy.',
   'Chemotherapy Support', 110),

  -- Q12
  ('BHC - Class 69 - Holistic Cancer Support',
   'Anti-cancer formula 1 is designed for which situation?',
   'Post-chemotherapy recovery',
   'Late-stage metastatic cancer',
   'Quickly changing the environment in early-stage cancer',
   'Aggressive treatment after formula 2',
   'c',
   'Anti-cancer formula 1 is explicitly for quickly changing the environment in early-stage cancer using nutritive herbs.',
   'Garlic in anti-cancer formula 1 to quickly change the environment in early-stage cancer.',
   'Anti-Cancer Formula 1', 120),

  -- Q13
  ('BHC - Class 69 - Holistic Cancer Support',
   'What is asafetida''s specific role in anti-cancer formula 1?',
   'Lymphatic drainage and waste removal',
   'Anti-viral and anti-bacterial support',
   'Cooling the overheated system',
   'Nervine to calm and reduce pain',
   'd',
   'Asafetida is explicitly noted in formula 1 as a nervine to calm and reduce pain in early-stage cancer.',
   'Asafetida in anti-cancer formula 1 as nervine to calm and reduce pain in early-stage cancer.',
   'Anti-Cancer Formula 1', 130),

  -- Q14
  ('BHC - Class 69 - Holistic Cancer Support',
   'What is the purpose of peach leaves in anti-cancer formula 1?',
   'Relieve stomach pain and support healthy elimination',
   'Anti-bacterial and infection fighting',
   'Cooling the overheated system',
   'Nervine and sedation',
   'a',
   'Peach leaves in anti-cancer formula 1 are described as relieving stomach pain and supporting healthy elimination.',
   'Peach leaves in anti-cancer formula 1 to relieve stomach pain and support healthy elimination.',
   'Anti-Cancer Formula 1', 140),

  -- Q15
  ('BHC - Class 69 - Holistic Cancer Support',
   'In anti-cancer formula 1, marshmallow root serves which purpose?',
   'Anti-tumor and lymphatic support',
   'Cooling',
   'Nervine to calm pain',
   'Blood cleansing',
   'b',
   'Marshmallow root in anti-cancer formula 1 is described simply as "cooling" — it cools the environment as part of the early-stage anti-cancer formula.',
   'Marshmallow root in anti-cancer formula 1 for cooling in early-stage cancer.',
   'Anti-Cancer Formula 1', 150),

  -- Q16
  ('BHC - Class 69 - Holistic Cancer Support',
   'Anti-cancer formula 2 is described in the personal notes as:',
   'A gentle formula for newly diagnosed patients',
   'More intense, used in stages after formula 1',
   'For metastatic cancer only, replacing western treatment',
   'A post-chemo recovery formula',
   'b',
   'Formula 2 is described as "more intense — after the first one — do in stages — keep getting tested."',
   'Black walnut hulls in anti-cancer formula 2: more intense formula used in stages after formula 1.',
   'Anti-Cancer Formula 2', 160),

  -- Q17
  ('BHC - Class 69 - Holistic Cancer Support',
   'Which herb appears in anti-cancer formula 2 but NOT in formula 1?',
   'Garlic',
   'Witch hazel',
   'Black walnut',
   'Feverfew',
   'd',
   'Feverfew appears only in anti-cancer formula 2. Garlic, witch hazel, and black walnut all appear in both formulas.',
   'Feverfew in anti-cancer formula 2: more intense formula used in stages after formula 1.',
   'Anti-Cancer Formula 2', 170),

  -- Q18
  ('BHC - Class 69 - Holistic Cancer Support',
   'Which herb appears in BOTH anti-cancer formula 1 and formula 2 (in different plant parts)?',
   'Feverfew',
   'Poke root',
   'Cleavers',
   'Witch hazel',
   'd',
   'Witch hazel appears in formula 1 as leaves and in formula 2 as bark — the same herb used in two forms across both formulas.',
   'Witch hazel bark in anti-cancer formula 2: more intense formula used in stages after formula 1.',
   'Anti-Cancer Formula 2', 180),

  -- Q19
  ('BHC - Class 69 - Holistic Cancer Support',
   'Which of these herbs is NOT listed in the Lymphatic Herbs section of Shereel''s personal notes?',
   'Elderberry',
   'Black pepper',
   'Catnip',
   'Sassafras',
   'c',
   'Catnip appears in the Nervines and Anti-Inflammatories section, not in the Lymphatic Herbs list. The lymphatic herbs are black walnut, burdock, elderberry, poke root, sassafras, peach, black pepper, and SJW.',
   'St. John''s wort listed as lymphatic herb for cancer support.',
   'Lymphatic Herbs', 190),

  -- Q20
  ('BHC - Class 69 - Holistic Cancer Support',
   'In which section of Shereel''s personal notes does St. John''s wort appear as a nervine and anti-inflammatory?',
   'Shereel''s Cancer Report',
   'Anti-Cancer Formula 1',
   'Lymphatic Herbs',
   'Nervines and Anti-Inflammatories',
   'd',
   'St. John''s wort is listed in the Nervines and Anti-Inflammatories section as a nervine/AI herb for cancer support, in addition to appearing in the Lymphatic Herbs list.',
   'St. John''s wort listed as nervine and anti-inflammatory herb for cancer support.',
   'Nervines and Anti-Inflammatories', 200),

  -- Q21
  ('BHC - Class 69 - Holistic Cancer Support',
   'In Shereel''s 2022 cancer report, which category included echinacea root, mullein, corn, and pine?',
   'Digestive',
   'Nervine',
   'Hormonal stabilizers',
   'Lymphatic',
   'd',
   'Echinacea root, mullein leaf and flower, corn (shuck), and pine (needles and resin) are all listed under the lymphatic category in Shereel''s 2022 cancer report.',
   'Echinacea root — antiseptic and analgesic (lymphatic) in Shereel''s 2022 cancer report.',
   'Shereel''s Cancer Report', 210),

  -- Q22
  ('BHC - Class 69 - Holistic Cancer Support',
   'Which three herbs were listed under the nervine category in Shereel''s 2022 cancer report?',
   'Garlic, red onion, horehound',
   'Cotton root, black cohosh, catnip',
   'Sassafras, poke, lobelia',
   'Echinacea, mullein, pine',
   'c',
   'Sassafras, poke, and lobelia are the three herbs listed under the nervine category in Shereel''s 2022 cancer report.',
   'Sassafras — nervine in Shereel''s 2022 cancer report.',
   'Shereel''s Cancer Report', 220),

  -- Q23
  ('BHC - Class 69 - Holistic Cancer Support',
   'In Shereel''s cancer report, what was asafetida listed for in the digestive category?',
   'Stomach ache and cramp',
   'Diarrhea and colic',
   'Worms (parasites)',
   'Digestion (general)',
   'd',
   'Asafetida is listed simply as "digestion" in the digestive category of Shereel''s 2022 cancer report.',
   'Asafetida — digestion in Shereel''s 2022 cancer report.',
   'Shereel''s Cancer Report', 230),

  -- Q24
  ('BHC - Class 69 - Holistic Cancer Support',
   'In Shereel''s cancer report, what was black walnut listed for in the digestive category?',
   'Stomach ache and cramp',
   'Worms',
   'Diarrhea and colic',
   'General digestion',
   'b',
   'Black walnut leaf and hull are listed specifically for worms in the digestive category of Shereel''s 2022 cancer report.',
   'Black walnut leaf and hull — worms (digestive) in Shereel''s 2022 cancer report.',
   'Shereel''s Cancer Report', 240),

  -- Q25
  ('BHC - Class 69 - Holistic Cancer Support',
   'Which herb is listed as anticarcinogenic in the Herbal Actions section for its ability to "inhibit, mitigate, prevent, and cure" cancer?',
   'Mullein',
   'Elderberry',
   'Asafetida',
   'Corn',
   'c',
   'Asafetida is one of five herbs listed in the Herbal Actions section as anticarcinogenic — capable of inhibiting, mitigating, preventing, and curing cancer.',
   'Asafetida listed as anticarcinogenic: inhibits, mitigates, prevents, and can help cure cancer.',
   'Herbal Actions', 250),

  -- Q26
  ('BHC - Class 69 - Holistic Cancer Support',
   'In the Herbal Actions section, which of these herbs is NOT listed as anticarcinogenic?',
   'Garlic',
   'Poke root',
   'Sassafras',
   'Echinacea',
   'd',
   'The Herbal Actions section lists poke root, sassafras, asafetida, garlic, and black walnut as anticarcinogenic. Echinacea is listed in the lymphatic section, not in the anticarcinogenic list.',
   'Poke root listed as anticarcinogenic: inhibits, mitigates, prevents, and can help cure cancer.',
   'Herbal Actions', 260),

  -- Q27
  ('BHC - Class 69 - Holistic Cancer Support',
   'What is poke root''s specific role in the Nervines and Anti-Inflammatories chemo support tea?',
   'Nourishing and cooling tissue',
   'Removing metabolic waste and radiation chemicals',
   'Breaks up tumors and scar tissue (low dose)',
   'Soothes nerves and reduces hot tissue',
   'c',
   'Poke root at low dose is described as breaking up tumors and scar tissue in the chemo support tea list within the Nervines and Anti-Inflammatories section.',
   'Poke root (low dose) for chemo support: breaks up tumors and scar tissue in tea.',
   'Nervines and Anti-Inflammatories', 270),

  -- Q28
  ('BHC - Class 69 - Holistic Cancer Support',
   'In the Nervines and Anti-Inflammatories section, what does sassafras do during chemo support tea?',
   'Nourishes and cools tissue',
   'Removes metabolic waste',
   'Breaks up scar tissue',
   'Soothes nerves, reduces inflamed and hot tissue',
   'd',
   'Sassafras is described as having a good taste, soothes nerves, and reduces inflamed and hot tissue when taken as chemo support tea.',
   'Sassafras for chemo support: good taste, soothes nerves, reduces inflamed and hot tissue in tea.',
   'Nervines and Anti-Inflammatories', 280),

  -- Q29
  ('BHC - Class 69 - Holistic Cancer Support',
   'Per Shereel''s personal notes, why should tinctures be avoided during cancer chemo support?',
   'They are too difficult to dose accurately',
   'They interact with prescription chemotherapy drugs',
   'Alcohol is hot; we want cooling preparations',
   'Glycerites are more bioavailable than tinctures',
   'c',
   'The personal notes explicitly state "try to avoid tinctures — alcohol is hot and we want to cool — prefer glycerites and teas."',
   'Cleavers for chemo support: removes metabolic waste and radiation chemicals in tea.',
   'Nervines and Anti-Inflammatories', 290),

  -- Q30
  ('BHC - Class 69 - Holistic Cancer Support',
   'The Formulary Development case study involves which patient profile?',
   'White female, 45, Stage 2 breast cancer',
   'African American male, 59, Stage 3 cancer',
   'Asian American female, 67, ovarian cancer',
   'Latina male, 52, prostate cancer',
   'b',
   'The Formulary Development section describes a case study of an African American male, 59, with Stage 3 cancer, treated with herbal tonics for blood cleaning.',
   'St. John''s wort in herbal tonic formula for blood cleansing; Stage 3 cancer case study, African American male, 59.',
   'Formulary Development', 300),

  -- Q31
  ('BHC - Class 69 - Holistic Cancer Support',
   'Which herb is described as addressing "circulatory and lymphatic involvement" in the Stage 3 cancer case study?',
   'Lobelia',
   'St. John''s wort',
   'Black walnut',
   'Sassafras',
   'c',
   'Black walnut is specifically noted for circulatory and lymphatic involvement in the Stage 3 cancer formulary development case study.',
   'Black walnut for circulatory and lymphatic involvement in Stage 3 cancer case study, African American male, 59.',
   'Formulary Development', 310),

  -- Q32
  ('BHC - Class 69 - Holistic Cancer Support',
   'In the Formulary Development section, what were the herbal tonics primarily designed to address?',
   'Immune stimulation',
   'Pain relief',
   'Blood cleansing',
   'Hormonal balance',
   'c',
   'The formulary development case uses herbal tonics for blood cleaning, with St. John''s wort, Indian tobacco (lobelia), and black walnut.',
   'Indian tobacco (lobelia) in herbal tonic formula for blood cleansing; Stage 3 cancer case study, African American male, 59.',
   'Formulary Development', 320),

  -- Q33
  ('BHC - Class 69 - Holistic Cancer Support',
   'Which three herbs are named as key herbs for cancer care in the Herbal Support Strategy section?',
   'Garlic, cleavers, nettle',
   'Black walnut, damiana, ashwagandha',
   'Poke root, sassafras, comfrey',
   'Marshmallow, slippery elm, witch hazel',
   'b',
   'The Herbal Support Strategy section specifically names black walnut, damiana, and ashwagandha as the key herbs for cancer care.',
   'Black walnut is a key herb in the herbal support strategy for cancer care.',
   'Herbal Support Strategy', 330),

  -- Q34
  ('BHC - Class 69 - Holistic Cancer Support',
   'In the Client Case Review, which trio of herbs was recommended in a client''s herbal tea?',
   'Marshmallow root, cleavers, nettle',
   'Feverfew, comfrey, black cohosh',
   'Black walnut, damiana, ashwagandha',
   'CBD, turmeric, passionflower',
   'd',
   'The client case review recommends CBD, turmeric, and passionflower grouped together in an herbal tea for cancer support.',
   'CBD recommended in client herbal tea for cancer support alongside turmeric and passionflower.',
   'Client Case Review', 340),

  -- Q35
  ('BHC - Class 69 - Holistic Cancer Support',
   'In the Herb Preparation and Effects section, what does dark tea color indicate when cold-infusing herbs?',
   'The infusion needs to steep longer',
   'The presence of minerals',
   'The tea contains poke root or other dark barks',
   'The infusion has not cooled sufficiently',
   'b',
   'The notes state that dark tea color indicates mineral presence when making cold infusions for mineral extraction.',
   'Nettle included in cold infusion tea for mineral extraction; dark tea color indicates mineral presence.',
   'Herb Preparation and Effects', 350),

  -- Q36
  ('BHC - Class 69 - Holistic Cancer Support',
   'Which four herbs are mentioned for the cold infusion tea blend in Herb Preparation and Effects?',
   'Marshmallow, cleavers, nettle, witch hazel',
   'Nettle, red raspberry, oat straw, dandelion',
   'Skullcap, catnip, bacopa, gotu kola',
   'Black walnut, burdock, sassafras, poke root',
   'b',
   'The Herb Preparation and Effects section lists nettle, red raspberry, oat straw, and dandelion as possible tea components for the cold infusion blend.',
   'Red raspberry included in cold infusion tea for mineral extraction and therapeutic effects.',
   'Herb Preparation and Effects', 360),

  -- Q37
  ('BHC - Class 69 - Holistic Cancer Support',
   'Why is horsetail substituted for red raspberry in the patient''s infusion tea?',
   'Red raspberry has an anticoagulant interaction with iron supplementation',
   'Horsetail has more vitamin C than red raspberry',
   'Horsetail is a gentle diaphoretic that gently opens pores for sweating',
   'Red raspberry was worsening the patient''s heavy menses',
   'c',
   'The Herbal Formulas and Adjustments section describes horsetail as a gentle diaphoretic substituted for red raspberry to gently open pores for sweating.',
   'Horsetail substituted for red raspberry in infusion; gentle diaphoretic that gently opens pores for sweating.',
   'Herbal Formulas and Adjustments', 370),

  -- Q38
  ('BHC - Class 69 - Holistic Cancer Support',
   'Which herbs are mentioned for stress and sleep support formula updates in the Herbal Formulas and Adjustments section?',
   'Garlic, black walnut, sassafras',
   'Marshmallow, slippery elm, cleavers',
   'Skullcap, horsetail, red raspberry',
   'Bacopa, gotu kola, chamomile, catnip, or valerian',
   'd',
   'The Herbal Formulas and Adjustments section mentions bacopa, gotu kola, and suggests adding chamomile, catnip, or valerian for sleep aid.',
   'Chamomile added to stress and sleep support formula as sleep aid in patient case followup.',
   'Herbal Formulas and Adjustments', 380),

  -- Q39
  ('BHC - Class 69 - Holistic Cancer Support',
   'Which supplement is listed as a biologic agent in the 7 Principles of Non-Toxic Cancer Therapy?',
   'Zinc',
   'Iron',
   'Vitamin D',
   'Vitamin C',
   'd',
   'Vitamin C therapy is specifically listed as a biologic (biologics = Vit C therapy) among the 7 principles of non-toxic cancer therapy.',
   'Vitamin C therapy (biologics) listed as one of the 7 principles of non-toxic cancer therapy.',
   '7 Principles of Cancer Therapy', 390),

  -- Q40
  ('BHC - Class 69 - Holistic Cancer Support',
   'In Feri''s patient case followup, why was iron tincture added to her formula?',
   'To address lymphatic stagnation',
   'To support hormonal balance',
   'To address iron deficiency noted in followup',
   'To replace red raspberry in the infusion',
   'c',
   'Iron tincture was added to Feri''s formula specifically to address iron deficiency noted during the followup assessment.',
   'Iron tincture added to Feri''s formula to address iron deficiency noted in followup.',
   'Feri (Patient Case)', 400),

  -- Q41
  ('BHC - Class 69 - Holistic Cancer Support',
   'In Feri''s case, the infusion swap from red raspberry to horsetail was made to alleviate what symptom?',
   'Heavy and painful menses',
   'Brain fog',
   'Nighttime urination',
   'Energy crashes',
   'c',
   'The infusion substituted red raspberry with horsetail (a gentle diaphoretic) specifically to alleviate nighttime urination.',
   'Red raspberry in Feri''s infusion tea; swapped out for horsetail to alleviate nighttime urination.',
   'Feri (Patient Case)', 410),

  -- Q42
  ('BHC - Class 69 - Holistic Cancer Support',
   'Which two herbs were added to Feri''s stress glycerite to be taken at night for sleep support?',
   'Chamomile and valerian',
   'Bacopa and gotu kola',
   'Skullcap and catnip',
   'Red raspberry and horsetail',
   'c',
   'Skullcap and catnip were added to Feri''s stress glycerite together, to be taken at night for sleep support.',
   'Skullcap added to Feri''s stress glycerite (with catnip) to be taken at night for sleep support.',
   'Feri (Patient Case)', 420),

  -- Q43
  ('BHC - Class 69 - Holistic Cancer Support',
   'In the Chemotherapy Support section, what role does marshmallow root serve?',
   'Anti-tumor and lymphatic support',
   'Metabolic waste removal',
   'Blood support and minerals',
   'Immune support and nourishment',
   'd',
   'Marshmallow root is specifically described as providing immune support and nourishment during chemotherapy in the generated notes.',
   'Marshmallow root for immune support and nourishment during chemotherapy.',
   'Chemotherapy Support', 430),

  -- Q44
  ('BHC - Class 69 - Holistic Cancer Support',
   'In Shereel''s 2022 cancer report, burdock root was used for which digestive complaint?',
   'Diarrhea and colic',
   'Stomach ache and cramp',
   'Worms',
   'General digestion',
   'b',
   'Burdock root is listed specifically for stomach ache and cramp in the digestive category of Shereel''s 2022 cancer report.',
   'Burdock root — stomach ache and cramp in Shereel''s 2022 cancer report.',
   'Shereel''s Cancer Report', 440),

  -- Q45
  ('BHC - Class 69 - Holistic Cancer Support',
   'In Shereel''s cancer report, which herbs were listed under viral and bacterial infection?',
   'Cotton root, black cohosh, sassafras',
   'Echinacea, mullein, corn, pine',
   'Poke, lobelia, catnip',
   'Garlic, red onion, horehound, sage',
   'd',
   'Garlic, red onion, horehound, and sage are the four herbs listed under viral and bacterial infection in Shereel''s 2022 cancer report.',
   'Garlic — viral and bacterial infection in Shereel''s 2022 cancer report.',
   'Shereel''s Cancer Report', 450),

  -- Q46
  ('BHC - Class 69 - Holistic Cancer Support',
   'Sarsaparilla bark is listed in the generated notes as an anticarcinogenic herb with emphasis on which additional property?',
   'Nervine and sedative',
   'Lymphatic support',
   'Cooling and anti-inflammatory',
   'Hormonal stabilization',
   'b',
   'Sarsaparilla bark is listed as anticarcinogenic with lymphatic support as its notable secondary property.',
   'Sarsaparilla bark listed as an anticarcinogenic herb for cancer care; lymphatic support.',
   'Use of Herbal Treatment in Cancer Care', 460),

  -- Q47
  ('BHC - Class 69 - Holistic Cancer Support',
   'In Shereel''s personal notes, pine is listed under which category in the cancer report?',
   'Digestive',
   'Nervine',
   'Viral and bacterial infection',
   'Lymphatic',
   'd',
   'Pine (needles and resin) is listed under the lymphatic category in Shereel''s 2022 cancer report.',
   'Pine (needles and resin) — lymphatic support in Shereel''s 2022 cancer report.',
   'Shereel''s Cancer Report', 470),

  -- Q48
  ('BHC - Class 69 - Holistic Cancer Support',
   'In the Nervines and Anti-Inflammatories chemo support section, what does cleavers specifically remove?',
   'Tumors and scar tissue',
   'Inflammatory cytokines',
   'Metabolic waste and radiation chemicals',
   'Excess hormones',
   'c',
   'Cleavers is described as removing metabolic waste and radiation chemicals in the chemo support tea within the Nervines and Anti-Inflammatories section.',
   'Cleavers for chemo support: removes metabolic waste and radiation chemicals in tea.',
   'Nervines and Anti-Inflammatories', 480),

  -- Q49
  ('BHC - Class 69 - Holistic Cancer Support',
   'Black pepper''s inclusion in the Lymphatic Herbs list is primarily for which purpose?',
   'Anti-bacterial infection fighting',
   'Hormonal regulation',
   'Lymphatic support for cancer care',
   'Nervine and sedation',
   'c',
   'Black pepper is included in the Lymphatic Herbs list for lymphatic support in cancer care.',
   'Black pepper listed as lymphatic herb for cancer support.',
   'Lymphatic Herbs', 490),

  -- Q50
  ('BHC - Class 69 - Holistic Cancer Support',
   'Elderberry is listed in Shereel''s personal notes under which section?',
   'Shereel''s Cancer Report (lymphatic)',
   'Herbal Actions (anticarcinogenic)',
   'Lymphatic Herbs',
   'Anti-Cancer Formula 2',
   'c',
   'Elderberry appears in the Lymphatic Herbs section of Shereel''s personal notes as a lymphatic herb for cancer support.',
   'Elderberry listed as lymphatic herb for cancer support.',
   'Lymphatic Herbs', 500);

  RAISE NOTICE 'Class 69 quiz questions loaded: 50 questions.';
END $$;
