-- Migration 351: Class 71 — PMOS quiz questions
-- class_name: 'BHC - Class 71 - PMOS'
--
-- H = 46 distinct herbs/supplements
-- F = 24 named factual items (dosages, formulas, specific mechanisms)
-- target = clamp(15 + 46×4 + 24×1, 20, 50) = clamp(223, 20, 50) = 50
-- Correct option distribution: a=13, b=13, c=12, d=12

SET search_path TO herbal, public;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM herbal.class_quiz_questions
    WHERE class_name = 'BHC - Class 71 - PMOS'
  ) THEN
    RAISE NOTICE 'Class 71 PMOS quiz questions already loaded, skipping';
    RETURN;
  END IF;

  INSERT INTO herbal.class_quiz_questions
    (class_name, question_text, option_a, option_b, option_c, option_d,
     correct_option, explanation, snippet_text, section_header, sort_order)
  VALUES

    ('BHC - Class 71 - PMOS',
     'Blue Flag (Iris) is described as specific for which lipid issue in PMOS?',
     'LDL and VLDL specifically',
     'Low HDL',
     'Elevated triglycerides',
     'Total cholesterol',
     'a',
     'Blue Flag (Iris versicolor) is noted as specific for LDL and VLDL, and for venous and lymphatic stasis according to Priest and Priest.',
     'Iris/Blue Flag: specific for LDL and VLDL; specific for venous and lymphatic stasis (Priest and Priest). Dose: decoction 1 tsp:8oz water, 3 x day Tincture: 10-30 drops, 3 x day.',
     'Iris (Blue Flag)', 10),

    ('BHC - Class 71 - PMOS',
     'Spearmint (Mentha spicata) is used in PMOS as:',
     'A liver detoxifier via cholagogue activity',
     'A daily infusion for 30 days to lower testosterone and reduce hirsutism',
     'An adaptogen for stress-related androgen elevation',
     'A nervine to reduce HPA-axis overdrive',
     'b',
     'Spearmint has research support as a daily infusion for 30 days to lower testosterone levels and reduce hirsutism (facial hair) in PMOS.',
     'Spearmint (Mentha spicata): daily infusion for 30 days shown to lower levels of testosterone and reduce hirsutism (facial hair) in PMOS.',
     'Materia Medica', 20),

    ('BHC - Class 71 - PMOS',
     'What is the Vitex tincture dose used in PMOS?',
     '30–60 drops 2x/day',
     '10–20 drops 4x/day',
     '1–2 ml 3x/day',
     '2–5 ml 1x/day',
     'c',
     'Vitex tincture dose is 1–2 ml taken 3 times per day; infusion is 1 tsp berries to 8 oz water.',
     'Vitex: dopamine agonist stimulating FSH and LH; downregulates excess prolactin level for dopaminergic activity; sometimes takes 6 months to a year to effect. Tincture: 1-2 ml, 3 x day. Caution: may interact with dopamine antagonists and dopamine receptor blocking agents.',
     'Vitex', 30),

    ('BHC - Class 71 - PMOS',
     'In the PCOS formula (OGR / Licorice / White Peony / Cinnamon / Gotu kola), what is the total dose and frequency?',
     '2 ml 3x/day',
     '5 ml 1x/day',
     '3 ml 2x/day',
     '4 ml 2x/day',
     'd',
     'The PCOS formula is dosed at 4 ml 2x/day.',
     'PCOS formula: OGR 30ml, Licorice 10ml, White Peony 30ml, Cinnamon 20ml, Gotu kola 30ml (for extracellular matrix); 4ml 2x/day.',
     'PCOS Formula', 40),

    ('BHC - Class 71 - PMOS',
     'Which herb is described as reducing 5-alpha-reductase enzyme, addressing elevated androgens in PMOS?',
     'Reishi',
     'Holy Basil',
     'Maitake',
     'Spearmint',
     'a',
     'Reishi may reduce the 5-alpha-reductase enzyme, which converts precursors into testosterone, making it supportive for hormone-related hair loss and hyperandrogenism in PMOS.',
     'Reishi addresses elevated androgen in PMOS by reducing 5-alpha-reductase enzyme.',
     'Blood Sugar and Lipid Regulation', 50),

    ('BHC - Class 71 - PMOS',
     'White Peony reduces testosterone through action on which enzyme?',
     '5-alpha-reductase',
     'Aromatase',
     'Cyclooxygenase',
     'Lipase',
     'b',
     'White Peony reduces testosterone through action on the aromatase enzyme, which can simultaneously increase progesterone and regulate estrogen and prolactin.',
     'White Peony: reduces testosterone through action on the aromatase enzyme, this can increase progesterone, regulate estrogen and prolactin.',
     'Materia Medica', 60),

    ('BHC - Class 71 - PMOS',
     'The inositol-rich tea blend for PMOS includes which group of herbs?',
     'Ginseng, schizandra, rhodiola, reishi, astragalus',
     'Holy basil, turmeric, ginger, black cohosh, meadowsweet',
     'Astragalus, licorice, red clover, alfalfa, kudzu',
     'Spearmint, vitex, white peony, licorice, cinnamon',
     'c',
     'The inositol-rich tea blend for fertility support in PMOS consists of astragalus, licorice, red clover, alfalfa, and kudzu — all leguminous plants containing inositol that enhance insulin signal transduction.',
     'Inositol-rich tea blend for PMOS: astragalus, licorice, red clover, alfalfa, kudzu. Inositol enhances signal transduction when insulin binds to the cell membrane.',
     'Inositol Rich Tea Blend', 70),

    ('BHC - Class 71 - PMOS',
     'What tissue moistener is recommended to take alongside Andrographis due to its intensity?',
     'Aloe vera gel',
     'Slippery elm bark',
     'Calendula glycerite',
     'Marshmallow glycerite',
     'd',
     'Andrographis should be taken with a tissue moistener such as marshmallow glycerite to offset its intensity.',
     'Marshmallow glycerite as a companion to Andrographis — use as a tissue moistener given Andrographis''s intensity.',
     'Andrographis', 80),

    ('BHC - Class 71 - PMOS',
     'NAC is described in these notes as comparable to which pharmaceutical for insulin regulation in PMOS?',
     'Metformin',
     'Clomid',
     'Risperidone',
     'Spironolactone',
     'a',
     'NAC is described as comparable to metformin for insulin regulation — and improves menstrual regularity — in PMOS.',
     'NAC: comparable to metformin for insulin regulation in PMOS.',
     'Vitamins and Supplements', 90),

    ('BHC - Class 71 - PMOS',
     'Vitex acts via which mechanism to influence the hypothalamic-pituitary axis and reduce prolactin?',
     'Serotonin antagonism',
     'Dopamine agonist activity',
     'Estrogen receptor modulation',
     'Aromatase inhibition',
     'b',
     'Vitex is a dopamine agonist that downregulates excess prolactin through dopaminergic activity and stimulates FSH and LH from the pituitary.',
     'Vitex reduces elevated prolactin, lengthens luteal phase, increases progesterone, and supports pregnancy; acts via dopamine activity on the hypothalamic-pituitary axis.',
     'Hormonal Balance and Reproductive Health', 100),

    ('BHC - Class 71 - PMOS',
     'How long may Vitex take to show full clinical effect in PMOS?',
     '1–2 weeks',
     '1–3 months',
     '6 months to a year',
     '2–4 years',
     'c',
     'Vitex sometimes takes 6 months to a year to effect; it should be used as a tonic over time, not expected to produce rapid results.',
     'Vitex: dopamine agonist stimulating FSH and LH; sometimes takes 6 months to a year to effect; binds with certain opiate receptor sites without being sedative or addictive.',
     'Vitex', 110),

    ('BHC - Class 71 - PMOS',
     'How is Poke Root used as a low-dose lymphatic jumpstart in PMOS?',
     '1 ml 3x/day as a tincture',
     '10–20 drops 2x/day, short course',
     '5–10 drops 4x/day for 2 weeks',
     '2–3 drops per dose in formula, then shift to a longer-term lymphatic',
     'd',
     'Poke is used at a very low dose (2–3 drops per dose in formula) to push the lymph and give it a jumpstart, then the practitioner shifts to another lymphatic herb better suited for long-term use.',
     'Poke (low dose): for long-term metabolic disruption — a small amount (2-3 drops per dose in formula) to jumpstart lymph flow, then shift to a longer-term lymphatic. Dose: Tincture: Fresh 2-5 drops, Dry: 5-15 drops, to 3 x day. Caution: Caustic, use with care.',
     'Poke', 120),

    ('BHC - Class 71 - PMOS',
     'Licorice, when combined with White Peony, is noted to specifically reduce prolactin elevated by which medication?',
     'Risperidone',
     'Haloperidol',
     'Olanzapine',
     'Clozapine',
     'a',
     'Licorice with White Peony normalizes testosterone levels and specifically reduces prolactin elevated by the antipsychotic Risperidone.',
     'Licorice: reduces insulin resistance, improves fat deposition, restores normal menses; with White Peony normalizes testosterone levels; reduces elevated prolactin specifically induced by Risperidone.',
     'Materia Medica', 130),

    ('BHC - Class 71 - PMOS',
     'What is the Andrographis tincture dose in PMOS?',
     '30 drops 4x/day',
     '1 ml 3x/day',
     '2 ml 2x/day',
     '1–3 ml 3x/day',
     'b',
     'Andrographis is dosed at 1 ml tincture 3 times per day; it should not be used in pregnancy or when trying to conceive.',
     'Andrographis: specific for liver congestion when people have intolerance to fats; indicated in arthritis and Type 2 Diabetes. Dose: Tincture: 1 ml, 3 x day. Precautions: Not for use in pregnancy. Avoid when trying to conceive.',
     'Andrographis', 140),

    ('BHC - Class 71 - PMOS',
     'Ocotillo is dosed in PMOS at:',
     '1–2 ml 3x/day',
     '30–60 drops 2x/day',
     '10–30 drops 4x/day',
     '5–15 drops 3x/day',
     'c',
     'Ocotillo likes smaller doses more frequently — 10–30 drops tincture 4 times per day — to support circulation, lymphatic, and blood flow alongside its liver inflammation and fat digestion actions.',
     'Ocotillo with PMOS: improves circulation (lymphatic and blood); specific for liver inflammation and chronic poor fat digestion. Dose: tincture 10-30 drops 4x/day (smaller doses more frequently).',
     'Ocotillo', 150),

    ('BHC - Class 71 - PMOS',
     'The classic patient picture for Cinnamon in PMOS is:',
     'Hot, damp, inflamed',
     'Moist, anxious, restless',
     'Dry, hot, exhausted',
     'Cold, dry, frail',
     'd',
     'The Cinnamon patient picture is cold, dry, and frail — a warming and tonifying herb appropriate for this constitution.',
     'Cinnamon (Ceylon, Cinnamomum verum): warming, tonifying, hypoglycemic, hypolipidemic; picture of cinnamon person is cold dry frail; has eugenol (anti-inflammatory effects); increases blood circulation, promotes tissue regeneration; classic for postpartum hemorrhage and loss of uterine tone.',
     'Cinnamon', 160),

    ('BHC - Class 71 - PMOS',
     'Which supplement taken at 200 mcg for at least 8 weeks is described as beneficial for insulin metabolism in PMOS?',
     'Selenium',
     'Vitamin D',
     'Inositol',
     'L-carnitine',
     'a',
     'Selenium taken at 200 mcg for at least 8 weeks is described as beneficial for insulin metabolism in PMOS.',
     'Selenium: taken at least 8 weeks, beneficial for insulin metabolism in PMOS; 200 mcg dose.',
     'Nutrients', 170),

    ('BHC - Class 71 - PMOS',
     'The Astragalus decoction dose is:',
     '1 tsp root to 8 oz water',
     '2 tsp root to 12 oz water',
     '1 tbsp root to 16 oz water',
     '1/2 tsp root to 8 oz water',
     'b',
     'Astragalus decoction is 2 tsp root to 12 oz water; tincture dose is 1–3 ml 3x/day.',
     'Astragalus: circulation-enhancing, hepatoprotective, immune-specific; hormone modulating due to isoflavones; tonic, take over time. Dose: Decoction: 2 tsp root to 12 oz water, Tincture: 1-3 ml, 3 x day.',
     'Astragalus', 180),

    ('BHC - Class 71 - PMOS',
     'Gotu kola''s primary role in the PCOS formula is:',
     'Liver detoxification',
     'Lymphatic stimulation',
     'Connective tissue and extracellular matrix support',
     'Androgen reduction',
     'c',
     'Gotu kola is included in the PCOS formula specifically for connective tissue and extracellular matrix support (included at 30ml, the same volume as OGR and White Peony).',
     'Gotu kola provides connective tissue and extracellular matrix support in the PMOS formula.',
     'PMOS Formula', 190),

    ('BHC - Class 71 - PMOS',
     'In this class, the abbreviation PMOS stands for:',
     'Polycystic Metabolic Ovarian Syndrome',
     'Peripheral Metabolic Ovarian Syndrome',
     'Polyhormonal Metabolic Ovarian Syndrome',
     'Polyendocrine Metabolic Ovarian Syndrome',
     'd',
     'PMOS — Polyendocrine Metabolic Ovarian Syndrome — is the updated name for what was previously called PCOS (Polycystic Ovarian Syndrome), reflecting that the glands upstream (pituitary, hypothalamus, thyroid, adrenals) are the root drivers, not just the ovaries.',
     '4-week PMOS protocol: dong quai (anabolic, supports follicular stage) + vitex (stimulates pituitary LH release, lowers prolactin).',
     'PMOS Treatment Protocol', 200),

    ('BHC - Class 71 - PMOS',
     'Milk thistle is recommended in PMOS treatment for which specific function?',
     'Liver function and blood health',
     'Nervous system support with nervines',
     'Bone health via weight-bearing support',
     'Lymphatic stimulation',
     'a',
     'Milk thistle is cited for blood health — specifically liver function — as one of the key treatment steps in PMOS.',
     'Milk thistle for liver function — a key step in PMOS treatment addressing blood health.',
     'PMOS Treatment', 210),

    ('BHC - Class 71 - PMOS',
     'Maitake is described as an adaptogen that specifically:',
     'Lowers elevated prolactin through dopaminergic activity',
     'Induces ovulation in PMOS',
     'Improves insulin sensitivity via polysaccharides',
     'Reduces 5-alpha-reductase enzyme activity',
     'b',
     'Maitake is described as an adaptogen that can induce ovulation — a key therapeutic target in PMOS where anovulation is common.',
     'Maitake: adaptogen and indicated to induce ovulation in PMOS.',
     'Materia Medica', 220),

    ('BHC - Class 71 - PMOS',
     'How long must Omega-3 be taken to reduce testosterone levels in PMOS?',
     '2–4 weeks',
     '6–12 months',
     '2–6 months',
     '1–2 years',
     'c',
     'Omega-3 taken for 2–6 months can reduce testosterone levels and improve unwanted hair growth and menstrual irregularity in PMOS.',
     'Omega-3: taken 2-6 months can reduce testosterone levels, improve unwanted hair growth and menstrual irregularity in PMOS.',
     'Nutrients', 230),

    ('BHC - Class 71 - PMOS',
     'What is the Cinnamon tincture dose used in PMOS, taken 4x/day?',
     '20–50 drops',
     '5–10 drops',
     '50–100 drops',
     '10–20 drops',
     'a',
     'Cinnamon tincture is dosed at 20–50 drops 4x/day for hypoglycemic and hypolipidemic effects in PMOS.',
     'Cinnamon (Ceylon, Cinnamomum verum): warming, tonifying, hypoglycemic, hypolipidemic; Dose: Tincture: 20-50 drops, 4x/day.',
     'Cinnamon', 240),

    ('BHC - Class 71 - PMOS',
     'Which herb should NOT be used in persons with damp conditions or fungal infections because its polysaccharides feed yeast?',
     'Astragalus',
     'Reishi',
     'Echinacea',
     'Holy Basil',
     'a',
     'Astragalus is full of polysaccharides that feed yeast and fungus; it aggravates damp conditions and can drive them deeper into tissue. Reishi or Echinacea should be swapped in when fungal issues or mold toxicity are present.',
     'Astragalus: full of polysaccharides - feeds yeast and fungus; aggravates a damp condition — could prolong it, drive deeper into tissue; not good for fungal conditions or mold toxicity. Swap for Reishi, Echinacea.',
     'Astragalus', 250),

    ('BHC - Class 71 - PMOS',
     'The Getting Sick Blend shared at class check-in consists of:',
     'Reishi, astragalus, schizandra, rhodiola',
     'Echinacea, gotu kola, red root, elderberry glycerite',
     'Holy basil, licorice, red clover, alfalfa',
     'Turmeric, ginger, meadowsweet, black cohosh',
     'b',
     'The Getting Sick Blend is echinacea, gotu kola, red root, and elderberry glycerite.',
     'Getting Sick Blend: echinacea, gotu kola, red root, elderberry glycerite.',
     'Check-in', 260),

    ('BHC - Class 71 - PMOS',
     'Blue Flag (Iris) is described as specific for venous and lymphatic stasis according to:',
     'David Hoffmann',
     'Michael Moore',
     'Priest and Priest',
     'Matthew Wood',
     'c',
     'Iris (Blue Flag) is cited as specific for venous and lymphatic stasis according to Priest and Priest, in addition to its specific action on LDL and VLDL.',
     'Iris/Blue Flag: specific for LDL and VLDL; specific for venous and lymphatic stasis (Priest and Priest).',
     'Iris (Blue Flag)', 270),

    ('BHC - Class 71 - PMOS',
     'In the 4-week PMOS protocol, what is Dong Quai''s role?',
     'Stimulates pituitary LH release',
     'Reduces elevated prolactin',
     'Improves insulin sensitivity',
     'Anabolic support for the follicular stage',
     'd',
     'In the 4-week PMOS protocol, Dong Quai provides anabolic support for the follicular stage, while Vitex sparks the pituitary to release LH and lowers prolactin.',
     '4-week PMOS protocol: dong quai (anabolic, supports follicular stage) + vitex (stimulates pituitary LH release, lowers prolactin).',
     'PMOS Treatment Protocol', 280),

    ('BHC - Class 71 - PMOS',
     'Which herbal combination normalizes testosterone and reduces elevated prolactin in PMOS?',
     'Licorice and White Peony',
     'Spearmint and Reishi',
     'Holy Basil and Maitake',
     'Chasteberry and Dong Quai',
     'a',
     'Licorice and White Peony together normalize testosterone levels and reduce elevated prolactin, particularly prolactin induced by Risperidone.',
     'Licorice and White Peony together: improve insulin resistance and reduce elevated testosterone and prolactin, especially prolactin elevated by risperidone.',
     'Hormonal Balance and Reproductive Health', 290),

    ('BHC - Class 71 - PMOS',
     'Burdock is described as having which dual benefit for gut health and the microbiome in PMOS?',
     'Antifungal and antibacterial',
     'Both pre- and pro-biotic',
     'Mucilaginous and astringent',
     'Hepatoprotective and cholagogue',
     'b',
     'Burdock is described as both pre- and pro-biotic — it supports the microbiome while also providing prebiotic fiber (inulin), making it especially useful in PMOS gut health protocols.',
     'Burdock — both pre- and pro-biotic; supports gut health and microbiome in PMOS.',
     'Gut Health Support', 300),

    ('BHC - Class 71 - PMOS',
     'L-carnitine is described as working better than either alone when combined with:',
     'Metformin',
     'Risperidone',
     'Clomid',
     'Spironolactone',
     'c',
     'L-carnitine combined with Clomid (clomiphene) works better than either alone for fertility support in PMOS.',
     'L-carnitine: increases fertility; combined with Clomid works better than either alone in PMOS.',
     'Nutrients', 310),

    ('BHC - Class 71 - PMOS',
     'Cinnamon contains which constituent responsible for its anti-inflammatory (AI) effects?',
     'Berberine',
     'Quercetin',
     'Silymarin',
     'Eugenol',
     'd',
     'Cinnamon has eugenol, which provides anti-inflammatory (AI) effects; it also improves insulin sensitivity and glucose levels.',
     'Cinnamon (Ceylon, Cinnamomum verum): has eugenol (anti-inflammatory effects); can improve insulin sensitivity and glucose levels; increases blood circulation, promotes tissue regeneration.',
     'Cinnamon', 320),

    ('BHC - Class 71 - PMOS',
     'How much Oregon Grape Root (OGR) is in the PCOS formula?',
     '30 ml',
     '20 ml',
     '10 ml',
     '15 ml',
     'a',
     'OGR is included at 30ml in the PCOS formula — the same volume as White Peony and Gotu kola.',
     'PCOS formula: OGR 30ml, Licorice 10ml, White Peony 30ml, Cinnamon 20ml, Gotu kola 30ml (for extracellular matrix); 4ml 2x/day.',
     'PCOS Formula', 330),

    ('BHC - Class 71 - PMOS',
     'Andrographis is specifically indicated for which liver condition in PMOS?',
     'Viral hepatitis and elevated liver enzymes',
     'Liver congestion with intolerance to fats and sluggish liver',
     'Fatty liver disease from excess sugar intake',
     'Gallbladder dysfunction and bile insufficiency',
     'b',
     'Andrographis is specific for liver congestion when people have intolerance to fats and a sluggish liver — a common PMOS pattern related to fat metabolism disruption.',
     'Andrographis: specific for liver congestion when people have intolerance to fats; sluggish liver; indicated in arthritis and Type 2 Diabetes; actions include hepatoprotective, cholagogue, anti-inflammatory, adaptogen, hypoglycemic.',
     'Andrographis', 340),

    ('BHC - Class 71 - PMOS',
     'Flax seed is recommended at what daily dose in PMOS for anti-inflammatory and fiber support?',
     '1 teaspoon',
     '1/4 cup',
     '1–2 tablespoons',
     '2 tablespoons minimum',
     'c',
     'Flax is recommended at 1–2 tablespoons daily on top of food, cooked in, or in a smoothie for anti-inflammatory omega-3 fatty acids and fiber in PMOS.',
     'Flax seed — 1-2 tablespoons daily on food, cooked in, or in a smoothie; good source of short-chain fatty acids and fiber for PMOS.',
     'Inflammatory Reduction', 350),

    ('BHC - Class 71 - PMOS',
     'The three adaptogens combined together in a personal formulation at class check-in were:',
     'Rhodiola, reishi, astragalus',
     'Holy basil, lemon balm, hibiscus',
     'Vitex, licorice, white peony',
     'St. John''s wort, schizandra, ginseng',
     'd',
     'St. John''s wort, schizandra, and ginseng were used together in a personal adaptogen formula shared at class.',
     'St. John''s wort, schizandra, ginseng used together in a personal adaptogen formula.',
     'Personal Formulation Experiences', 360),

    ('BHC - Class 71 - PMOS',
     'Holy Basil is classified as an adaptogen with what primary action in PMOS?',
     'Blood sugar metabolism support',
     'Androgen reduction via 5-alpha-reductase inhibition',
     'Lymphatic stimulation',
     'Liver detoxification via cholagogue activity',
     'a',
     'Holy Basil is an adaptogen that primarily improves blood sugar metabolism in PMOS.',
     'Holy basil: adaptogen for blood sugar metabolism in PMOS.',
     'Blood Sugar and Lipid Regulation', 370),

    ('BHC - Class 71 - PMOS',
     'Inositol is described as enhancing which cellular process relevant to PMOS?',
     'Mitochondrial fat oxidation',
     'Signal transduction when insulin binds to the cell membrane',
     'SHBG production in the liver',
     'Aromatase enzyme activity',
     'b',
     'Inositol enhances signal transduction when insulin binds to the cell membrane — improving the cell''s ability to respond to insulin, thereby addressing insulin resistance in PMOS.',
     'Inositol-rich tea blend for PMOS: astragalus, licorice, red clover, alfalfa, kudzu. Inositol enhances signal transduction when insulin binds to the cell membrane.',
     'Inositol Rich Tea Blend', 380),

    ('BHC - Class 71 - PMOS',
     'In the PCOS formula, the amount of Licorice is:',
     '20 ml',
     '30 ml',
     '10 ml',
     '15 ml',
     'c',
     'Licorice is the smallest component at 10 ml in the PCOS formula (OGR 30ml, Licorice 10ml, White Peony 30ml, Cinnamon 20ml, Gotu kola 30ml).',
     'PCOS formula: OGR 30ml, Licorice 10ml, White Peony 30ml, Cinnamon 20ml, Gotu kola 30ml; 4ml 2x/day.',
     'PCOS Formula', 390),

    ('BHC - Class 71 - PMOS',
     'Vitex caution states it may interact with:',
     'Dopamine antagonists and dopamine receptor blocking agents',
     'SSRIs and MAOIs',
     'Beta-blockers and calcium channel blockers',
     'ACE inhibitors and ARBs',
     'd',
     'Vitex may interact with dopamine antagonists and dopamine receptor blocking agents, because it acts as a dopamine agonist and could oppose their effects.',
     'Vitex: Caution: This plant may interact with dopamine antagonists and dopamine receptor blocking agents.',
     'Vitex', 400),

    ('BHC - Class 71 - PMOS',
     'In which PMOS clinical picture is Ocotillo specifically indicated?',
     'PMOS with poor fat digestion, liver inflammation, and need for lymphatic and blood circulation support',
     'PMOS with anxiety, HPA-axis overdrive, and sleep disruption',
     'PMOS with hypothyroidism and cold extremities',
     'PMOS with heavy bleeding and fibroids',
     'a',
     'Ocotillo is specifically indicated in PMOS for improving circulation (lymphatic and blood), liver inflammation, and chronic poor fat digestion.',
     'Ocotillo with PMOS: improves circulation (lymphatic and blood); specific for liver inflammation and chronic poor fat digestion. Dose: tincture 10-30 drops 4x/day.',
     'Ocotillo', 410),

    ('BHC - Class 71 - PMOS',
     'What is the dose of the rhodiola, cardamom, fennel tincture shared at class?',
     '2 drops once daily',
     '5 drops three times a day',
     '10 drops twice daily',
     '15 drops once daily',
     'b',
     'Rhodiola, cardamom, fennel tincture was used at five drops, three times a day.',
     'Rhodiola, cardamom, fennel tincture at five drops, three times a day.',
     'Personal Formulation Experiences', 420),

    ('BHC - Class 71 - PMOS',
     'Which herb is described as specific for LDL/VLDL AND venous and lymphatic stasis (Priest and Priest)?',
     'Poke Root',
     'Ocotillo',
     'Iris / Blue Flag',
     'Red Root',
     'c',
     'Iris versicolor (Blue Flag) is specific for LDL and VLDL, and for venous and lymphatic stasis per Priest and Priest — making it a distinctive lipid-focused lymphatic in PMOS.',
     'Iris/Blue Flag: specific for LDL and VLDL; specific for venous and lymphatic stasis (Priest and Priest). Dose: Decoction: 1 tsp: 8 oz water, 3 x day; Tincture: 10-30 drops, 3 x day.',
     'Iris (Blue Flag)', 430),

    ('BHC - Class 71 - PMOS',
     'Which pituitary hormone does Vitex specifically downregulate?',
     'FSH',
     'LH',
     'AMH',
     'Prolactin',
     'd',
     'Vitex downregulates excess prolactin through its dopaminergic activity — elevated prolactin suppresses fertility, and Vitex is specifically indicated when prolactin is high in PMOS.',
     'Vitex: dopamine agonist in the body; downregulates excess prolactin level for dopaminergic activity; reduce elevated prolactin, lengthen luteal phase, increase progesterone.',
     'Materia Medica', 440),

    ('BHC - Class 71 - PMOS',
     'The Vitex infusion preparation is:',
     '1 tsp berries to 8 oz water',
     '1 tbsp berries to 16 oz water',
     '2 tsp berries to 8 oz water',
     '1 tsp berries to 16 oz water',
     'a',
     'Vitex infusion is prepared at 1 tsp berries to 8 oz water.',
     'Vitex: Infusion: 1 tsp berries: 8oz water; Tincture: 1-2 ml, 3 x day.',
     'Vitex', 450),

    ('BHC - Class 71 - PMOS',
     'The Poke Root fresh tincture dose used in PMOS is:',
     '10–20 drops 3x/day',
     '2–5 drops up to 3x/day',
     '1–2 ml 3x/day',
     '30–60 drops 2x/day',
     'b',
     'Fresh Poke Root is dosed at 2–5 drops up to 3x/day; dry is 5–15 drops. It is used at a very low dose due to its caustic nature.',
     'Poke (low dose): Tincture: Fresh 2-5 drops, Dry: 5-15 drops, to 3 x day. Caution: Caustic, use with care.',
     'Poke', 460),

    ('BHC - Class 71 - PMOS',
     'Reishi should be substituted for Astragalus specifically when a patient has:',
     'Acute infectious illness',
     'Elevated insulin resistance and metabolic syndrome',
     'A damp condition, fungal infection, or mold toxicity',
     'Low prolactin levels',
     'c',
     'Reishi (and Echinacea) are recommended as a swap for Astragalus in patients with damp conditions, fungal infections, or mold toxicity because Astragalus''s polysaccharides feed yeast.',
     'Reishi as alternative to Astragalus in damp or fungal conditions (Astragalus'' polysaccharides can aggravate damp/fungal).',
     'Astragalus', 470),

    ('BHC - Class 71 - PMOS',
     'The stress support formula shared in class included rhodiola and which three other herbs?',
     'Dandelion, nettle, ginger',
     'Astragalus, reishi, schizandra',
     'Turmeric, ginger, black cohosh',
     'Lemon balm glycerite, hibiscus, hawthorn',
     'd',
     'The stress support formula was lemon balm glycerite, hibiscus, hawthorn, and rhodiola — for clarity and calmness in the body.',
     'Lemon balm glycerite, hibiscus, hawthorn, rhodiola — clarity and calmness in body.',
     'Stress Support', 480),

    ('BHC - Class 71 - PMOS',
     'Cinnamon''s plant part and preparation used in PMOS are:',
     'Bark — tincture and decoction',
     'Leaf — essential oil or glycerite',
     'Root — decoction only',
     'Seed — cold extract',
     'a',
     'Cinnamon bark is prepared as a tincture (20–50 drops 4x/day) or decoction.',
     'Cinnamon: Part Used: Bark. Preparation: Tincture, Decoction. Dose: Tincture: 20-50 drops, 4x/day.',
     'Cinnamon', 490),

    ('BHC - Class 71 - PMOS',
     'White Peony''s dual hormonal mechanism in PMOS is:',
     'Reduces FSH through pituitary feedback; increases LH',
     'Reduces testosterone via aromatase enzyme; increases progesterone',
     'Reduces LH through dopamine activity; increases estrogen',
     'Reduces prolactin via dopamine; increases progesterone and estrogen',
     'b',
     'White Peony reduces testosterone through action on the aromatase enzyme, which in turn can increase progesterone and regulate estrogen and prolactin.',
     'White Peony: reduces testosterone through action on the aromatase enzyme, this can increase progesterone, regulate estrogen and prolactin.',
     'Materia Medica', 500);

END $$;
